### ISSUE TITLE
Mapping sent to ES incorrect for attachmenmt type

### ISSUE THREAD

**Issue by richardmiller-zz** [FriendsOfSymfony/FOSElasticaBundle#100]
As reported by @vittore in GH-99:

Hi,

I think there is a little bug.

If I use this in config.yml:

```
foq_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        biblio:
            types:
                article:
                    mappings:
                        contents:
                            type: attachment
```

I espect a metadata like: 

```
    curl -X PUT "localhost:9200/biblio/article/_mapping" -d '{
      "article" : {
        "properties" : {
          "contents" : {
            "type" : "attachment",
            "fields" : {
              "contents" : { "term_vector":"with_positions_offsets",  "analyzer": "snowball"  }
            }
          }
       }
      }
    }'
```

But I get a (string) type.

```
{
state: open
settings: {
index.number_of_shards: 5
index.number_of_replicas: 1
}
mappings: {
article: {
properties: {
title: {
type: string
}
contents: {
type: string
}
}
}
}
aliases: [ ]
}
```
