### ISSUE TITLE
include_in_all on the type level not accepted

### ISSUE THREAD

**Issue by Tobion** [FriendsOfSymfony/FOSElasticaBundle#1016]
In #405 it was fixed that one can use `include_in_all` on properties so that it gets inherited in elasticsearch. But one can also add `include_in_all` directly on the type so it gets inherited for all properties on the type. See the second example in https://www.elastic.co/guide/en/elasticsearch/reference/current/include-in-all.html

But this cannot be used in elastica bundle as the following raises an error that `include_in_all` is not accepted there.

```
fos_elastica:
    indexes:
        myindex:
            types:
                mytype:
                    include_in_all: false
                    properties:
```
