### ISSUE TITLE
Creating the root index

### ISSUE THREAD

**Issue by bertoost** [FriendsOfSymfony/FOSElasticaBundle#1023]
I have my configuration like this;

```
fos_elastica:
  clients:
    default: { host: %elasticsearch_host%, port: %elasticsearch_port% }
  indexes:
    app:
      index_name: my_app_name
      types:
        # etc
```

Everything works fine when I manually create the "my_app_name" index via a curl -XPUT command but I think the populate or reset command should create this? Or do I miss something?
