### ISSUE TITLE
Index only specific objects

### ISSUE THREAD

**Issue by behramcelen** [FriendsOfSymfony/FOSElasticaBundle#1027]
I want index only published journal object on my project. But i can not managed :(
My elastica.yml like below for journal type;
```
journal:
          mappings:
            id: { type: integer }
            translations:
              type: "object"
              properties:
                locale:
                  type: string
                title:
                  type: string
                subtitle:
                  type: string
                description:
                  type: string
                titleAbbr:
                  type: string
            title:
              type: string
              fields:
                raw:
                  type: string
                  index: not_analyzed
            slug: { type: string }
            subtitle: { type: string }
            description: { type: string }
            issn: { type: string }
            eissn: { type: string }
            founded: { type: date }
            tags:
              analyzer: "keyword"
              type: string
            status: { "index": "not_analyzed" }
            published: { "index": "not_analyzed",type: boolean }
            accessModal: { type: integer }
            subjects:
              type: object
              properties:
                id: { type: integer }
                subject: { type: string, index: not_analyzed }
            publisher:
              type: object
              properties:
                name:
                  type: string
                  fields:
                    raw:
                      type: string
                      index: not_analyzed
                slug: { type: string }
                publisherType:
                  type: object
                  properties:
                    name: { index: not_analyzed }
```
On my system we only expose `published = status(1)` journal object on public pages. So ı don't want to index to elasticsearch unpublished objects. How can i manage?
