### ISSUE TITLE
 Symfony ElasticaBundle listener and query_builder_method

### ISSUE THREAD

**Issue by shubaivan** [FriendsOfSymfony/FOSElasticaBundle#1047]
I need upload in elastic, when I created entity Lead, only who have status approved, this is my, mapping:

```
                 persistence:
                      driver: orm
                      model: Artel\ProfileBundle\Entity\Lead
                      provider:
                        query_builder_method: createIsActiveQueryBuilder
                      listener: ~
                      finder: ~
```

and my query_builder_method: createIsActiveQueryBuilder:

```
public function createIsActiveQueryBuilder()
{
    $qb = $this->getEntityManager()->createQueryBuilder('d');

    $qb
        ->select('d')
        ->from('ArtelProfileBundle:Lead', 'd')
        ->where('d.statusLead = :status')
        ->setParameter('status', 'approved')
    ;

    return $qb;
}
```

When I run I have upload lead only status approved

```
app/console fos:elastica:populate --no-reset
```

created Lead

```
    $lead = new Lead();
    //some logic
    $manager->persist($lead);
    $manager->flush();
```

But when I create new Lead with default status 'not_approved' this lead uploaded in elastic, why I not understand listener upload this lead, why not work query_builder ?

**Comment by ruudvanderweijde** [comment]
Maybe you're looking for this: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/Resources/doc/types.md#testing-if-an-object-should-be-indexed

```yml
    types:
        users:
            indexable_callback: 'approved'
```
