### ISSUE TITLE
FosElasticBundle not Analyzedfield

### ISSUE THREAD

**Issue by shubaivan** [FriendsOfSymfony/FOSElasticaBundle#1061]
I have elastic search 2.2.1 and "friendsofsymfony/elastica-bundle": "~3.0",

I need add not analyzed for field in index I add in config to filed skill "fields" and "index: not_analyzed", but after 

```
app/console fos:elastica:populate --no-reset --index=directory --type=skill
```

In mapping still have 

```
"skill": {
  "properties": {
    "skill": {
      "type": "string"
    },
```

this my config:

```
    directory:
        finder: ~
        types:
                skill:
                 mappings:
                      id:
                         type: integer
                      skill:
                         type: integer
                         fields:
                            raw:
                                type: integer
                                index: not_analyzed
```

what I'am doing wrong, any ideas, help

**Comment by behramcelen** [comment]
can you try below snippet;
```
directory:
        finder: ~
        types:
                skill:
                 mappings:
                      id:
                         type: integer
                      skill:
                         type: integer
                         index: not_analyzed
```
And skill is integer? And can you paste your entity relations.
