### ISSUE TITLE
Using defined “index_name” when running reset/populate commands

### ISSUE THREAD

**Issue by oachoor** [FriendsOfSymfony/FOSElasticaBundle#1072]
I'm building a multi-demo application with multiple indexes, one index per demo.

Actually the reset/populate commands takes only "my_index" as value, which will refresh all Elasticsearch indexes :

```
php ezpublish/console fos:elastica:reset --index=my_index
php ezpublish/console fos:elastica:populate --index=my_index
```

I will need to pass the specified "index_name" like this :

```
php ezpublish/console fos:elastica:reset --index=my_unique_index_per_demo
php ezpublish/console fos:elastica:populate --index=my_unique_index_per_demo
```

My yaml configuration looks like :

```
indexes:
    my_index:
        #use_alias: true ?
        index_name: my_unique_index_per_demo
```

Now I'm using curl requests to do this, but just wondering if there has been any solution to refresh only the index by name.
