### ISSUE TITLE
Unable to create a custom listener: Catchable Fatal Error: addEventSubscriber

### ISSUE THREAD

**Issue by BentCoder** [FriendsOfSymfony/FOSElasticaBundle#1088]
Hi,

I'm getting error below while trying to create a custom listener for handling 1 to N associations between **Post** and **Comment**.

**ERROR**

`ContextErrorException in EventManager.php line 137:
Catchable Fatal Error: Argument 1 passed to Doctrine\Common\EventManager::addEventSubscriber() must be an instance of Doctrine\Common\EventSubscriber, instance of Application\SearchBundle\Listener\PostIndexListener given, called in /Library/WebServer/Documents/symfony/elastica/app/cache/dev/appDevDebugProjectContainer.php on line 778 and defined`

**VERSIONS**
symfony/symfony -> 2.6.11
friendsofsymfony/elastica-bundle -> 3.1.8

**MAPPING**
```
fos_elastica:
    clients:
        default: { host: 127.0.0.1, port: 9200 }
    indexes:
        post_index:
            client: default
            index_name: post_index
            types:
                post:
                    mappings:
                        id:
                            type: integer
                            index: not_analyzed
                        title:
                            type: string
                            analyzer: english
                        comment:
                            type: object
                            properties:
                                id:
                                    type: integer
                                    index: not_analyzed
                                message:
                                    type: string
                    persistence:
                        driver: orm
                        model: Application\SearchBundle\Entity\Post
                        finder: ~
                        provider: ~
                        listener:
                            service: application_search.listener.post_index
```

**services.yml**

```
services:
    application_search.listener.post_index:
        class: Application\SearchBundle\Listener\PostIndexListener
        arguments:
            - @fos_elastica.object_persister.post_index.post
            - @fos_elastica.indexable
            - ['postPersist', 'postUpdate', 'postRemove', 'preRemove']
        calls:
            - [ setContainer, [ '@service_container', @fos_elastica.object_persister.post_index.post ] ]
        tags:
            - { name: 'doctrine.event_subscriber' }
```

**PostIndexListener**

```
namespace Application\SearchBundle\Listener;

use Doctrine\Common\Persistence\Event\LifecycleEventArgs;
use FOS\ElasticaBundle\Doctrine\Listener;
use FOS\ElasticaBundle\Persister\ObjectPersister;
use Symfony\Component\DependencyInjection\ContainerInterface;

class PostIndexListener extends Listener
{
    /** @var ContainerInterface */
    private $container;
    /** @var ObjectPersister */
    private $postPersister;

    public function setContainer(
        ContainerInterface $container,
        ObjectPersister $postPersister
    ) {
        $this->container = $container;
        $this->postPersister = $postPersister;
    }

    public function postPersist(LifecycleEventArgs $eventArgs)
    {
    }

    public function postUpdate(LifecycleEventArgs $eventArgs)
    {
    }

    public function postRemove(LifecycleEventArgs $eventArgs)
    {
    }

    public function preRemove(LifecycleEventArgs $eventArgs)
    {
    }
}
```

I've read and tried all of these below and many more:

- [https://github.com/FriendsOfSymfony/FOSElasticaBundle/issues/143](https://github.com/FriendsOfSymfony/FOSElasticaBundle/issues/143)
- [http://stackoverflow.com/questions/25987371/change-es-data-on-nested-object-changes-automatically](http://stackoverflow.com/questions/25987371/change-es-data-on-nested-object-changes-automatically)
- [http://stackoverflow.com/questions/21909763/symfony2-foselasticabundle-update-index-for-all-entities-related-to-the-entity-u?rq=1](http://stackoverflow.com/questions/21909763/symfony2-foselasticabundle-update-index-for-all-entities-related-to-the-entity-u?rq=1)
- [http://stackoverflow.com/questions/34393410/foselasticabundle-update-nested-entity](http://stackoverflow.com/questions/34393410/foselasticabundle-update-nested-entity)
- [https://groups.google.com/forum/#!topic/elastica-php-client/WTONX-zBTI4](https://groups.google.com/forum/#!topic/elastica-php-client/WTONX-zBTI4)
