### ISSUE TITLE
Unable to populate the search index (Trying to get property of non-object)

### ISSUE THREAD

**Issue by nightmarelie** [FriendsOfSymfony/FOSElasticaBundle#1090]
I use the version 3.0.1 with the JMS serializer

My config:

```
fos_elastica:
    serializer:
        callback_class: FOS\ElasticaBundle\Serializer\Callback
        serializer: serializer
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        app:
            types:
                local_product:
                    serializer:
                        groups: [ elastica ]
                    persistence:
                        driver: orm
                        model: AppBundle\Entity\LocalProduct
                        provider: ~
                        listener:
                            immediate: ~
                        finder: ~
```

After execute:

```
php app/console fos:elastica:populate
```

We get the error message:

**[Symfony\Component\Debug\Exception\ContextErrorException]**
**Trying to get property of non-object**

Exception trace:

```
() at /var/www/api/src/AppBundle/Service/CountryService.php:70
 Symfony\Component\Debug\ErrorHandler->handleError() at /var/www/api/src/AppBundle/Service/CountryService.php:70
 AppBundle\Service\CountryService->getCountryId() at /var/www/api/src/AppBundle/Service/ProductService.php:264
 AppBundle\Service\ProductService->__construct() at /tmp/devotion/cache/dev/appDevDebugProjectContainer.php:3871
 appDevDebugProjectContainer->getApp_Service_ProductServiceService() at /var/www/api/app/bootstrap.php.cache:2155
 Symfony\Component\DependencyInjection\Container->get() at /tmp/devotion/cache/dev/appDevDebugProjectContainer.php:3759
 appDevDebugProjectContainer->getApp_Serializer_Subscriber_ProductPreSubscriberService() at /var/www/api/app/bootstrap.php.cache:2155
 Symfony\Component\DependencyInjection\Container->get() at /var/www/api/vendor/jms/serializer/src/JMS/Serializer/EventDispatcher/LazyEventDispatcher.php:48
 JMS\Serializer\EventDispatcher\LazyEventDispatcher->initializeListeners() at /var/www/api/vendor/jms/serializer/src/JMS/Serializer/EventDispatcher/EventDispatcher.php:80
 JMS\Serializer\EventDispatcher\EventDispatcher->hasListeners() at /var/www/api/vendor/jms/serializer/src/JMS/Serializer/GraphNavigator.php:163
 JMS\Serializer\GraphNavigator->accept() at /var/www/api/vendor/jms/serializer/src/JMS/Serializer/Serializer.php:176
 JMS\Serializer\Serializer->visit() at /var/www/api/vendor/jms/serializer/src/JMS/Serializer/Serializer.php:82
 JMS\Serializer\Serializer->JMS\Serializer\{closure}() at n/a:n/a
 call_user_func() at /var/www/api/vendor/phpoption/phpoption/src/PhpOption/Some.php:89
 PhpOption\Some->map() at /var/www/api/vendor/jms/serializer/src/JMS/Serializer/Serializer.php:85
 JMS\Serializer\Serializer->serialize() at /var/www/api/vendor/friendsofsymfony/elastica-bundle/Serializer/Callback.php:52
 FOS\ElasticaBundle\Serializer\Callback->serialize() at n/a:n/a
 call_user_func() at /var/www/api/vendor/friendsofsymfony/elastica-bundle/Persister/ObjectSerializerPersister.php:45
 FOS\ElasticaBundle\Persister\ObjectSerializerPersister->transformToElasticaDocument() at /var/www/api/vendor/friendsofsymfony/elastica-bundle/Persister/ObjectPersister.php:120
 FOS\ElasticaBundle\Persister\ObjectPersister->insertMany() at /var/www/api/vendor/friendsofsymfony/elastica-bundle/Doctrine/AbstractProvider.php:95
 FOS\ElasticaBundle\Doctrine\AbstractProvider->doPopulate() at /var/www/api/vendor/friendsofsymfony/elastica-bundle/Provider/AbstractProvider.php:71
 FOS\ElasticaBundle\Provider\AbstractProvider->populate() at /var/www/api/vendor/friendsofsymfony/elastica-bundle/Command/PopulateCommand.php:178
 FOS\ElasticaBundle\Command\PopulateCommand->populateIndexType() at /var/www/api/vendor/friendsofsymfony/elastica-bundle/Command/PopulateCommand.php:149
 FOS\ElasticaBundle\Command\PopulateCommand->populateIndex() at /var/www/api/vendor/friendsofsymfony/elastica-bundle/Command/PopulateCommand.php:124
 FOS\ElasticaBundle\Command\PopulateCommand->execute() at /var/www/api/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:256
 Symfony\Component\Console\Command\Command->run() at /var/www/api/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:846
 Symfony\Component\Console\Application->doRunCommand() at /var/www/api/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:189
 Symfony\Component\Console\Application->doRun() at /var/www/api/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:96
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /var/www/api/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:120
 Symfony\Component\Console\Application->run() at /var/www/api/app/console:27
```

We use jms subscribers
# src\AppBundle\Resources\config\serializer.yml

```
services:
    app.serializer.subscriber.product_pre_subscriber:
        class: AppBundle\Serializer\Subscriber\LocalProductPreSubscriber
        arguments:
```

**issue in this line. But i need this service !**
            - @app.service.product_service 

```
        tags:
            - { name: jms_serializer.event_subscriber }
```

Has anyone an idea on what to do ?
