### ISSUE TITLE
How do I connect to Elastic Cloud?

### ISSUE THREAD

**Issue by PaddyLock** [FriendsOfSymfony/FOSElasticaBundle#1126]
Hi, I need to connect to an external Elastic Cloud service. I have tried both the following configurations with no success:

```
fos_elastica:
    clients:
        default:
            host: https://*************.eu-west-1.aws.found.io:9243/
```

```
fos_elastica:
    clients:
        default:
            host: https://*************.eu-west-1.aws.found.io
            port: 9243
```

If I connect manually with curl I can connect fine with:

`curl -X GET 'https://*************.eu-west-1.aws.found.io:9243/'`

but if I try

`php app/console fos:elastica:populate`

then I get

```
[Elastica\Exception\Connection\HttpException]  
  Couldn't resolve host 
```

**Comment by PaddyLock** [comment]
I now have a working config like this:

fos_elastica:
    clients:
        default:
            host: readwrite:password@******************.eu-west-1.aws.found.io:9200/

readwrite:password is the user name and password

HOWEVER, when I run `php app/console fos:elastica:populate`

I get

```
Resetting products
 4525/4525 [============================] 100%
Populating products/productRefreshing products

                                          
  [Elastica\Exception\ResponseException]  
  failed to parse, document is empty 
```

**Comment by PaddyLock** [comment]
Further more I can query the elastic cloud service directly in the browser and get results, but not when using elastica bundle

**Comment by giovannialbero1992** [comment]
@PaddyLock Maybe there is an error on index's mapping. can you attach your mapping ?

**Comment by PaddyLock** [comment]
it worked fine when I was using a local elasticsearch. here is my full config

```
fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }
        cloud:
            host: readwrite:password@***************.eu-west-1.aws.found.io:9200/
    indexes:
        products:
            client: cloud
            types:
                product:
                    mappings:
                        name: { boost: 5 }
                        commonName: { boost: 5 }
                        sku: { boost: 3 }
                        description:
                        isRemedy:
                        countries:
                            type: "nested"
                            properties:
                                code: ~
                        book:
                            type: "nested"
                            properties:
                                author: ~
                                isbn: ~
                        brand:
                            type: "nested"
                            properties:
                                name: { boost: 4 }

                    persistence:
                        driver: orm
                        model: Helios\CoreBundle\Entity\Product
                        provider: ~
                        finder: ~
                        listener: ~
                        elastica_to_model_transformer:
                            ignore_missing: true
                        listener:
                            is_indexable_callback: "isPublic"
```

**Comment by giovannialbero1992** [comment]
Try to connect to host with this authentication config:
```
default:
            host: %elastica.host%
            port: %elastica.port%
            headers:
                Authorization: %elastica.authheader%
```

**Comment by PaddyLock** [comment]
@giovannialbero1992 what should the value of elastica.authheader be?

**Comment by giovannialbero1992** [comment]
Sorry, I've pasted a generic exapmle but maybe the documentation is better than https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/Resources/doc/cookbook/elastica-client-http-headers.md

**Comment by PaddyLock** [comment]
giovannialbero1992 I read the documentation before. I've tried it that way before and it doesn't connect. The only way I can get it to connect is 

host: readwrite:password@***************.eu-west-1.aws.found.io:9200/

It seems to write but not read

**Comment by giovannialbero1992** [comment]
Are you working on Amazon right? maybe there is some security group doesn't set properly

**Comment by PaddyLock** [comment]
@giovannialbero1992 Yes it is AWS, but it is through the hosted Elastic Cloud Service - https://www.elastic.co/cloud/as-a-service and I am using the readwrite user that I have set up

**Comment by PorridgeBear** [comment]
I've just connected to our HTTPS Elastic Cloud instance as follows:

```
    clients:
        default:
            host: 12345678.eu-west-1.aws.found.io
            port: 9243
            transport: Https
            headers:
                Authorization: "Basic QWxhZGRpbjpPcGVuU2VzYW1l"
```

Where QWxhZGRpbjpPcGVuU2VzYW1l is a base64 encoded Basic Authentication pair:

`echo -n "Aladdin:OpenSesame" | base64`
