### ISSUE TITLE
How to create type mapping dynamically

### ISSUE THREAD

**Issue by a-ast** [FriendsOfSymfony/FOSElasticaBundle#1127]
I have an attributes table. All attributes have a value and a type. All values are stored as text in a database table.
However, I need to build index (dynamically) and specify a type for each attribute:

``` yaml
                mappings:
                    attribute_map:
                        type: object
                        properties:
                            attr1:
                                type: float
                            attr2:
                                type: integer
                            attr3:
                                type: string
```

I tried to call $type->setMapping(...) in prePopulateListener but it doesn't modify an actual type mapping.
Is there any other way to do it?

**Comment by alekitto** [comment]
The `PRE_TYPE_POPULATE` event is called before the type reset call, so the mapping will be overwritten immediately.
You should try to call a `setMapping` in a `POST_TYPE_RESET` (`elastica.index.type_post_reset`) event listener

**Comment by AAstakhov** [comment]
Thank you for a tip, @alekitto. It works, but unfortunately POST_TYPE_RESET event is triggered after a mapping is sent to ES server.

```php
        $type->setMapping($mapping);

        $this->dispatcher->dispatch(TypeResetEvent::POST_TYPE_RESET, $event);
```

It means that I send mapping twice.

I see that FOSElasticaBundle is not designed for dynamic mappings. Index configurations are built in compiler passes, so it is not easy to change mapping after a container is built.

My idea is to introduce another event/events:

```php
        $mapping = new Mapping();
       
        $event = new TypeMappingEvent($indexName, $typeName, $mapping);
        $this->dispatcher->dispatch(TypeResetEvent::POST_TYPE_MAPPING, $event);

        $type->setMapping($mapping); 
```

It would allow to modify mappings on-the-fly.
Does it make sense?

**Comment by oleg-andreyev** [comment]
@a-ast If I understood correctly, I'd suggest reviewing dynamic templates https://www.elastic.co/guide/en/elasticsearch/reference/current/dynamic-templates.html

**Comment by XWB** [comment]
Dynamic templates should to the trick, I have used it a few times before.

```
types:
    my_type:
        attr1:
            match: attr1_name
            mapping:
                type: float
        attr2:
            match: attr2_name
            mapping:
                type: integer
```
