### ISSUE TITLE
parent definition fos_elastica.listener.prototype.propel of non existing listener missing

### ISSUE THREAD

**Issue by swietek** [FriendsOfSymfony/FOSElasticaBundle#1144]
Hi,

I've defined a simple fos elastica configuration for my symfony project which uses propel, not doctrine.
I'd like to index an entity called Item, which is stored in src\Model\Item\Item.php and extends  src\Model\Item\om\BaseItem.php

Here is the fos_elastica.yml which is imported in config.yml

```
fos_elastica:
    clients:
        default: { host: %elastic_host%, port: %elastic_port% }
    indexes:
        project:
            types:
                item:
                    mappings:
                        id: { type: integer }
                        itemno: { type: string }
                    persistence:
                        driver: propel
                        model: Model\Item\Item
                        provider: ~
```

I'm wondering getting following error message, where I miss a parent definition of a listener, which are actually not supported for propel - as mentioned in the documentation. I get following error message:

> RuntimeException in ResolveDefinitionTemplatesPass.php line 100:
> The parent definition "fos_elastica.listener.prototype.propel" defined for definition "fos_elastica.listener.project.item" does not exist.

I'm using following versions

```
"php": "~5.6 || ~7.0",
"symfony/symfony": "~2.8",
"propel/propel-bundle": "~1.4",
"friendsofsymfony/elastica-bundle": "^3.2"
```

I'm looking for days for a solution, but with no results.
Thanks

**Comment by gkawka** [comment]
Anyone found solution to this problem?

**Comment by cvschaefer** [comment]
A quick solution for me was to set an empty listener service:

```
                    persistence:
                        driver: propel
                        listener:
                            service: ''

```

The actual problem is a faulty configuration definition in FOS\ElasticaBundle\DependencyInjection\Configuration

->arrayNode('listener')
->addDefaultsIfNotSet()

addDefaultsIfNotSet makes it impossible to omit the listeners definition for drivers without support like Propel, because it will apply the default values.
