### ISSUE TITLE
Cast id to string not working

### ISSUE THREAD

**Issue by spiroski** [FriendsOfSymfony/FOSElasticaBundle#1156]
Hello I'm trying to map a MongoDB Doctrine entity that has an object ( Wrapper of UUID) as Id.

Here's my mapping:

```
types:
                employee:
                    mappings:
                        first_name:
                            property_path: name.first
                        last_name:
                            property_path: name.last
                        middle_name:
                            property_path: name.middle
                        email: ~
                        skills:
                            type: 'nested'
                            properties:
                                id:
                                    property_path: id.toString
                                names:
                                    type: 'nested'
                                    properties:
                                        locale: ~
                                        name: ~
                    persistence:
                        driver: mongodb
                        model: TwoBit\Employees\Model\Employee
                        provider: ~
                        listener: ~
                        finder: ~
                        identifier: id
```

Here's my entity:

```
class Employee implements Person, HasSkills, WorksInDepartments, Subordinate , Superior
{
    /**
     * @var string
     */
    protected $id;

    /**
     * @return PersonID
     */
    public function getId()
    {
        return PersonID::fromString($this->id);
    }

}
```

PersonID overrides the __toString() method and returns a valid string representation of UUID.

The private property id is a string but I cast it to PersonID when using the getter. 

From searching the issues I understand that this has been fixed before, but it doesn't seem to work with "dev-master" version.
