### ISSUE TITLE
Nested Sort not Working on Paginate

### ISSUE THREAD

**Issue by plozmun** [FriendsOfSymfony/FOSElasticaBundle#1159]
I have the following mapping:

```
property:
   mappings:  
      data:
         type: nested
            properties:
               rooms: { type: integer }
               baths: { type: integer }
               size: { type: float }

```

I need to sort by size and i put the "nested_field" necessary like the elasticsearch guide says [Sorting within nested objects.](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-sort.html#nested-sorting)

When i add the sort array:
`"data.size" => array(
    "order" => "asc",
    "nested_path" => "data"
  )`

The paginator returns the query without nested_path element.
