### ISSUE TITLE
Loading wrong entity

### ISSUE THREAD

**Issue by kironet** [FriendsOfSymfony/FOSElasticaBundle#1174]
Hey,

I'm new in elasticasearch.
I have 2 websites and when I populate, one of website is calling another one's entity. 

Here is config:

```
fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        magazin:
            client: default
            types:
                post:
                    mappings:
                        title: ~
                    persistence:
                        # the driver can be orm, mongodb, phpcr or propel
                        # listener and finder are not supported by
                        # propel and should be removed
                        driver: orm
                        model: Web\AdminBundle\Entity\Post
                        provider: ~
                        listener: ~
                        finder: ~
```
```

fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        app:
            client: default
            types:
                ad:
                    mappings:
                        title: ~
                    persistence:
                        # the driver can be orm, mongodb, phpcr or propel
                        # listener and finder are not supported by
                        # propel and should be removed
                        driver: orm
                        model: Web\AdminBundle\Entity\Ad
                        provider: ~
                        listener: ~
                        finder: ~
```

Error: 

> Resetting magazin
>                                                             
>   [ReflectionException]                                            
>   Property Web\AdminBundle\Entity\Category::$title does not exist

How to use elastica for multiple websites?
Thanks

**Comment by ragusa87** [comment]
You should use 2 different indexes.
Use ```index_name: '%elasticsearch_index%'``` and configure your *elasticsearch_index* in parameters.yml
```yml

fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        app:
            index_name: '%elasticsearch_index%'
            client: default
            types:
                ad:
                    mappings:
                        title: ~
                    persistence:
                        # the driver can be orm, mongodb, phpcr or propel
                        # listener and finder are not supported by
                        # propel and should be removed
                        driver: orm
                        model: Web\AdminBundle\Entity\Ad
                        provider: ~
                        listener: ~
                        finder: ~
```
