### ISSUE TITLE
Language(UTF8)

### ISSUE THREAD

**Issue by kironet** [FriendsOfSymfony/FOSElasticaBundle#1190]
Hey,

how can I let elastica to search in czech text. 
My DB is set to UTF8 general ci.

Here is my config:
```
fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        app:
            index_name: '%elasticsearch_index%'
            client: default
            types:
                movie:
                    mappings:
                        czTitle: ~
                        enTitle: ~
                    persistence:
                        driver: orm
                        model: Web\AdminBundle\Entity\Movie
                        provider: ~
                        listener: ~
                        finder: ~
```

If I type english title, it'll find, if I type czech, it returns nothing.
