### ISSUE TITLE
Empty array as a result of search

### ISSUE THREAD

**Issue by michau85** [FriendsOfSymfony/FOSElasticaBundle#1218]
It is my first time I am trying to install FOSelastica bundle. I'm trying to rewrite an example from here (documentation). I don't know what I am doing wrong but I receive empty array. I'am using xampp localhost. Below my code

///Controller

```
 public function indexAction() {
        $finder = $this->container->get('fos_elastica.finder.app.user');
        $results = $finder->find('Ula');   
       //return new Response($results);
       var_dump($results);
    }
```

///app/config.yml

```
fos_elastica:
    clients:
        default: { host: localhost, port: 3306}
    indexes:
        app:
            types:
                user:
                    mappings:
                        username:
                             type: string
                        firstName:
                             type: string
                        lastName:
                             type: string
                        email:
                             type: string
                    persistence:
                        # the driver can be orm, mongodb, phpcr or propel
                        # listener and finder are not supported by
                        # propel and should be removed
                        driver: orm
                        model: SklepBundle\Entity\User
                        provider: ~
                        finder: ~    
                        listener: ~

```
Thanks for help in advance.
