### ISSUE TITLE
Search in multiple entities

### ISSUE THREAD

**Issue by kironet** [FriendsOfSymfony/FOSElasticaBundle#1219]
Hello,

is it possible to search in multiple entities? 

```
fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        domain:
            index_name: 'index'
            client: default
            types:
                products:
                    properties:
                        title: { type: string, analyzer: czech }
                    persistence:
                        driver: orm
                        model: Web\ShopBundle\Entity\Product
                        provider: ~
                        listener: ~
                        finder: ~
                accessories:
                    properties:
                        title: { type: string, analyzer: czech }
                    persistence:
                        driver: orm
                        model: Web\ShopBundle\Entity\Product
                        provider: ~
                        listener: ~
                        finder: ~
```

I tried this:
```
$finder = $this->get('fos_elastica.finder.domain');
$paginator = $this->get('knp_paginator');
$products = $finder->createPaginatorAdapter($keyword);
$pagination = $paginator->paginate($products, $request->query->get('page', 1), 20);
```

But didn't work.

> You have requested a non-existent service "fos_elastica.finder.domain". Did you mean one of these: "fos_elastica.finder.domain.products", "fos_elastica.finder.domain.accessories", "fos_elastica.index.domain", "fos_elastica.index_manager", "fos_elastica.indexable"
