### ISSUE TITLE
Mapper for [revisions.title] conflicts with existing mapping in other types

### ISSUE THREAD

**Issue by zajca** [FriendsOfSymfony/FOSElasticaBundle#1226]
I have two different entities which are implementing same interface thus have similar mappings.

```
...
          workUnit:
            properties:
              urlSlug: ~
              type: ~
              revisions:
                type: "nested"
                properties:
                  title: { type: text,boost: 2, analyzer: cz }
            persistence:...
...
          competence:
            properties:
              id: ~
              revisions:
                type: "nested"
                properties:
                  title: { type: text,boost: 2, analyzer: cz }
            persistence:...
...
```
this will create exception when i try to populate es.
```
  [Elastica\Exception\ResponseException]                                       
  Mapper for [revisions.title] conflicts with existing mapping in other types  
  :                                                                            
  [mapper [revisions.title] is used by multiple types. Set update_all_types t  
  o true to update [boost] across all types.] 
```

is there way to avoid this? like rename field or something? I can't design entity other way since they are follows same interface. 

```
friendsofsymfony/elastica-bundle       4.0.x-dev 8bc275b Elasticsearch PHP integration for your Symfony2 project using Elastica
ruflin/elastica                        3.2.3             Elasticsearch Client

"version": {
    "number": "5.2.2",
    "build_hash": "f9d9b74",
    "build_date": "2017-02-24T17:26:45.835Z",
    "build_snapshot": false,
    "lucene_version": "6.4.1"
}
```
