### ISSUE TITLE
Mapping config, nested document fields not saved

### ISSUE THREAD

**Issue by pierrre** [FriendsOfSymfony/FOSElasticaBundle#123]
In my mapping config, I use nested documents.

Here is my config:

```
foq_elastica:
    clients:
        default:
            host: localhost
            port: 9200
    indexes:
        foo:
            client: default
            types:
                player:
                    mappings:
                        name:
                            type: string
                            index: not_analyzed
                        balls:
                            type: nested
                            fields:
                                color:
                                    type: string
                                    index: not_analyzed
                                size:
                                    type: integer
                                location:
                                    type: geo_point
```

Here is the saved mapping:

```
curl -XGET 'http://localhost:9200/foo/player/_mapping?pretty=1' 
{
  "player" : {
    "properties" : {
      "balls" : {
        "type" : "nested"
      },
      "name" : {
        "type" : "string",
        "index" : "not_analyzed"
      }
    }
  }
}
```

Fields of the nested document are missing.
I think it's a bug.
