### ISSUE TITLE
Manual provider with FOS Elastica

### ISSUE THREAD

**Issue by ernestocuzcueta** [FriendsOfSymfony/FOSElasticaBundle#1235]
I have a problem with my manual provider. I have installed this versions:

Symfony: 2.7

FOS elastica-bundle: 3.2.2

I configured the bundle, I created the index and the types in the config.yml file. When I run the command: php app/console fos:elastica:populate Works well, but the problem is I have more of 5.000.000 of records to index. So I decided create my manual provider. When I ran the command again, my manual provider never was executed. I researched and I found the file: FOS\ElasticaBundle\Provider\ProviderRegistry has a method

```
public function addProvider($index, $type, $providerId) {

if (!isset($this->providers[$index])) {
    $this->providers[$index] = array();
}
$this->providers[$index][$type] = $providerId;
}
```

I could see that my provider is added but later is added the default provider with the same index and type and my provider is lost by the new I modified the method to see if the problem is here:

```
public function addProvider($index, $type, $providerId) {
if (!isset($this->providers[$index])) {
    $this->providers[$index] = array();
}
if (!isset($this->providers[$index][$type])) {
  $this->providers[$index][$type] = $providerId;
}
}

```
With this modification the manual provider was executed and works well. All the information was indexed using my code.

I would like know if exist a correct way to use or configure my manual provider without edit the method of the vendor

My configuration

```
fos_elastica:
    clients:
        default: { host: %elasticsearch_host%, port: %elasticsearch_port%, logger: false}
    indexes:
        app1:
            types:
                post:
                    mappings:
                        nombre: {analyzer: my_analyzer }
                        descripcion: ~
                    persistence:
                        driver: orm
                        model: MyApp\PostBundle\Entity\Post
                        provider: ~
                        finder: ~
                        listener:
                            logger: false
                            insert: false
                            update: false
                            delete: false     
```
My service:

 ```
 myApp.elastic_provider.post:
    class: MyApp\PostBundle\Buscador\PostProvider
    arguments: [@fos_elastica.index.app1.post, @doctrine.orm.entity_manager]
    tags:
      - { name: fos_elastica.provider, index: app1, type: post }  
```

Regards

**Comment by makasim** [comment]
since v4 ( maybe it works for an older version, I haven't checked it) you can do:

```yaml
fos_elastica:
    indexes:
        app1:
            types:
                post:
                    persistence:
                        provider:
                            service: myApp.elastic_provider.post
```
