### ISSUE TITLE
QueryBuilder returning an array which Elastic doesn't seem to like

### ISSUE THREAD

**Issue by dangraetzer** [FriendsOfSymfony/FOSElasticaBundle#124]
I'm using a custom QueryBuilder so that I can index foreign key values.

``` php
 public function getQueryForAllItemsForSearch()
    {

        $qb = $this->getEntityManager()->createQueryBuilder()
                    ->select(array("i.name", "i.description", "i.designer", "i.material", "i.colour", "i.care", "c.title", "s.title", "st.name"))
                    ->from("ItemBundle:Item", 'i')
                    ->innerJoin("i.category", "c")
                    ->innerJoin("i.subcategory", "s")
                    ->innerJoin("i.store", "st");
        return $qb;
    }
```

I'm unfortunately receiving this error: 

```
bigDan:elaa daniel$ php ./app/console foq:elastica:populate
Resetting indexes
Populating indexes

[ErrorException]                                                                                                                                                                         
Warning: get_class() expects parameter 1 to be object, array given in vendor/bundles/FOQ/ElasticaBundle/Transformer/ModelToElasticaAutoTransformer.php line 49  
```

When i dump the object it's referring to, it is the correct data. but it's an array, rather than the Item object it must be expecting.

Perhaps my implementation is wrong?

Here's my config:

```
item:
                    mappings:
                        name: { boost: 5 }
                        description: { boost: 3 }
                        category: { boost: 3 }
                        subcategory: { boost: 3 }
                        designer: { boost: 2 }
                        material: { boost: 2 }
                        colour: { boost: 2 }
                        care: { boost: 1 }
                    persistence:
                        driver: orm
                        model: xxx\ItemBundle\Entity\Item
                        listener:
                        provider:
                          query_builder_method: getQueryForAllItemsForSearch
                        finder:
```

Thanks for any help
