### ISSUE TITLE
Persistence data fail on join and with clause

### ISSUE THREAD

**Issue by nolonolo** [FriendsOfSymfony/FOSElasticaBundle#1244]
I have a persitence configuration in fos_elastica.yml file like next:

```
seeker:
persistence: 
            driver: orm
            identifier: couId
            model: AppBundle\Entity\Courses
            provider: 
              batch_size: 2500
              query_builder_method: getSeekerListQueryBuilder
properties: 
            couForm: 
              properties: 
                forId: 
                  type: integer
              type: object
```

getSeekerListQueryBuilder has a left join like next:
`->leftJoin('cou.couForm', 'couForm', 'WITH', 'couForm.forStatus = 1')`

I pretend has cou.couForm = null when couForm has forStatus = 0.

When I use populate comand
`php app/console fos:elastica:populate --no-reset --index=name_index --type seeker`
If forStatus is 0 elastica has:
"couForm":[],

But, when persist a seeker in DB, elastica persistence feature populate the ID in elastica when should be null, or [] :

`"couForm": {
            "forId": 18
          }`
