### ISSUE TITLE
Handling the configuration for multiple environments

### ISSUE THREAD

**Issue by gilles-g** [FriendsOfSymfony/FOSElasticaBundle#125]
Hi, 

I'd like to raise an issue with in the bundle configuration, we can not currently easily work with the test environment. 
Ie, if I want to load test data, I would like a separate index in Elasticsearch, but I'd also like to avoid having to copy all the file types in my elastica_test.yml (For example ). 

A solution would be to not generate the service ids based on the index name, but with a specified reference (as shown in the sample configuration).

I'd be glad to hear how other people solve this problem in their projects.

Configuration example: 

``` yml
# foq_elastica.yml
foq_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    connections: # or an other 
        awesome_blog: # here the reference of connection (part of the generated service id)
            index_name: awesome_blog
            client: default
    indexes:
        awesome_blog: # according to connection reference
            types:
                post:
                    mappings:
                        title: { type: string }

# foq_elastica_test.yml
foq_elastica:
    connections:
        awesome_blog:
            index_name: awesome_blog_test # as you can see, we can easily change the index name
```
