### ISSUE TITLE
Question: deletion of the child requires routing to parent, listener fails

### ISSUE THREAD

**Issue by jandom** [FriendsOfSymfony/FOSElasticaBundle#1260]
Hi guys, 

Trying to make the doctrine listener pickup a deletion of child in a parent-child association and update the index. 

In a bit of a pickle here... I'm pretty sure I'm misunderstanding something, maybe you can help. 

Here is the mapping, the association is between a ProtocolCollection entity which has a $versions attribute – that's a ArrayCollection of Protocol entities. So there is a OneToMany association between ProtocolCollection and Protocol.

```
fos_elastica:
    indexes:
        app:
            types:

                protocol_collection:
                    properties:
                        id:
                           type: integer
                    persistence:
                        driver: orm
                        model: MyApp\CoreBundle\Entity\ProtocolCollection
                        provider: ~
                        finder: ~
                        listener: ~

                protocol:
                    properties:
                        id:
                           type: integer
                    _parent:
                        type: "protocol_collection"
                        property: "collection"
                        identifier: "id"
                    persistence:
                        driver: orm
                        model: MyApp\CoreBundle\Entity\Protocol
                        provider: ~
                        finder: ~
                        listener: ~
```

This code is my crashing test-case
```
# Contents of web/app_cli.php run with php web/app_cli.php
<?php

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Debug\Debug;
use MyApp\CoreBundle\Entity\ProtocolCollection;
use MyApp\CoreBundle\Entity\Protocol;


$loader = require_once __DIR__.'/../app/bootstrap.php.cache';
Debug::enable();

require_once __DIR__.'/../app/AppKernel.php';

$kernel = new AppKernel('dev', true);
$kernel->boot();

$em = $container->get('doctrine')->getManager();

// Define data structures...
$collection = new ProtocolCollection();
$protocol = new Protocol();

// ... link them up together...
$collection->addVersion($protocol);

// ... and persist!
$em->persist($collection);
$em->flush();

// this breaks...
$collection->removeVersion($protocol);
$em->remove($protocol);
$em->flush();

```

The response I get is this
```
PHP Fatal error:  Uncaught Elastica\Exception\Bulk\ResponseException: Error in one or more bulk request actions:

delete: /app/protocol/2 caused routing is required for [app]/[protocol]/[2] [index: app]
 in /vagrant/Symfony/vendor/ruflin/elastica/lib/Elastica/Bulk.php:410
Stack trace:
#0 /vagrant/Symfony/vendor/ruflin/elastica/lib/Elastica/Bulk.php(359): Elastica\Bulk->_processResponse(Object(Elastica\Response))
#1 /vagrant/Symfony/vendor/ruflin/elastica/lib/Elastica/Client.php(615): Elastica\Bulk->send()
#2 /vagrant/Symfony/vendor/friendsofsymfony/elastica-bundle/Persister/ObjectPersister.php(169): Elastica\Client->deleteIds(Array, Object(FOS\ElasticaBundle\Elastica\Index), Object(Elastica\Type))
#3 /vagrant/Symfony/vendor/friendsofsymfony/elastica-bundle/Doctrine/Listener.php(188): FOS\ElasticaBundle\Persister\ObjectPersister->deleteManyByIdentifiers(Array)
#4 /vagrant/Symfony/vendor/friendsofsymfony/elastica-bundle/Doctrine/Listener.php(216): FOS\ElasticaBundle\Doctrine\Listener->persistScheduled()
#5 /vagrant/Symfony/vendo in /vagrant/Symfony/vendor/ruflin/elastica/lib/Elastica/Bulk.php on line 410
```

I can reproduce that response with curl
```
$ curl -XDELETE 'localhost:9200/app/protocol/2?pretty'
{
  "error" : {
    "root_cause" : [
      {
        "type" : "routing_missing_exception",
        "reason" : "routing is required for [app]/[protocol]/[2]",
        "index_uuid" : "_na_",
        "index" : "app"
      }
    ],
    "type" : "routing_missing_exception",
    "reason" : "routing is required for [app]/[protocol]/[2]",
    "index_uuid" : "_na_",
    "index" : "app"
  },
  "status" : 400
}
```

And fix it manually by providing the id of the parent ProtocolCollection
```
$ curl -XDELETE 'localhost:9200/app/protocol/2?routing=2&pretty'
{
  "found" : true,
  "_index" : "app",
  "_type" : "protocol",
  "_id" : "2",
  "_version" : 2,
  "result" : "deleted",
  "_shards" : {
    "total" : 2,
    "successful" : 1,
    "failed" : 0
  }
}
```

I'm using `        "friendsofsymfony/elastica-bundle": "dev-master"`
