### ISSUE TITLE
Call to a member function getRepository() on null (Outdated docs)

### ISSUE THREAD

**Issue by MJBGO** [FriendsOfSymfony/FOSElasticaBundle#1264]
Hi,

I've been trying for a few days now to make the bundle work for a very simple case ... a simple search in my index. I want to build in the futur a more complex query, that's why I want to use a repository.

This is my config file : 

```yaml
fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        app:
            types:
                user:
                    properties:
                        id: ~
                        name: ~
                    persistence:
                        driver: orm
                        model: AppBundle\Entity\UserSearch
                        provider: ~
                        finder: ~
                        repository: AppBundle\Repository\UserSearchRepository
```

This is my entity : 

```php
<?php

namespace AppBundle\Entity;

class UserSearch
{
    /**
     * @var int
     */
    private $id;

    /**
     * @var string
     */
    private $name;

+ __construct / getters / setters
```

My repository : 

```php
<?php

namespace AppBundle\Repository;

use FOS\ElasticaBundle\Repository;

class UserSearchRepository extends Repository
{
    public function search($query)
    {
        $this->find($query);
    }
}
```

Controller : 

```php
$repositoryManager = $this->get('fos_elastica.repository_manager');
$repository = $repositoryManager->getRepository('app/user');
$alliances = $repository->search('test');
```

I followed theses docs to build this : https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/Resources/doc/usage.md
https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/Resources/doc/cookbook/custom-repositories.md

I solved many problems caused since this PR #1119 (outdated docs): 

* fos_elastica.manager => fos_elastica.repository_manager
* UserBundle:User => app/user

But it is still not working ...

![image](https://user-images.githubusercontent.com/8344487/27810065-2d6f8606-6056-11e7-9b4d-3e76358d411e.png)

($this->objectClass value is AppBundle\Entity\UserSearch)

Do you have an idea how to solve this problem ? :(

Thanks !
