### ISSUE TITLE
You have requested a non-existent service

### ISSUE THREAD

**Issue by zebraf1** [FriendsOfSymfony/FOSElasticaBundle#128]
Hi,

I'm getting an exception:

``` php
You have requested a non-existent service "foq_elastica.finder.website.description_unit".
500 Internal Server Error - ServiceNotFoundException
```

I'm trying to get paginated results working and I almost did, but I keep getting into this exception every now and then and I haven't found what's wrong with the configuration.

config.yml

``` yml
foq_elastica:
    clients:
        default: { host: myhost, port: 9200 }
    indexes:
        website:
            client: default
            types:
                description_unit:
                    mappings:
                        title: { boost: 5 }
                        # more mappings...
                    persistence:
                        driver: propel # orm, mongodb, propel are available
                        model: \Dira\MainBundle\Model\DescriptionUnit
                        provider:
                        finder:
services:
    foq_elastica.provider:
        class: Dira\MainBundle\Search\DescriptionUnitProvider
        tags:
            - { name: foq_elastica.provider, index: website, type: description_unit }
        arguments: [null, foq_elastica.index.website.description_unit]
    foq_elastica.finder:
        class: FOQ\ElasticaBundle\Finder\TransformedFinder
        tags:
            - { name: foq_elastica.finder, index: website, type: description_unit }
        arguments: [null, foq_elastica.finder.website.description_unit]
```

In controller:

``` php
$finder = $this->get('foq_elastica.finder.website.description_unit');
```

The provider is working, but finder keeps throwing that exception. At some point it was working fine until I changed the config.yml to add more mappings. When I reverted the changes, it kept throwing the error. I tried clearing the cache, but nothing changed.

I haven't seen foq_elastica.finder declared in services, but when I added it, it was working.

I must be doing something wrong, but I cannot get the finder working to get paginated results.
