### ISSUE TITLE
Missing exception if server return 403 http code.

### ISSUE THREAD

**Issue by eugenekurasov** [FriendsOfSymfony/FOSElasticaBundle#1286]
Hi,

If server forbidden request we don't get any exception.

For reproduse issue you can make mistake in port and execute command "fos:elastica:populate' and you don't get any exception. It's look like all good.

```
fos_elastica:
    clients:
        default: { host: 'localhost', port: '9200' } # Change port to forbidden port
...
```

# Environment

## Elasticsearch packages
```
elasticsearch/elasticsearch      v5.3.0            
friendsofsymfony/elastica-bundle dev-master ebcbf84
ruflin/elastica                  5.3.0
```

## Symfony
```
symfony/symfony v3.3.9
```

## PHP
```
PHP 7.1.8 (cli) (built: Aug  4 2017 18:59:36) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.8, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.5.5, Copyright (c) 2002-2017, by Derick Rethans
```
