### ISSUE TITLE
Setting index_name causes problems with using Elastica\Search

### ISSUE THREAD

**Issue by dkarlovi** [FriendsOfSymfony/FOSElasticaBundle#1292]
If I do something like this:

```yaml
fos_elastica:
    indexes:
        app:
            index_name: "app_%kernel.environment%"
```

And later:

```php
$client = $this->get('fos_elastica.client');
$index = $client->getIndex('app');
$search = new \Elastica\Search($client);
$search->addIndex($index);

// $query generated elsewhere
$results = $search->search($query);
```

This will fail as `$index->getName()` inside `search()` will return `app`, not `app_<env>`, but from Elasticsearch's POV, `app` doesn't exist.
