### ISSUE TITLE
[Dependency Injection] A non-existent service "fos_elastica.elastica_to_model_transformer.collection.app"

### ISSUE THREAD

**Issue by aibragimov4xxi** [FriendsOfSymfony/FOSElasticaBundle#1298]
Hi.
I'am trying to inject "fos_elastica.elastica_to_model_transformer.collection.app" service into my class, but get following error:
```The service "AppBundle\Searcher\Searcher" has a dependency on a non-existent service "fos_elastica.elastica_to_model_transformer.collection.app"```

My ```services.yml```
```
AppBundle\Searcher\Searcher:
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@fos_elastica.index_manager'
            - '@fos_elastica.elastica_to_model_transformer.collection.app'
        public: true
```

My ```config.yml```
```
fos_elastica:
    clients:
        default: { host: elasticsearch, port: 9200 }
    indexes:
        app:
            types:
                user:
                    properties:
                        firstName: ~
                        lastName: ~
                        secondName: ~
                        comment: ~
                    persistence:
                        driver: orm
                        model: AppBundle\Entity\User
                        provider: ~
                        finder: ~
                project:
                    properties:
                        stage: ~
                        subjects: ~
                        title: ~
                        description: ~
                        problemDescription: ~
                        purposeDescription: ~
                    persistence:
                        driver: orm
                        model: AppBundle\Entity\Project
                        provider: ~
                        finder: ~
```

The same error when I'm trying to get "fos_elastica.elastica_to_model_transformer.collection.app" service from the controller action like in docs example:
https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/Resources/doc/cookbook/multi-type-search.md

So, how can i get transformer for collection result?

**Comment by vulfhelm** [comment]
Same problem here... :-(

**Comment by aibragimov4xxi** [comment]
I found another way to transform collection, but problem with ```fos_elastica.elastica_to_model_transformer.collection.app``` still exists.

Solution:
You need to create transformers for each entity you may have in your collection.
For example you have entity "AppBundle\Entity\Project".

Your transformer will look like this:
```
<?php

namespace AppBundle\Searcher\Transformer;

use AppBundle\Entity\Project;
use FOS\ElasticaBundle\Doctrine\AbstractElasticaToModelTransformer;
use Doctrine\ORM\Query;

class ElasticaToProjectTransformer extends AbstractElasticaToModelTransformer
{
    protected function findByIdentifiers(array $identifierValues, $hydrate)
    {
        if (empty($identifierValues)) {
            return array();
        }
        $hydrationMode = $hydrate ? Query::HYDRATE_OBJECT : Query::HYDRATE_ARRAY;
        $qb = $this->registry
            ->getManagerForClass(Project::class)
            ->getRepository(Project::class)
            ->createQueryBuilder('p')
            ->select('p');

        /* @var $qb \Doctrine\ORM\QueryBuilder */
        $qb->where($qb->expr()->in('p.'.$this->options['identifier'], ':values'))
            ->setParameter('values', $identifierValues);

        return $qb->getQuery()->setHydrationMode($hydrationMode)->execute();
    }
}
```

Next step - register your transformer as a service in services.yml:
```
app.searcher.transformer.project:
        class: 'AppBundle\Searcher\Transformer\ElasticaToProjectTransformer'
        arguments:
            - '@doctrine'
            - 'AppBundle\Entity\Project'
        calls:
            - [setPropertyAccessor, ["@fos_elastica.property_accessor"]]
        tags:
            - {name: "fos_elastica.elastica_to_model_transformer", type: "project", index: "app"}
```

Finally inject your services to your Searcher class (or get them from Controller container) and create new instance of ```FOS\ElasticaBundle\Transformer\ElasticaToModelTransformerCollection``` with array of your transformers as an argument:

Injection of transformers in Searcher class in services.yml
```
AppBundle\Searcher\Searcher:
        arguments:
            - '@app.searcher.transformer.user' #another transfomer created in a similar way as the project transformer
            - '@app.searcher.transformer.project'
        public: true
```

Creation of Collection transformer in Searcher class:
```
public function __construct(
        ElasticaToUserTransformer $userTransformer,
        ElasticaToProjectTransformer $projectTransformer
    ) {
        $transformers['user'] = $userTransformer;
        $transformers['project'] = $projectTransformer;
        $this->collectionTransformer = new CollectionTransformer($transformers);
    }
```
It is necessary that the keys of your $transformers array was the same as your types in elastica-bundle config.

Sorry for my English. I hope the explanation is quite understandable
