### ISSUE TITLE
Enable field sorting

### ISSUE THREAD

**Issue by mcanepa** [FriendsOfSymfony/FOSElasticaBundle#1309]
How can I enable sort for some fields through configuration?

I've read this documentation: [https://www.elastic.co/guide/en/elasticsearch/reference/5.2/fielddata.html](https://www.elastic.co/guide/en/elasticsearch/reference/5.2/fielddata.html)

So this is what I've tried:

**ORIGINAL WORKING YML** (only relevant parts)

```
fos_elastica:
    indexes:
        %server%:
            index_name: %server%
            types:
                contacts:
                    mappings:
                        id:
                            type: integer
                        firstName: ~
                        lastName: ~
                        created_at:
                            type : date
                        updated_at:
                            type : date
                        deleted_at:
                            type : date
                    persistence:
                        driver: orm
                        model: MyBundle\Entity\Contact
                        finder: ~
                        provider: ~
                        listener: ~
```

Added config:

```
                    properties:
                        firstName:
                            type: text
                            fields:
                                keyword:
                                    type: keyword
                        lastName:
                            type: text
                            fields:
                                keyword:
                                    type: keyword 
```

I don't know what I'm doing wrong. If I do this via kibana it works, but I need so set it up via config.

```
PUT local/_mapping/contacts
{
  "properties": {
    "firstName": {
      "type":     "text",
      "fields": {
        "keyword": {
          "type": "keyword"
        }
      }
    },
    "lastName": {
      "type":     "text",
      "fields": {
        "keyword": {
          "type": "keyword"
        }
      }
    }    
  }
} 
```
