### ISSUE TITLE
[Transformer] Allow the transformer to transform to nothing

### ISSUE THREAD

**Issue by dkarlovi** [FriendsOfSymfony/FOSElasticaBundle#1314]
Following #1312, it makes sense to allow the transformer to return `null`, by which signaling "skip this without doing anything". Note that this differs from "indexable" which will (currently) delete a document which is unindexable.

Use case: as noted in #1312, I'm implementing a multi-language support which looks like this:

```yaml
fos_elastica:
    indexes:
        app_en:
            types:
                article:
                    properties:
                        id: ~
                        title: ~
                    persistence:
                        model: ArticleBundle\Entity\Article
        app_de:
            types:
                article:
                    properties:
                        id: ~
                        title: ~
                    persistence:
                        model: ArticleBundle\Entity\Article
```

This will properly populate the indices with translated content (as I change the locale from `PRE_INDEX_POPULATE`). Trouble is, when persisting an entity in a single language, it will try to update ALL indices with that entity's current content (which is only in a single language), so my idea here is to simply skip if the index's locale doesn't match entity locale (by which, keeping the status quo, which is correct).

If I mark the entity as un-indexable for all indices beside the correct one, it will delete it from there, which is not what I want.
