### ISSUE TITLE
Using without persistence driver

### ISSUE THREAD

**Issue by macintoshplus** [FriendsOfSymfony/FOSElasticaBundle#1378]
Hi,

I use this bundle for populate index from rest API and search into after.
The populate action is only manual.

I cannot  use the v5 without persistence. 

My config :
```
fos_elastica:
    clients:
        default: { host: %es_host%, port: %es_port% }
    indexes:
        suggest_user:
            client: default
            types:
                user:
                    properties:
                        id: {type: text, boost: 5}
                        nom: {type: text, boost: 3}
                        prenom: {type: text, boost: 3}
                        mail: {type: text, boost: 3}
                    persistence:
                        driver: ~
```
I don't have Doctrine, Mongo or PHPCR... Howto custom this part?

**Comment by makasim** [comment]
I'd suggest implementing a persistence provider so that you can reuse all other parts

**Comment by macintoshplus** [comment]
Thanks for the answer. I have implemented the `FOS\ElasticaBundle\Persister\ObjectPersisterInterface` in class with only `insertMany` and work now fine.

**Comment by tmarly** [comment]
Hi Jean-Baptiste, can you give more details on how to implement a custom persister ?
I tried:
- create a class that implements ObjectPersisterInterface
- declare it in services.yaml (but may be my declaration is not correct)
- then in fos_elastica.yaml add the property persister: { service: 'my.service.name' }
But it's not working (I'm using sf4)

Thanks

**Comment by macintoshplus** [comment]
Hi,

Declare your persister in service with tags:
```yaml
services:
    App\Persister\CustomPersister:
        arguments: [null]
        tags:
            - { name: fos_elastica.persister, index: "index_name", type: "type_name" }
```
