### ISSUE TITLE
"Routing is required" when using parent

### ISSUE THREAD

**Issue by AlexandreKilian** [FriendsOfSymfony/FOSElasticaBundle#1381]
Hello,

I am trying to define a parent/child relation according to https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/types.md#parent-fields

My config for the two entities looks like following:

```
               item:
                    serializer:
                        groups: [elastica]
                    persistence:
                        driver: orm
                        model: AppBundle\Entity\Item
                        provider: ~
                        listener: ~
                        finder: ~
                reservation:
                    serializer:
                        groups: [elastica]
                    properties:
                        item_id:
                            type: integer
                            index: not_analyzed
                    _parent:
                        type: item
                        property: item_id
                    # _routing:
                    #     required: true
                    #     path: item
                    persistence:
                        driver: orm
                        model: AppBundle\Entity\Reservation
                        provider: ~
                        listener: ~
                        finder: ~

```

Unfortunately I run into an issue when populating:

``index: /app/reservation/1 caused routing is required for [app]/[reservation]/[1] [index: app]``
As you can see in the config I tried the _routing config to fix that, unfortunately that gets sent in the mapping and causes an error there:

``Mapping definition for [_routing] has unsupported parameters:  [path : item_id]``

I don't see what's wrong here, the docs state that you should "setParent" on a document, but I don't have a document to setParent on as I'm automatically populating from ORM. So it seems to me that either the docs don't state everything concerning this topic or that there is an issue here...

My scenario here is, that I'm trying to find "Items" that don't have "reservations" on a specific date.
