### ISSUE TITLE
unknown setting [index.analyzer.my_analyzer.filter]

### ISSUE THREAD

**Issue by mvigneron** [FriendsOfSymfony/FOSElasticaBundle#1383]
Hello,

I'm testing bundle FosElasticaBundle, I would like to set a custom analyser and filter but I have an issue "unknown setting [index.analyzer.my_analyzer.filter]" in console output.

My config 

```
fos_elastica:
  clients:
    default: { host: %elastic_search_host%, port: %elastic_search_port% }
  indexes:
    search:
      #index_name: api_%kernel.environment%
      settings:
        index:
          analyzer:
            my_analyzer:
              type: custom
              tokenizer: lowercase
              filter : [my_ngram]
          filter:
            my_ngram:
              type: "nGram"
              min_gram: 3
              max_gram: 5

      types:
        shop:
          properties:
            name: {type: text,boost: 6, analyser: my_analyzer }
          persistence:
            driver: orm
            model: AppBundle\Entity\Shop
            provider: ~
            finder: ~
            listener:
              defer: true
```

Command: 
`php bin/console fos:elastica:create`
Response 
```
 [Elastica\Exception\ResponseException]
  unknown setting [index.analyzer.my_analyzer.filter] please check that any required plugins are installed, or check the breaking changes documentation
   for removed settings
```

My config of custom analyser is exactly the same than the documentation => https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/v5.0.2/doc/types.md#custom-settings

Version FosElasticaBundle : 5.0.2

What's wrong with my config ?

Thanks

**Comment by mvigneron** [comment]
Sorry for my post... I had many typo in my config...

analyser => analyzer
Missed "analysis"

Config updated =>

```
fos_elastica:
  clients:
    default: { host: %elastic_search_host%, port: %elastic_search_port% }
  indexes:
    search:
      index_name: api_%kernel.environment%
      settings:
        index:
          analysis:
            analyzer:
              my_analyzer:
                type: custom
                tokenizer: lowercase
                filter : [my_ngram]
            filter:
              my_ngram:
                type: nGram
                min_gram: 3
                max_gram: 5
      types:
        shop:
          properties:
            name:
              type: text
              boost: 6
              analyzer: my_analyzer
          persistence:
            driver: orm
            model: AppBundle\Entity\Shop
            provider: ~
            finder: ~
            listener:
              defer: true
```
