### ISSUE TITLE
Multi type search to multi index search

### ISSUE THREAD

**Issue by Kleinast** [FriendsOfSymfony/FOSElasticaBundle#1385]
Hello there,

The new elasticsearch don't allow to have more than one type by index.
So this doc is Obsolete, isn't it ?
https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/cookbook/multi-type-search.md
I'am looking for do similar thing, but now with multi index search. How should I do ?

Thanks

**Comment by IckleChris** [comment]
Very new to ES and this bundle, but I've got as far as being able to perform a search across multiple indices;

```
indexes:
    thread:
        finder: ~
        types:
            thread:
                properties:
                    title: ~
                    body: ~
                persistence:
                    driver: orm
                    model: App\Entity\Thread
                    provider: ~
                    finder: ~
    reply:
        finder: ~
        types:
            reply:
                properties:
                    body: ~
                persistence:
                    driver: orm
                    model: App\Entity\Reply
                    provider: ~
                    finder: ~
```

```
$search = $mngr->getIndex('thread')->createSearch($searchTerm);
$search->addIndex('reply');
$results = $search->search()->getResults();
```

`$results` contains matched items from both indexes. What I can't figure out is the transformation from that point. 

```
$transformer = $this->get('fos_elastica.elastica_to_model_transformer.collection.thread');
$results = $transformer->transform($results);
```

In this case `$transformer` is an instance of `ElasticaToModelTransformerCollection` that (obviously) only contains the thread transformer, and therefore fails when it attempts to transform a reply. There may be an easy way to end up with a collection containing multiple transformers but I can't seem to find it.

**Comment by Kleinast** [comment]
Your solution work fine. Thank you very much

**Comment by insekticid** [comment]
@IckleChris:

define service
```yaml
    FOS\ElasticaBundle\Transformer\ElasticaToModelTransformerCollection:
        arguments:
            - {
                recipe: '@fos_elastica.elastica_to_model_transformer.recipe.recipe',
                recipes: '@fos_elastica.elastica_to_model_transformer.recipes.recipes'
              }
 ```

define custom class and inject this collection into $this->elasticaToModelTransformerCollection;
 ```php
            $index      = $this->indexManager->getIndex('recipe');
            $index2     = $this->indexManager->getIndex('recipes');

            $searchable = new MultiIndex($index->getClient(), $index->getName());
            $searchable->addIndex($index2);

            $transformer = $this->elasticaToModelTransformerCollection;
            $paginatorAdapter = new TransformedPaginatorAdapter($searchable, $query, [], $transformer);
            $items = new Pagerfanta(new FantaPaginatorAdapter($paginatorAdapter));
            $items->setMaxPerPage($limit);
            $items->setCurrentPage($page);
 ```

where MultiIndex looks like 
```php
<?php

declare(strict_types=1);

/*
 * Created by Exploit.cz <insekticid@exploit.cz>
 */

namespace App\Search\Elastica;

use Elastica\Exception\InvalidException;
use Elastica\Index;
use Elastica\ResultSet\BuilderInterface;
use Elastica\Search;

class MultiIndex extends Index
{
    /**
     * Array of indices.
     *
     * @var array
     */
    protected $_indices = [];

    /**
     * Adds a index to the list.
     *
     * @param \Elastica\Index|string $index Index object or string
     *
     * @throws \Elastica\Exception\InvalidException
     *
     * @return $this
     */
    public function addIndex($index)
    {
        if ($index instanceof Index) {
            $index = $index->getName();
        }

        if (!is_scalar($index)) {
            throw new InvalidException('Invalid param type');
        }

        $this->_indices[] = (string) $index;

        return $this;
    }

    /**
     * Add array of indices at once.
     *
     * @param array $indices
     *
     * @return $this
     */
    public function addIndices(array $indices = [])
    {
        foreach ($indices as $index) {
            $this->addIndex($index);
        }

        return $this;
    }

    /**
     * Return array of indices.
     *
     * @return array List of index names
     */
    public function getIndices()
    {
        return $this->_indices;
    }

    /**
     * @param string|array|\Elastica\Query $query
     * @param int|array                    $options
     * @param BuilderInterface             $builder
     *
     * @return Search
     */
    public function createSearch($query = '', $options = null, BuilderInterface $builder = null)
    {
        $search = new Search($this->getClient(), $builder);
        $search->addIndex($this);
        $search->addIndices($this->getIndices());
        $search->setOptionsAndQuery($options, $query);

        return $search;
    }
}

```

**Comment by michaelKaefer** [comment]
The  docs are still wrong for elasticsearch 6.0 and all following versions. Since this issue was closed: there is another open issue on this: https://github.com/FriendsOfSymfony/FOSElasticaBundle/issues/1521

**Comment by skylord123** [comment]
Yeah I just ran into this and there are no great alternatives.

It would be nice if this bundle got updated to handle multiple indexes in a better way.

I am building a global site search atm and indexes are only added if the user has permissions. Getting that to work along with pagination is pretty god awful right now.

**Comment by PaulAboulinc** [comment]
> Very new to ES and this bundle, but I've got as far as being able to perform a search across multiple indices;
> 
> ```
> indexes:
>     thread:
>         finder: ~
>         types:
>             thread:
>                 properties:
>                     title: ~
>                     body: ~
>                 persistence:
>                     driver: orm
>                     model: App\Entity\Thread
>                     provider: ~
>                     finder: ~
>     reply:
>         finder: ~
>         types:
>             reply:
>                 properties:
>                     body: ~
>                 persistence:
>                     driver: orm
>                     model: App\Entity\Reply
>                     provider: ~
>                     finder: ~
> ```
> 
> ```
> $mngr = $this->get('fos_elastica.index_manager');
> 
> $search = $mngr->getIndex('thread')->createSearch($searchTerm);
> $search->addIndex('reply');
> $results = $search->search()->getResults();
> ```
> 
> `$results` contains matched items from both indexes. What I can't figure out is the transformation from that point.
> 
> ```
> $transformer = $this->get('fos_elastica.elastica_to_model_transformer.collection.thread');
> $results = $transformer->transform($results);
> ```
> 
> In this case `$transformer` is an instance of `ElasticaToModelTransformerCollection` that (obviously) only contains the thread transformer, and therefore fails when it attempts to transform a reply. There may be an easy way to end up with a collection containing multiple transformers but I can't seem to find it.

I used this response but I had problem with searching on other index than the one I used to get de transformer (thread in this example).

To avoid that, I override the class "ElasticaToModelTransformerCollection" like this :

```
<?php

namespace Unadere\Bundle\Utils\ElasticaBundle;

/**
 * Class ElasticaToModelTransformerCollection
 * @package Unadere\Bundle\Utils\ElasticaBundle
 */
class ElasticaToModelTransformerCollection extends \FOS\ElasticaBundle\Transformer\ElasticaToModelTransformerCollection
{
    /**
     * @return array|\FOS\ElasticaBundle\Transformer\ElasticaToModelTransformerInterface[]
     */
    public function getTransformers()
    {
        return $this->transformers;
    }

    /**
     * @param ElasticaToModelTransformerCollection $modelTransformer
     */
    public function addTransformers($modelTransformer)
    {
        $transformers = $modelTransformer->getTransformers();
        foreach ($transformers as $key => $transformer) {
            $this->transformers[$key] = $transformer;
        }
    }
}
```

In the OverrideServiceCompilerPass.php : 

```
$definition = $container->findDefinition('fos_elastica.elastica_to_model_transformer.collection');
$definition->setClass(ElasticaToModelTransformerCollection::class);
```

Then in my service using the transformer, I create a new transformer : 

Service arguments :
```
arguments:
   $searchTransformers:
         thread: '@fos_elastica.elastica_to_model_transformer.collection.thread'
         reply: '@fos_elastica.elastica_to_model_transformer.collection.reply'
```

And in my service : 
```
public function __construct($searchTransformers)
    {
        $modelTransformer = new ElasticaBundle\ElasticaToModelTransformerCollection([]);
        /** @var \Unadere\Bundle\Utils\ElasticaBundle\ElasticaToModelTransformerCollection $transformer */
        foreach ($searchTransformers as $transformers) {
            $modelTransformer->addTransformers($transformers);
        }

        $this->modelTransformer = $modelTransformer;
    }
```

It's seems to work fine for me but I'm not against a better solution. :)
