### ISSUE TITLE
Exception: Class name must be a valid object or a string 

### ISSUE THREAD

**Issue by spointecker** [FriendsOfSymfony/FOSElasticaBundle#1389]
Hi!

Since I upgraded from v4 to v5 I am getting the following exception on saving (`$entity->flush()`) entities via doctrine.

Here is the call stack:
```
 () at /var/www/vendor/friendsofsymfony/elastica-bundle/src/Persister/ObjectPersister.php:53
 FOS\ElasticaBundle\Persister\ObjectPersister->handlesObject() at /var/www/vendor/friendsofsymfony/elastica-bundle/src/Doctrine/Listener.php:136
 FOS\ElasticaBundle\Doctrine\Listener->postUpdate() at /var/www/vendor/symfony/symfony/src/Symfony/Bridge/Doctrine/ContainerAwareEventManager.php:61
 Symfony\Bridge\Doctrine\ContainerAwareEventManager->dispatchEvent() at /var/www/vendor/doctrine/orm/lib/Doctrine/ORM/Event/ListenersInvoker.php:117
 Doctrine\ORM\Event\ListenersInvoker->invoke() at /var/www/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:1109
 Doctrine\ORM\UnitOfWork->executeUpdates() at /var/www/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:392
 Doctrine\ORM\UnitOfWork->commit() at /var/www/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php:358
 Doctrine\ORM\EntityManager->flush() at  ....
```
I already cleared all caches and run composer dumpautoload to be sure to use the latest files.

Any ideas?

**Comment by spointecker** [comment]
I found the problem myself.

I have a `type` in my elasticsearch config, which is not connected to an ORM mapper and should not so cannot be updated automatically.
But unfortunately the listeners for delete/update/insert were active, so the object persister tried to compare "null" with the class name -> failed.

Adding this to my config solved the problem:

```
fos_elastica:
   index:
      app:
          types:
              mycustomtype:
                 .....
                 persistence:
                     listener:
                          insert: false
                          update: false
                          delete: false
```
