### ISSUE TITLE
Excluding "object" data from search

### ISSUE THREAD

**Issue by BentCoder** [FriendsOfSymfony/FOSElasticaBundle#1403]
Hi,

There isn't any option to exclude embedded objects in search. Is there a way to do this? The `cities` should be excluded.

Thanks

Searching a document with `id = 1`.

        $terms = new Terms();
        $terms->setTerms('id', [1]);

        $index = $this->indexManager->getIndex('country');
        $result = $index->search($terms);
        $document = $result->getDocuments()[0];

        print_r($document->getData());

**Current Result**

```
Array
(
    [id] => 1
    [name] => United Kingdom
    [cities] => Array
        (
            [0] => Array
                (
                    [id] => 1
                    [name] => London
                )
            [1] => Array
                (
                    [id] => 2
                    [name] => Bath
                )
        )
)
```

**DESIRED RESULT**

```
Array
(
    [id] => 1
    [name] => United Kingdom
)
```

**config.yml**

```
fos_elastica:
    indexes:
        country:
            client: default
            index_name: country
            types:
                country:
                    properties:
                        id:
                            type: integer
                        name:
                            type: text
                        cities:
                            type: object
                            properties:
                                id:
                                    type: integer
                                name:
                                    type: text
```

**Mapping**
```
{
  "country_2018-02-21-101025": {
    "mappings": {
      "country": {
        "_meta": {
          "model": "MyBundle\\Entity\\Country"
        },
        "properties": {
          "id": {
            "type": "integer"
          },
          "cities": {
            "properties": {
              "id": {
                "type": "integer"
              },
              "name": {
                "type": "text"
              }
            }
          },
          "name": {
            "type": "text"
          }
        }
      }
    }
  }
}
```
