### ISSUE TITLE
AWS ElasticSearch connect "Couldn't resolve host"

### ISSUE THREAD

**Issue by coreygans** [FriendsOfSymfony/FOSElasticaBundle#1407]
I saw this issue: #1126 but it isn't working for me. 

## Background
I've setup the elasticsearch instance to only allow access to my IP address so it doesn't require auth
This curl command works and gets a response: 
` curl -XGET 'https://xxxxxxxxxxxxx.us-east-1.es.amazonaws.com:443'
`
Also I'm able to create an index:
```
curl -XPUT 'https://xxxxxxxxxxxxxxxx.us-east-1.es.amazonaws.com:443/customer?pretty'
{
  "acknowledged" : true,
  "shards_acknowledged" : true,
  "index" : "customer"
}


```
When I run 
`php bin/console fos:elastica:populate
`
It throws the error:

```
In Http.php line 189:
  [Elastica\Exception\Connection\HttpException]  
  Couldn't resolve host        
```                  

Here is my config:
```
fos_elastica:
    clients:
        default:
            host: https://xxxxxxxxxxx.us-east-1.es.amazonaws.com
            port: 443

```

I was able to populate with a local docker instance, so I know the setup works, but just stuck on this. Appreciate any help.
