### ISSUE TITLE
Populating elasticsearch index with a custom provider service without having a database

### ISSUE THREAD

**Issue by ivan-jovanovic** [FriendsOfSymfony/FOSElasticaBundle#1410]
I recently updated the FOS Elastica bundle and now I'm having trouble with the PagerProviderInterface, because the ProviderInterface class was deleted. I'm using Symfony 3.3, FOS Elastica 5.0.3, Elastica 6.0 and ElasticSearch 5.6.8. Before the update I used this script (http://www.inanzzz.com/index.php/post/zijc/populating-elasticsearch-index-with-a-custom-provider-service-without-having-a-database) to create and populate a custom index in ElasticSearch that was not connected to a model in my doctrine configuration. I was using this for the past year, and it became an integral part in my website. But since version 5.0 FOS Elastica removed the ProviderInterface class and reworked the whole provider logic, making my code obsolete.

I'm now struggling to do the right changes in my script to implement the new PagerProviderInterface, and I'm doubting if it's even possible to create a custom index with the new provider changes.

Can someone help me with pointers, how can I populate an elasticsearch index that's not in the database with the new PagerProviderInterface?

**Comment by reflexxion** [comment]
Hi @ivan-jovanovic,

did you manage to solve this issue?

**Comment by ivan-jovanovic** [comment]
Hello,
No, I did not. I stopped using custom indexes in ES.

**Comment by sirbugabriel89** [comment]
As the ProviderInterface is not longer used there is a workaround.

Set up an event listener or subscriber for `FOS\ElasticaBundle\Event\TransformEvent::POST_TRANSFORM` to be able to inject your own parameters.

```
namespace AcmeBundle\EventListener;

use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use FOS\ElasticaBundle\Event\TransformEvent;

class CustomElasticaListener implements EventSubscriberInterface
{
    public function addCustomProperty(TransformEvent $event)
    {
        $document = $event->getDocument();
        $custom = 'custom value';
        // if you want to access the object you have to call $event->getObject();
       // in my case i had to inject a service in this listener then call $this->otherService->countNewMessagesInConversation(); then i populated the field.
                    
        $document->set('custom', $custom);
    }
    
    public static function getSubscribedEvents()
    {
        return array(
            TransformEvent::POST_TRANSFORM => 'addCustomProperty',
        );
    }
}
```

I got those info from https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/cookbook/custom-properties.md

**Comment by ivansrdic** [comment]
1. Create the pager provider service
```php
<?php
namespace Acme\UserBundle\Provider;

use FOS\ElasticaBundle\Provider\PagerProviderInterface;
use FOS\ElasticaBundle\Provider\PagerfantaPager;
use Pagerfanta\Pagerfanta;
use Pagerfanta\Adapter\ArrayAdapter;

class UserPagerProvider implements PagerProviderInterface
{
    public function provide(array $options = array())
    {
        new PagerfantaPager(new Pagerfanta(new ArrayAdapter([ /* an array of objects */ ])));
    }
}
```

2. Register the pager provider service in `services.yaml`
```yaml
# app/config/services.yaml
services:
    acme.search_provider.user:
        class: Acme\UserBundle\Provider\UserPagerProvider
        tags:
            - { name: fos_elastica.pager_provider, index: app, type: user }
```

3. Configure an index in `fos_elastica.yaml`
```yaml
# app/config/packages/fos_elastica.yaml
fos_elastica:
    indexes:
        app:
            types:
                user:
                    persistence:
                        provider:
                            service:  acme.search_provider.user
```

**Comment by MaximeTaqt** [comment]
```
3. Configure an index in fos_elastica.yaml
# app/config/packages/fos_elastica.yaml
fos_elastica:
    indexes:
        app:
            types:
                user:
                    persistence:
                        provider:
                            service:  acme.search_provider.user
```

This part is missing from documentation https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/provider.md
