### ISSUE TITLE
Doctrine listener doesn't consider custom query_builder_method

### ISSUE THREAD

**Issue by RobMasters** [FriendsOfSymfony/FOSElasticaBundle#143]
As the title suggests, I'm using the doctrine listener to automatically update the index, but my custom `query_builder_method` isn't being taken into consideration. The query builder method only returns stories that are set as active and have a published date that is in the past, but after creating a new Story entity that is inactive and due to be published sometime in the future it appears in the search results.

Here is the relevant section of my configuration, within my "story" type:

```
persistence:
    driver: orm # orm, mongodb, propel are available
    model: Acme\Bundle\StoryBundle\Entity\Story
    provider:
        query_builder_method: createIsActiveQueryBuilder
    listener:
    finder:
```

I'm able to temporarily 'fix' the problem temporarily by executing the `foq:elastica:populate` command. This will produce a correct search index containing only active, published stories, but only until a new story is created.
