### ISSUE TITLE
Get error when populate

### ISSUE THREAD

**Issue by parezban** [FriendsOfSymfony/FOSElasticaBundle#1434]
I try to use **elasticsearch** with my **symfony 4**

here is my **yaml** file :

```
fos_elastica:
clients:
    default: { host: localhost, port: 9200 }
serializer:
    serializer: jms_serializer
indexes:
    app:
        index_name: app_%kernel.environment%
        types:
            user:
                properties:
                    username: ~
                    email: ~
                persistence:
                    driver: orm
                    model: App\Entity\User
                    provider: ~
                    finder: ~
```

when i try to populate data using :

`php bin/console fos:elastica:populate`

i get this error :

Malformed action/metadata line [3], expected START_OBJECT but found [VALUE_
STRING]
