### ISSUE TITLE
Reusable property definitions for index (and maybe whole config)

### ISSUE THREAD

**Issue by Destroy666x** [FriendsOfSymfony/FOSElasticaBundle#1435]
Hello,

this is an example of a property definition I'm using in several places:
```
                            type: 'string'
                            analyzer: 'arabic'
                            store: false
                            fields:
                                ngram:
                                    type: 'string'
                                    analyzer: 'index_arabic_ngram_analyzer'
                                    search_analyzer: 'search_arabic_ngram_analyzer'
                                    store: false
                                raw:
                                    type: 'string'
                                    index: 'not_analyzed'
```
I'm wondering if it's possible to shorten it to something like `property_definition: 'arabicString'` which then would be replaced by all those settings. Didn't find anything in documentation - the closest thing are dynamic templates, but they don't work on the index level, right? If it's not possible in Elastic itself it would be nice to have it as an addition
