### ISSUE TITLE
Cannot populate when using pretty json option

### ISSUE THREAD

**Issue by Jerome1337** [FriendsOfSymfony/FOSElasticaBundle#1438]
I'm using FOSElastica with jms serializer to get datas and populate it to elasticsearch.

When I'm using `JSON_PRETTY_PRINT` option inside jms serializer, I get a malformed data error.

```
  [Elastica\Exception\ResponseException]                                              
  Malformed action/metadata line [3], expected START_OBJECT but found [VALUE_STRING] 
```

My FOSElastica is pretty simple and I'm using FOSElastica `5.0.3` and Symfony `3.4`

```
fos_elastica:
    clients:
        default: { host: '%env(ELASTICSEARCH_HOST)%', port: '%env(ELASTICSEARCH_PORT)%' }
    serializer:
        serializer: jms_serializer
    indexes:
        app:
            index_name: app
            types:
                user:
                    serializer:
                        groups: [elastica]
                    persistence:
                        driver: orm
                        model: AppBundle\Entity\user
                        provider: ~
                        listener: ~
                        finder: ~
```

When I'm removing pretty json output the population command work well. But I need this options elsewhere.

**Comment by bassrock** [comment]
Seeing this issue as well. As soon as I removed pretty print from jms_serializer it started working. Something to note to is that pretty print is a default option in Symfony 4 receipe-contrib

**Comment by ahmed-bhs** [comment]
@bassrock @Jerome1337  Gyus did you find any solution. I'm working with symfony 4 ..and I'm facing the same problem, every time i add the 

```
fos_elastica:
   ...
    serializer:
        serializer: jms_serializer
```
