### ISSUE TITLE
JmsSerializer:  Malformed action/metadata line [3], expected START_OBJECT but found [VALUE_STRING]

### ISSUE THREAD

**Issue by CocoJr** [FriendsOfSymfony/FOSElasticaBundle#1439]
Hi !

I have always the error when using JMSSerializer.
This is my configuration:

``` 
fos_elastica:
    clients:
        default: { host: elasticsearch, port: 9200 }
    serializer:
        serializer: jms_serializer.serializer
    indexes:
        app:
            index_name: app_%kernel.environment%
            types:
                user:
                    serializer:
                          groups: [elastica]
                          serialize_null: true
                    persistence:
                          driver: orm
                          model: App\Entity\User

jms_serializer:
    visitors:
        json:
            options: 0
        xml:
            format_output: false
    handlers:
        datetime:
            default_format: "yyyy-mm-dd H:i:s"
```

If i don't use JmsSerializer but i use "properties" inside fos_elastica, all works.
