### ISSUE TITLE
ElasticaBundle dont update the indexes automatically

### ISSUE THREAD

**Issue by devozanges** [FriendsOfSymfony/FOSElasticaBundle#1447]
When I edit my entity, the index does not change. but it changes well when I populate

    // ...
    persistence:    
         driver: orm    
         model: AppBundle\Entity\MyEntity
         provider: ~    
         finder: ~     
         listener: ~

Does anyone have any idea what the problem is? #

**Comment by nalhabash** [comment]
That problem is still there for me. I'm using a custom EventSubscriber to reset the Index on the PRE_INDEX_POPULATE event to get around this.

**Comment by manu-sparheld** [comment]
`listener: { enabled: true }`
can you try this?

**Comment by euperia** [comment]
I've tried adding  `enabled: true` and it doesn't work for me.

```
persistence:
    driver: orm
    model: App\Entity\Product\Product
    provider: ~
    listener:
        enabled: true
        insert: true
        update: true
        delete: true
```
