### ISSUE TITLE
suggestion does not support [field]

### ISSUE THREAD

**Issue by ahmed-bhs** [FriendsOfSymfony/FOSElasticaBundle#1459]
Using  `fos_elastica.finder.post_index.post` service to get list of <a href="https://www.elastic.co/guide/en/elasticsearch/reference/5.2/search-suggesters-completion.html#fuzzy" >sugesstion available</a> from my mapping:

```

fos_elastica:
    clients:
        default: { host: elasticsearch, port: 9200 }
    indexes:
        post_index:
            client: default
            index_name: post_index
            types:
                post:
                    properties:
                        suggest:
                            type: completion
                        id:
                            type: keyword
                        title:
                            type: keyword
                        description:
                            type: keyword

                    persistence:
                        driver: orm
                        model: App\Entity\Post
                        finder: ~
                        provider: ~
                        listener: ~
 ```
This is my php code under SearchController:

```

        $finder = $this->container->get('fos_elastica.finder.post_index.post');

        $compelation = [
                "suggest" => [
                    "suggest" => [
                        "text" => "test",
                        "completion" => [
                            "field" => "suggest",
                            "fuzzy" => ["fuzziness" => 2]
                        ],
                    ]
                ]
            ];

        $result = $finder->find($compelation);
```
The post request work great under kibana console and return the appropriate result:
```

POST post_index/_search?pretty
{
    "suggest": {
        "anything-suggest" : {
            "text" : "test",
            "completion" : {
                "field" : "suggest",
                "fuzzy" : {
                    "fuzziness" : 2
                }
            }
        }
    }
}

```

This is the error I'm getting:

```
suggestion does not support [field]
```
