### ISSUE TITLE
Error when trying to do the 1st populate : rejecting mapping update

### ISSUE THREAD

**Issue by eved42** [FriendsOfSymfony/FOSElasticaBundle#1462]
- Symfony version : 4.1
- Elastica bundle version : 5.0
- Work locally on Windows 10 Entreprise + Wampserver 3.0.0

I have 2 entities that I want to index with Elastica : `Customer` and `Prescriber`

I installed Elastica on my computer, it seems to work when I go on http://localhost:9200/.
After configuring my `fos_elastica.yaml` file, I tried to populate for the first time with this command : 
`$ php bin/console fos:elastica:populate`

I've got this error : 
```
In Http.php line 181:
Rejecting mapping update to [app] as the final mapping would have more than 1 type: [prescriber, customer]
```
I think I badly configured Elastica...

```
fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        app:
          types:
            customer:
              indexable_callback: 'isIndexable'
              properties:
                code: ~
                name: ~
                postalCode: ~
                city: ~
                cip: ~
              persistence:
                driver: orm
                model: App\Entity\Customer

            prescriber:
              indexable_callback: 'isIndexable'
              properties:
                rpps: ~
                lastname: ~
                firstname: ~
                postalCode: ~
                city: ~
              persistence:
                driver: orm
                model: App\Entity\Prescriber
                provider:
                  batch_size: 1000
```
Is it a good way for indexing 2 different entities ? I don't want to index neither every property of them nor all the rows of my tables.

After filtering only indexable rows, I have around 150 customers and more than 390k prescribers.

**Comment by samimussbach** [comment]
Elasticsearch rejects to use multiple types in one index since ES 6. See https://www.elastic.co/blog/index-type-parent-child-join-now-future-in-elasticsearch for details.

You should map customer and prescriber as two indexes instead ot 2 types of the same "app" index

**Comment by eved42** [comment]
Ok thank you, it seems to work with this new config : 

```
fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        customers:
          types:
            customer:
              indexable_callback: 'isIndexable'
              properties:
                code: ~
                name: ~
                postalCode: ~
                city: ~
                cip: ~
              persistence:
                driver: orm
                model: App\Entity\Customer
                identifier: code

        prescribers:
          types:
            prescriber:
              indexable_callback: 'isIndexable'
              properties:
                rpps: ~
                lastname: ~
                firstname: ~
                postalCode: ~
                city: ~
              persistence:
                driver: orm
                model: App\Entity\Prescriber
                provider:
                  batch_size: 1000
```
