### ISSUE TITLE
LogicException: Not Implemented when speeding up command following doc

### ISSUE THREAD

**Issue by PBXg33k** [FriendsOfSymfony/FOSElasticaBundle#1463]
I've tried setting up workers in order to speed up populating elasticsearch since running it without workers results in a memory exhaustion. I tried following the documentation on setting up using the `EnqueueBundle` but didn't manage setting it up as it fails to run the commands.

Any assistant is appreciated.

Command output:
```
/var/www/html # bin/console fos:elastica:populate --pager-persister=queue -vvv
Resetting app
[2018-10-18 20:55:05] elastica.DEBUG: Elastica Request {"request":{"path":"app_dev","method":"DELETE","data":[],"query":[],"contentType":"application/json","connection":{"config":{"headers":[],"curl":[]},"host":"elastica","port":80,"ssl":false,"logger":"fos_elastica.logger","compression":false,"retryOnConflict":0,"enabled":true}},"response":{"acknowledged":true},"responseStatus":200} []
[2018-10-18 20:55:05] elastica.INFO: app_dev (DELETE) 5149.49 ms [] []
...
[2018-10-18 20:55:06] console.ERROR: Error thrown while running command "fos:elastica:populate --pager-persister=queue -vvv". Message: "Not implemented" {"exception":"[object] (LogicException(code: 0): Not implemented at /var/www/html/vendor/enqueue/redis/RedisContext.php:98)","command":"fos:elastica:populate --pager-persister=queue -vvv","message":"Not implemented"} []
...
[2018-10-18 20:55:06] console.DEBUG: Command "fos:elastica:populate --pager-persister=queue -vvv" exited with code "1" {"command":"fos:elastica:populate --pager-persister=queue -vvv","code":1} []

In RedisContext.php line 98:
                    
  [LogicException]  
  Not implemented   
                    
Exception trace:
 Enqueue\Redis\RedisContext->createTemporaryQueue() at /var/www/html/vendor/enqueue/elastica-bundle/Persister/QueuePagerPersister.php:71
 Enqueue\ElasticaBundle\Persister\QueuePagerPersister->insert() at /var/www/html/vendor/friendsofsymfony/elastica-bundle/src/Command/PopulateCommand.php:259
 FOS\ElasticaBundle\Command\PopulateCommand->populateIndexType() at /var/www/html/vendor/friendsofsymfony/elastica-bundle/src/Command/PopulateCommand.php:189
 FOS\ElasticaBundle\Command\PopulateCommand->populateIndex() at /var/www/html/vendor/friendsofsymfony/elastica-bundle/src/Command/PopulateCommand.php:164
 FOS\ElasticaBundle\Command\PopulateCommand->execute() at /var/www/html/vendor/symfony/console/Command/Command.php:251
 Symfony\Component\Console\Command\Command->run() at /var/www/html/vendor/symfony/console/Application.php:904
 Symfony\Component\Console\Application->doRunCommand() at /var/www/html/vendor/symfony/framework-bundle/Console/Application.php:89
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /var/www/html/vendor/symfony/console/Application.php:262
 Symfony\Component\Console\Application->doRun() at /var/www/html/vendor/symfony/framework-bundle/Console/Application.php:75
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /var/www/html/vendor/symfony/console/Application.php:145
 Symfony\Component\Console\Application->run() at /var/www/html/bin/console:39

fos:elastica:populate [--index [INDEX]] [--type [TYPE]] [--no-reset] [--no-delete] [--sleep SLEEP] [--ignore-errors] [--no-overwrite-format] [--first-page FIRST-PAGE] [--last-page LAST-PAGE] [--max-per-page MAX-PER-PAGE] [--pager-persister PAGER-PERSISTER] [-h|
--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>
```

Configs:
```
/var/www/html # bin/console debug:config enqueue

Current configuration for extension with alias "enqueue"
========================================================

enqueue:
    transport:
        default:
            alias: '%env(ENQUEUE_DSN)%'
    client:
        traceable_producer: true
        prefix: enqueue
        app_name: app
        router_topic: default
        router_queue: default
        router_processor: Enqueue\Client\RouterProcessor
        default_processor_queue: default
        redelivered_delay_time: 0
    async_events:
        enabled: true
    consumption:
        idle_timeout: 0
        receive_timeout: 100
    job: false
    extensions:
        doctrine_ping_connection_extension: false
        doctrine_clear_identity_map_extension: false
        signal_extension: false
        reply_extension: true


/var/www/html # env | grep ENQUEUE_DSN
ENQUEUE_DSN=redis://redis:6379/1?vendor=phpredis
```

Redis server content
```
/var/www/html # redis-cli -h redis -n 1
redis:6379[1]> keys *
(empty list or set)
```
