### ISSUE TITLE
configuration to external server (searchly.com, via heroku)

### ISSUE THREAD

**Issue by tacman** [FriendsOfSymfony/FOSElasticaBundle#1476]
I've added searchly as an AddOn heroku service.  This gives an environment variable in the form of a URL:

SEARCHBOX_URL:     http://username@password@thorin-us-east-1.searchly.com

My fos_elastic.yaml is set up as

```yaml
fos_elastica:
  clients:
    default: { url: '%env(SEARCHBOX_URL)%' }
```

And works fine if the SEARCHBOX_URL is set up to my local envirnment (localhost:9200), but fails when it's deployed.  I''m wondering if in addition to the username and password if I need to send an API key in the headers, and if so, how does one do that?

I see #491, but not sure how to configure the API key, if indeed that's the problem.  I'm assuming the 'URL' is the right parameter to set, but not 100% sure.  Perhaps someone who knows could update the documentation to mention that.

**Comment by ferhatsb** [comment]
To set basic auth taken from [docs](https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/cookbook/http-auth-for-elastica.md)

```
fos_elastica:
  clients:
    default:
      host: thorin-us-east-1.searchly.com
      port: 443
      username: 'username'
      password: 'api-key'
```
You may need to parse those values over SEARCHBOX_URL
