### ISSUE TITLE
CURLOPT_SSL_VERIFYPEER doesn't work

### ISSUE THREAD

**Issue by aequasi** [FriendsOfSymfony/FOSElasticaBundle#1492]
Trying to do this

```yaml
fos_elastica:
    clients:
        default:
            connections:
            -   url: '%env(ELASTICSEARCH_URL)%'
                ssl: true
                curl:
                    CURLOPT_SSL_VERIFYPEER: false
```

Gives me:   `Warning: curl_setopt() expects parameter 2 to be integer, string given `

**Comment by aequasi** [comment]
ended up doing:

```yaml
fos_elastica:
    clients:
        default:
            connections:
            -   url: '%env(ELASTICSEARCH_URL)%'
                ssl: true
                curl:
                    64: false # CURLOPT_SSL_VERIFYPEER
```

Not sure if thats right, but it works?
