### ISSUE TITLE
How to upgrade from `Provider` to `PagerProvider`?

### ISSUE THREAD

**Issue by Seb33300** [FriendsOfSymfony/FOSElasticaBundle#1497]
Hello,

I have to upgrade a project to Symfony 4 and this require to upgrade your bundle to the 5.0 version.

The project I have to upgrade contains a custom class implementing `FOS\ElasticaBundle\Provider\ProviderInterface` interface and another one extends `FOS\ElasticaBundle\Doctrine\ORM\Provider` class.
Both are deprecated:
```
@deprecated since 4.1 will be removed in 5.x. Use PagerProvider instead
```

[`PagerProviderInterface`](https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/src/Provider/PagerProviderInterface.php) seems to work differently from the previous [`Provider`](https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/4.x/Provider/ProviderInterface.php) interface.

Is it possible to have an example or more details on how I should migrate to the new interface?

Thank you

**Comment by Seb33300** [comment]
Based on [3.2 documentation](https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/3.2.x/Resources/doc/cookbook/manual-provider.md#manual-provider) example, if I understand properly, the result should be:

``` php
namespace Acme\UserBundle\Provider;

use FOS\ElasticaBundle\Provider\PagerProviderInterface;
use FOS\ElasticaBundle\Provider\PagerfantaPager;
use Pagerfanta\Pagerfanta;
use Pagerfanta\Adapter\ArrayAdapter;

class UserPagerProvider implements PagerProviderInterface
{
    public function provide(array $options = array())
    {
        $document = new Document();
        $document->setData(array('username' => 'Bob'));

        return new PagerfantaPager(new Pagerfanta(new ArrayAdapter([$document])));
    }
}
```
Can someone confirm if I am right?

**Comment by Seb33300** [comment]
@makasim You worked on the PR to implement this.
Can you please confirm if I am right in me previous comment?

The project I have to migrate also overwrite the Doctrine ORM Provider `filterObjects` method to filter results by language like this:
```
namespace App\Doctrine\ORM;

use FOS\ElasticaBundle\Doctrine\ORM\Provider as BaseProvider;

class Provider extends BaseProvider
{
    protected function filterObjects(array $options, array $objects)
    {
        // Translatables objects are indexed currently based on the indexName which defines the locale
        $locale = $options['indexName'];

        $objects = parent::filterObjects($options, $objects);

        $return = [];
        foreach ($objects as $object) {
            // Test if a localisation exists
            if (!$object->getTranslations()->containsKey($locale)) {
                continue;
            }

            // Sets the current locale
            $object->setCurrentLocale($locale);

            $return[] = $object;
        }

        return $return;
    }
}
```

It looks like we should use ORMPagerProvider now?
Any easy way to implement the same thing with the new providers?

**Comment by makasim** [comment]
I've reduced the time I spend on open source to a bare minimum. Sorry about that.

**Comment by rayrigam** [comment]
@Seb33300 Your example is similar to the one in here : https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/4.x/Resources/doc/cookbook/manual-provider.md
I tried using it with `return new PagerfantaPager(new Pagerfanta(new ArrayAdapter($documents)));` where `$documents` is an array of `Elastica\Document` objects. However, I get this error with the console command `php bin/console fos:elastica:populate`:
> PersisterRegistry.php line 47:
> No persister was registered for index "acme_index" and type "acme_type".

Any idea how to solve that?

**Comment by ivansrdic** [comment]
@Seb33300 @rayrigam 

1. Create the pager provider service
```php
<?php
namespace Acme\UserBundle\Provider;

use FOS\ElasticaBundle\Provider\PagerProviderInterface;
use FOS\ElasticaBundle\Provider\PagerfantaPager;
use Pagerfanta\Pagerfanta;
use Pagerfanta\Adapter\ArrayAdapter;

class UserPagerProvider implements PagerProviderInterface
{
    public function provide(array $options = array())
    {
        new PagerfantaPager(new Pagerfanta(new ArrayAdapter([ /* an array of objects */ ])));
    }
}
```

2. Register the pager provider service in `services.yaml`
```yaml
# app/config/services.yaml
services:
    acme.search_provider.user:
        class: Acme\UserBundle\Provider\UserPagerProvider
        tags:
            - { name: fos_elastica.pager_provider, index: app, type: user }
```

3. Configure an index in `fos_elastica.yaml`
```yaml
# app/config/packages/fos_elastica.yaml
fos_elastica:
    indexes:
        app:
            types:
                user:
                    persistence:
                        provider:
                            service:  acme.search_provider.user
```
