### ISSUE TITLE
Concurrency DBS and elastic

### ISSUE THREAD

**Issue by cbastienbaron** [FriendsOfSymfony/FOSElasticaBundle#1505]
Hi,

I have, some times, an error 
```
An Error Occurred! Uncaught PHP Exception Twig_Error_Runtime: "An exception has been thrown during the rendering of a template ("Cannot find corresponding Doctrine objects (19) for all Elastica results (20). IDs: 791369, 771546, 792544, 781456, 789694, 791622, 789608, 781678, 791617, 789722, 786340, 791735, 791683, 792667, 790794, 791641, 788715, 790830, 792686, 792688"
```

This append when some entity have removed, time with sync of elastica and request for this resource.

Thinks there is no deal if i return 19 entity (DBS) instead of 20 (for elastic), there is an option or a workaround to say to FoselasticaBundle, ok we have a number mismatch result but it's not critical at all and return my 19 results ?

**Comment by cbastienbaron** [comment]
RTFM idiot :)

```yaml
                user:
                    persistence:
                        elastica_to_model_transformer:
                            ignore_missing: true
```
