### ISSUE TITLE
Pass a *service* in the persistence repository

### ISSUE THREAD

**Issue by nayzo** [FriendsOfSymfony/FOSElasticaBundle#1510]
Hello,

Actually in the index persistence configuration we can passe a FQCN of the Repository. Is there a way to passe also a _service_ name ?

 ```
persistence:
    driver: orm
    model: App\Entity\Foo
    provider: ~
    finder: ~
    repository: App\Repository\FooRepository  OR  app.foo.repository  <=== HERE
```

The idea behind all this is to possibly pass and inject parameters and services in to the reposiotory class.
If it's not the case, I'm willing to make a pull request for this feature.
