### ISSUE TITLE
How to disable persistence completely

### ISSUE THREAD

**Issue by benr77** [FriendsOfSymfony/FOSElasticaBundle#1520]
I might be going slightly mad, but I cannot find any simple way to disable the persistence functionality completely.

I have two applications. 

App 1 - Uses this bundle to create and populate an index from Doctrine ORM as normal.

```
fos_elastica:
    indexes:
        people:
            client: default
            types:
                person:
                    properties:
                        id: ~
                        phoneNumber: ~
                    persistence:
                        driver: orm
                        model: App\Messaging\Domain\Model\People\Person
                        finder: ~
                        provider: ~
```

App 2 - Uses this bundle to query the index (no finders) and manually populate a different, localised entity
```
fos_elastica:
    indexes:
        people:
            client: default
            types:
                person:
                    properties:
                        id: ~
                        phoneNumber: ~
```
I'm getting `[InvalidArgumentException] No providers were registered for index "people".`

How can I completely ignore persistence operations in app 2 ?

Looks like related to #1507
