### ISSUE TITLE
[indexes][alias] - how that work ?

### ISSUE THREAD

**Issue by cbastienbaron** [FriendsOfSymfony/FOSElasticaBundle#1522]
Hi guys,

i'm searching infos about `use_alias: true` and behaviour to have zero downtime during a populate (with changing schema) and auto switch alias to new index created ... 
Pretty sure i'm missing something here. 
Here my conf with fos es
```yaml
fos_elastica:
    clients:
        default:
            host: "%elasticsearch_host%"
            port: "%elasticsearch_port%"
            retryOnConflict: 3
    indexes:
        toto:
            use_alias: true
            index_name: toto_search
            ...
```
Es POV aliases

```bash
curl -XGET 'http://localhost:9200/_alias/?pretty'
{
  "toto_search" : {
    "aliases" : { }
  },
  "toto_search_2019-05-28-112501" : {
    "aliases" : { }
  }
}
```
IMHO, when i do a populate, a new index is created and alias must point on this new index (when f:e:p process is terminated). But it's not the case, i 've to do this manualy 
```bash
curl -X POST "localhost:9200/_aliases" -H 'Content-Type: application/json' -d'
{
    "actions" : [
        { "add" : { "index" : "toto_search_2019-05-28-103956", "alias" : "toto_search" } }
    ]
}
'
```
What is the point i'm missing ? 
Thks ;)
