### ISSUE TITLE
caused Limit of total fields [1000] in index [stats] has been exceeded

### ISSUE THREAD

**Issue by manu-sparheld** [FriendsOfSymfony/FOSElasticaBundle#1527]
Hi, I have below setting in `fos_elastica.yaml` but While populating I get error: caused Limit of total fields [1000] in index [general_stats] has been exceeded
```
    stats:
            settings:
                blocks:
                    read_only_allow_delete: null
                mapping:
                    total_fields:
                        limit: 100000
```

**Comment by viunyk** [comment]
Hi, 
Try like this 

```
  indexes:
    YOU_DOCUMENT_TYPE:
      settings:
        index.mapping.total_fields.limit: 2000
```
