### ISSUE TITLE
Options available for Index templates

### ISSUE THREAD

**Issue by malcomhamelin** [FriendsOfSymfony/FOSElasticaBundle#1540]
I've been reading this documentation and I'm trying to do something like "every field named 'created' is of type 'date' in every index in every document".

It works by adding a "dynamic_templates" config for each index but it is highly inefficient, as it adds a lot of lines into my config.yml file (like, hundreds).

[I saw the "Index templates" option](https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/templates.md
) which seems to me the solution to do what I want, but it seems that there is no complete list of suboptions for "Index templates" in FOSElastica. I tried things from the official documentation but it doesn't work.

Any idea as to what is the most efficient way to do **"every field named 'created' is of type 'date' in every index in every document"** ?

**Comment by malcomhamelin** [comment]
I found the solution for my problem :

```
index_templates: # https://www.elastic.co/guide/en/elasticsearch/reference/6.8/indices-templates.html
        base_template: # this is a custom name for the template
            client: default
            template: "*" # this is where you define which indices will use this template
            types:
                _doc: # this is where you define which types will use this (_doc stands for every type/documents)
                    dynamic_templates: # https://www.elastic.co/guide/en/elasticsearch/reference/6.8/dynamic-templates.html
                        dynamic_date_template:
                            match_pattern: regex
                            match: created|updated|tpq_date|taq_date
                            mapping:
                                type: date
```
