### ISSUE TITLE
Case insensitive sort?

### ISSUE THREAD

**Issue by modstore** [FriendsOfSymfony/FOSElasticaBundle#1548]
I'm using the serializer and I have a text field on my object: title.
I want to search and sort on this field. It's mostly working, I am sorting using: title.keyword as it wasn't possible so sort on title directly.
My only issue is that all upper case results come before the lower case results. So I need to add a lowercase analyzer to the title.keyword field I think, I'm just not sure of how to do this using the serializer. Or do I put this in the config, but not sure on the syntax to set this up.

Any help would be appreciated, cheers!

**Comment by XWB** [comment]
We simply use two fields for the title property: one for search and one for sort. Something like this:

```yaml
title:
    type: text
    fields:
        ngrams:
            search_analyzer: text
            analyzer: ngram
            type: text
        raw:
            type: keyword
            index: false
```

```php
$query = new Query();
$query->setSort(['title.raw' => 'desc']);
```
