### ISSUE TITLE
ManyToMany relation print all DB

### ISSUE THREAD

**Issue by sharipovmarat** [FriendsOfSymfony/FOSElasticaBundle#1550]
Hi! How can i skip `articles` field in `tags` object? Result return 1000+ objects..... Any idea?
```
### fos_elastica.yaml
indexes:
        app: 
            index_name: app_%kernel.environment%
            types:
                articles:
                    properties: 
                        id: ~
                        // some fields
                        tags: ~
                    persistence:
                        driver: orm
                        model: App\Entity\Articles
                        provider: ~
                        finder: ~
```
```
### App\Entity\Articles.php
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;
    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Tags", mappedBy="articles")
     */
    private $tags;
```

```
### App\Entity\Tags.php
  /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;
    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Articles", inversedBy="tags")
     */
    private $articles;

```

```
### SearchController.php
       $finder = $this->container->get('fos_elastica.finder.app.articles');
        $paginator = $this->get('knp_paginator');
        $results = $finder->createPaginatorAdapter($q);
        $pagination = $paginator->paginate($results, $page, 1);
       return $pagination;
```

```
### Output

{
    "current_page_number": 1,
    "num_items_per_page": 1,
    "items": [
        {
            "id": 802,
            "title": "Сырдария өзенінің арнасынан шығуы Қазалы ауданының бірқатар шаруашылығын шығынға ұшыратты",
            "active": true,
            "main": false,
            "pubdate": "2017-03-29T09:08:44+06:00",
            "fulltxt": "*****",
            "videoitube": "11729",
            "moduletype": "Articles",
            "itubetags": [],
            "tags": [
                {
                    "id": 1,
                    "slug": "bastyaqparat",
                    "title": "Басты ақпарат",
                    "active": true,
                    "description": "Басты ақпарат",
                    "position": 1,
                    "inmenu": true,
                    "articles": [
                        {
                            "id": 1,
                            "title": "Индонезия: Суматра жағалауында 6,5 балдық жер сілкінісі болды",
                            "active": true,
                            "main": false,
                            "pubdate": "2016-06-02T01:10:42+06:00",
                            "fulltxt": "****",
                            "mainimg": "/old/articles/article_19.jpg",
                            "moduletype": "Articles",
                            "itubetags": [],
                            "tags": [],
                            "views": 63
                        },

                        ******** ALL Articles with TagId=1 
                        ******** Count 1000+

                        ],
    "total_count": 3,
    "paginator_options": {
        "pageParameterName": "page",
        "sortFieldParameterName": "sort",
        "sortDirectionParameterName": "direction",
        "filterFieldParameterName": "filterField",
        "filterValueParameterName": "filterValue",
        "distinct": true
    },
    "custom_parameters": [],
    "route": "search",
    "params": {
        "q": "Сырдария"
    },
    "page_range": 5,
    "template": "@KnpPaginator/Pagination/sliding.html.twig",
    "sortable_template": "@KnpPaginator/Pagination/sortable_link.html.twig",
    "filtration_template": "@KnpPaginator/Pagination/filtration.html.twig"
}
```
