### ISSUE TITLE
[Question] Why is null normalized as empty array for nested object?

### ISSUE THREAD

**Issue by devmaslov** [FriendsOfSymfony/FOSElasticaBundle#1558]
Hello,

I stumbled upon one issue because nested objects are transformed into an empty array instead null before they get into elasticsearch. I want to make this module work along with [Api Platform](https://api-platform.com/docs/core/elasticsearch/#elasticsearch-support). Api Platform has a read only support for elasticsearch, so I'm trying to use this bundle for populating elastic with data. Api Platform just searches entities and de-normalizes them. And it's getting inconvenient when value which is supposed to be null appears as an empty array. If it's a relation to another entity, serializer tries to "de-normalizes" that empty array into an entity and it leads to errors.

So the question is, why does it work this way? I can see in code that it was done on purpose:
[transformNested](https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/dbfd82439530f85df738726a24a2ba891c0f4797/src/Transformer/ModelToElasticaAutoTransformer.php#L117)
[Unit test](https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/dbfd82439530f85df738726a24a2ba891c0f4797/tests/Unit/Transformer/ModelToElasticaAutoTransformerTest.php#L529)

As an example let's say we have an entity called `User` which has one-to-one relation to `Image` entity. The main idea here:

```
user:
    types:
        _doc:
            properties:
                id:
                    type: integer
                username:
                    type: keyword
                image:
                    type: object
                    properties:
                        id:
                            type: keyword
                        name:
                            type: keyword
```

I create a new User(id=1, username="test", image=null)
When it's indexed to elasticsearch it would looks like this:
```
{"id": 1, "username": "test", "image": []}
```
When it's de-normalized it looks like this: User(id=1, username="test", image=Image(id=null, name=null))

There're several ways to fix this not touching code of this bundle, but all of that would be just workarounds. It looks to me that the root of the problem that null is not represented as it is in elastic in the first place and it should be changed. But I cann't understand why it was implemented this way on purpose.
