### ISSUE TITLE
Process killed while populating

### ISSUE THREAD

**Issue by OskarStark** [FriendsOfSymfony/FOSElasticaBundle#1564]
Hi 👋 

When I run `bin/console fos:elasticas:populate` I ran into a process terminate.
The output is `Killed`:
<img width="536" alt="Screenshot 2019-10-18 10 59 35" src="https://user-images.githubusercontent.com/995707/67181086-d812aa00-f3db-11e9-8582-81a847c7499c.png">

While debugging it shows, that it works fine in `dev` mode on the same machine.
<img width="503" alt="Screenshot 2019-10-18 10 55 54" src="https://user-images.githubusercontent.com/995707/67181100-e234a880-f3db-11e9-8d05-1afdd7ac43ef.png">

The difference between `dev` and `prod` is, that I use the following **default** doctrine settings (Symfony 4 via flex) in `prod`, but the `dev` one is empty:
```yaml
# config/packages/prod/doctrine.yaml
doctrine:
    orm:
        auto_generate_proxy_classes: false
        metadata_cache_driver:
            type: service
            id: doctrine.system_cache_provider
        query_cache_driver:
            type: service
            id: doctrine.system_cache_provider
        result_cache_driver:
            type: service
            id: doctrine.result_cache_provider

services:
    doctrine.result_cache_provider:
        class: Symfony\Component\Cache\DoctrineProvider
        public: false
        arguments:
            - '@doctrine.result_cache_pool'
    doctrine.system_cache_provider:
        class: Symfony\Component\Cache\DoctrineProvider
        public: false
        arguments:
            - '@doctrine.system_cache_pool'

framework:
    cache:
        pools:
            doctrine.result_cache_pool:
                adapter: cache.app
            doctrine.system_cache_pool:
                adapter: cache.system

```

when using sth like this, it works:
```yaml
# config/packages/prod/doctrine.yaml
doctrine:
    orm:
        auto_generate_proxy_classes: false
        metadata_cache_driver: apcu
        query_cache_driver: apcu
        result_cache_driver: apcu

```

***PHP version**
```
PHP 7.3.9 (cli) ( ZTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.9, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.9, Copyright (c) 1999-2018, by Zend Technologies
    with blackfire v1.27.0~linux-x64-zts73, https://blackfire.io, by Blackfire
```
**Library version**
```
friendsofsymfony/elastica-bundle    v5.1.1
```

It turns out, that it uses more memory in `prod`, than in `dev`.
Any ideas how to fix this?
