### ISSUE TITLE
How to bypass Doctrine SQLFilter

### ISSUE THREAD

**Issue by endelwar** [FriendsOfSymfony/FOSElasticaBundle#1606]
I have a Doctrine\ORM\Query\Filter\SQLFilter listening to queries that I want to bypass when I need to get the entities after an elasticsearch query.

Usually I'd do this with ```$this->getEntityManager()->getFilters()->disable('my_filter');``` in Entity Repository method.

Whis is the right way to achieve this using FOSElasticaBundle?

**Comment by endelwar** [comment]
My fault, it's in the [documentation](https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/usage.md#using-a-custom-query-builder-method-for-transforming-results)

In my entity repository I added
```php
    public function createElasticaQueryBuilder($alias, $indexBy = null): \Doctrine\ORM\QueryBuilder
    {
        $this->getEntityManager()->getFilters()->disable('my_filter');

        return $this->createQueryBuilder($alias, $indexBy);
    }
```

and in `fos_elastica.yaml`
```yaml
types:
  mytype:
    persistence:
      elastica_to_model_transformer:
        query_builder_method: createElasticaQueryBuilder
```
