### ISSUE TITLE
Softdeletable with foselasticabundle

### ISSUE THREAD

**Issue by fldv** [FriendsOfSymfony/FOSElasticaBundle#1608]
I have a database, and I deleted a relationship via gedmo softdeletable.

I created the mapping, via the YAML file, and when I execute the following command **fos:elastica:populate** i get an error.

**Entity of type 'App\Entity\B' for IDs id(X) was not found**

Do you have a solution ?

```
fos_elastica.yaml

  clients:
    default: { url: '%env(ELASTICSEARCH_URL)%/' }

  indexes:
    app:
      types:
        A:
          properties:
            id: ~
            name: ~
            B:
              type: object
              id: ~
          persistence:
            driver: orm
            model: App\Entity\A
```

Thank you for your answers
