### ISSUE TITLE
wrong index_name populate ?

### ISSUE THREAD

**Issue by ibasaw** [FriendsOfSymfony/FOSElasticaBundle#1610]
hi

```
PHP : 7.2
SF: 3.4.38
ES: 6.8.1
ESBUNDLE: v5.1.1
```

```
fos_elastica:
  clients:
    default: { host: '%es_ip%', port: '%es_port%' }
  indexes:
    app:
      index_name: v2_%kernel.environment%
```

I am in prod i insert item in my DB with a command controller SF, so the listener is use, then i see that my datas are populate in the dev env, not in the prod ?!!!

Why ?

++
