### ISSUE TITLE
[question] indexable_callback for level 2 entities

### ISSUE THREAD

**Issue by GTopalian** [FriendsOfSymfony/FOSElasticaBundle#1612]
Hello, 

Let's say, I have a "book" and an "author" entity; 

Then entity `book` has a `getPublic()` method that that returns "true" if the book is public. 
In the mapping config I use 
```yml
 book:
            types:
                book:
                    indexable_callback: 'getPublic'
```
And indeed, it only indexes books that have their `getPublic() == true` :+1: 
Lets say I have a book with `"title":"toto"` and `"public":false`, it is not indexed.  

Now, I also have an class "author" with an n-to-n relationship with books. 
The mapping are made so that when I index author, I get this

```json
"author":{
    "name":"titi",
    "books":[{
        "title": "toto",
        "public": false
    }]
}
```
The problem is: the callback "getPublic" is well triggered for 1st level indexation, and was not called with this "second level". 
Is it normal? And if yes, what would be a workaround? 
Thanks!!
