### ISSUE TITLE
Symfony container linter raises exception with index_template

### ISSUE THREAD

**Issue by spointecker** [FriendsOfSymfony/FOSElasticaBundle#1620]
Hello,

I have the following config for a index_template
```
fos_elastica:
   index_templates: 
        base_template: 
            client: default
            template: "*" 
            types:
                _doc:
                    dynamic_templates: 
                        dynamic_rating_template: 
                            path_match: "*rating.*.*.rating"
                            mapping:
                                type: float
```

When I run the following symfony console command `bin/console lint:container` I get this exception:
```
  Invalid service "fos_elastica.index_template.base_template._doc": method "FOS\ElasticaBundle\Elastica\IndexTemplate::getType()" does not exist.  
```

If I remove the index_template config, the linter does not raise an exception!
