### ISSUE TITLE
Search without hydration through fos.elastical.finder.*

### ISSUE THREAD

**Issue by spiroski** [FriendsOfSymfony/FOSElasticaBundle#1631]
Hello,

Is it possible to search without hydrating ( Transforming ) the results with a finder?

In my case, I would like to only get the ids ( Avoid querying the database ).

If it is not possible, I believe it is very useful to introduce this feature.

**Comment by tacman** [comment]
Here's how I solved that problem, though I don't think it's elegant.  Specifically, I can't figure out a way to set the class and  options (to set hydrate to false) from the yaml configuration.

Anyway, you need to create a transformer service:

```php
<?php

namespace App\Transformers;

use Doctrine\Common\Persistence\ManagerRegistry;
use FOS\ElasticaBundle\Doctrine\ORM\ElasticaToModelTransformer;

class ElasticaToArticleIdTransformer extends ElasticaToModelTransformer
{
    public function __construct(ManagerRegistry $registry, string $objectClass='NOT USED', array $options = [])
    {
        $options['hydrate'] = false;
        parent::__construct($registry, $objectClass, $options);
    }

    protected function findByIdentifiers(array $identifierValues, $hydrate): array
    {
        return empty($identifierValues) ? [] : array_map(fn($aId) => ['id' => (int)$aId], $identifierValues);
    }
}
```

Then in fos_elastica.yaml, set the elastica_to_model_transformer service.  

```yaml
fos_elastica:
  clients:
    default: { url: '%env(ELASTICSEARCH_URL)%' }
  indexes:
    article:
      persistence:
        driver: orm
        elastica_to_model_transformer:
          service: App\Transformers\ElasticaToArticleIdTransformer
        model:  App\Entity\Article
```

You'll get back an array of arrays containing just the ids.
