### ISSUE TITLE
Use Symfony Messenger component to populate index

### ISSUE THREAD

**Issue by tacman** [FriendsOfSymfony/FOSElasticaBundle#1635]
Since the master branch requires at least Symfony 4.4, I would like to propose that we use the Symfony Messenger component to populate the index.  I think instead of dispatching an event, we could dispatch a messageand then handling the message, the behavior will continue to be exact what we have.  Or the event listeners that inserts the document(s) into the index could be refactored to a message/messageHandler.

That way, if the messenger configured for async, then it can be queued in RabbitMQ or even another Doctrine table.  This will automatically give us multiple retries and failure reports.  This is pretty common, since the ES server is often located elsewhere on the network.  Plus we'd be able to catch errors like bad UTF-8 encoding, etc.  

If the message component isn't configured for async, it'll have the exact behavior it has now.

I'm happy to contribute some code and make a PR if there's support for doing this (though I might not actually be the right person, since I'm not an expert with this bundle, and don't really understand all the listeners and subscribers).

Thanks for your consideration of this.

**Comment by XWB** [comment]
I agree using Symfony Messenger would be the way to go.

**Comment by XWB** [comment]
See https://github.com/FriendsOfSymfony/FOSElasticaBundle/pull/1640

**Comment by pluseg** [comment]
To whom, who didn't understand how to use Symfony Messenger component in real life. In the PR guys added a Message and Handler, but somehow Symfony doesn't see them, so you need to:

1. Define new transport (queue) and point Message into it in `config/packages/messenger.yaml`:
```
framework:
    messenger:
        transports:
            ...
            # Specify your transport instead of Doctrine if needed
            elasticsearch_population: 'doctrine://default?queue_name=elasticsearch_population'

        routing:
             ...
             'FOS\ElasticaBundle\Message\AsyncPersistPage': elasticsearch_population
```

2. Define already implemented but not visible services in services.yaml:
```
services:
    ...
    FOS\ElasticaBundle\Persister\AsyncPagerPersister:
        arguments:
            - '@fos_elastica.pager_persister_registry'
            - '@fos_elastica.pager_provider_registry'
            # In the bundle this messagebus is different, but we should pass official Symfony bus.
            - '@Symfony\Component\Messenger\MessageBusInterface'
        tags:
            - { name: "fos_elastica.pager_persister", persisterName: "async" }

    FOS\ElasticaBundle\Message\Handler\AsyncPersistPageHandler:
        tags: [ messenger.message_handler ]
```

3. Start async populatation the index:
```
# Because we define persisted with `persisterName: "async"` above, we can run it with.
bin/console fos:elastica:populate --pager-persister=async
```

4. Read tasks for population from queue and really feed the data:
```
bin/console messenger:consume elasticsearch_population --limit=100
```

cc FYI @XWB
