### ISSUE TITLE
Make the finder services public, so they can be injected and TypeHinting

### ISSUE THREAD

**Issue by tacman** [FriendsOfSymfony/FOSElasticaBundle#1637]
The documentation on how to search assumes the container is available, which is not longer very common in Symfony 5 apps.

    $finder = $this->container->get('fos_elastica.finder.app.user');

https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/usage.md

If these were services were public, they could be injected via typehinting and variable naming.

Alternatively (or additionally), maybe there's a way to get the finder service from a service that is already public.  If so, what is that?  I'll update the documentation once I learn how to do it.  Thanks.

**Comment by XWB** [comment]
You don't have to make the service public. Just inject it via service configuration:

```yaml
    # services.yaml
services:

    App\Elastic\MyService:
        arguments:
            $finder: '@fos_elastica.finder.app.user'
```

```php
namespace App\Elastic;

use FOS\ElasticaBundle\Finder\PaginatedFinderInterface;

class MyService
{
    private PaginatedFinderInterface $finder;

    public function __construct(PaginatedFinderInterface $finder)
    {
        $this->finder = $finder;
    }
}
```

**Comment by tacman** [comment]
Slightly less setup is to bind the parameters:
```yaml
services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $finderWork: '@fos_elastica.finder.work'
            $finderParagraph: '@fos_elastica.finder.paragraph'
```

Then in the service or controller, use that variable

```php
    /**
     * @Route("/search", name="search_dashboard")
     */
    public function search(Request $request, FinderInterface $finderParagraph, FinderInterface $finderWork, IndexManager $indexManager)
    {
```

BUT if they were public, these services could be used without configuring them in services.yaml, by using the camelcase version of the service name __construct(FinderInterface $fosElasticaFinderWork) I think.  This is how monolog channels work, for example.  

I think they should be public, though, because that's how they're intended to be used, and it greatly simplifies the documentation and DX.
