### ISSUE TITLE
Analyzer

### ISSUE THREAD

**Issue by shevaton7** [FriendsOfSymfony/FOSElasticaBundle#166]
I'm trying to configure my config.yml file with the analyzer option but I do not have a concrete example to do so.
 please someone give me an example configuration with analyzers, several entities, and a wide index finder.

I tried to use the following configuration, but it doesn't work. I got this error : 

```
IndexMissingException[[website] missing] 
```

My config:

```
foq_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        website:
            client: default
            finder:
        doc:
            settings:
                index:
                    analysis:
                        analyzer:
                            my_analyzer:
                                type: custom
                                tokenizer: lowercase
                                filter   : [my_ngram]
                        filter:
                            my_ngram:
                                type: "nGram"
                                min_gram: 3
                                max_gram: 5
            types:
                ThOraInfo:
                    mappings:
                        macName: { boost: 5, analyzer: my_analyser }
                        oraInstance: { boost: 3 }
                        oraVersion: { boost: 3 }
                    persistence:
                        driver: orm
                        model: Visiondpi\VisionBundle\Entity\ThOraInfo
                        listener:
                            insert: true
                            update: true
                            delete: true
                        provider:
                            query_builder_method: createIsActiveQueryBuilder
                        identifier: idThOraInfo
                        repository: Visiondpi\VisionBundle\Repository\ThOraInfoRepository
                ThSybInfo:
                    mappings:
                        macName: { boost: 8, analyzer: my_analyser }
                        sybInstance: { boost: 3 }
                        SybVersion: { boost: 3 }
                    persistence:
                        driver: orm
                        model: Visiondpi\VisionBundle\Entity\ThSybInfo
                        listener:
                            insert: true
                            update: true
                            delete: true
                        provider:
                            query_builder_method: createIsActiveQueryBuilder
                        identifier: id
                        repository: Visiondpi\VisionBundle\Repository\ThSybInfoRepository
                ThMysqlInfo:
                    mappings:
                        macName: { boost: 5, analyzer: my_analyzer }
                        myServeur: { boost: 3 }
                        myVersion: { boost: 3 }
                    persistence:
                        driver: orm
                        model: Visiondpi\VisionBundle\Entity\ThMysqlInfo
                        listener:
                            insert: true
                            update: true
                            delete: true
                        provider:
                            query_builder_method: createIsActiveQueryBuilder
                        identifier: idThMysqlInfo
                        repository: Visiondpi\VisionBundle\Repository\ThMysqlInfoRepository
```

Thanks !
