### ISSUE TITLE
Outdated doc for indexes

### ISSUE THREAD

**Issue by sparrowek** [FriendsOfSymfony/FOSElasticaBundle#1684]
The doc says:
```
fos_elastica:
    indexes:
        user:
            properties:
                username: ~
                firstName: ~
                lastName: ~
                email: ~
```

But now:
```
fos_elastica:
    indexes:
        app:
            types:
                user:
                    properties:
```

Is the correct form.
