### ISSUE TITLE
Populate index throws "Cannot unset string offsets"

### ISSUE THREAD

**Issue by sparrowek** [FriendsOfSymfony/FOSElasticaBundle#1685]
Here is my config:
```
fos_elastica:
    serializer: ~
    clients:
        default: { url: '%env(ELASTICSEARCH_URL)%' }
    indexes:
        app_entry:
            types:
                entry:
                    persistence:
                        # the driver can be orm, mongodb or phpcr
                        driver: orm
                        model: App\Entity\Entry
                        provider: ~
                        # finder: ~
                    properties:
                        title: keyword
                        url: keyword
```
This throws "Cannot unset string offsets" during population
Full log:
```
Resetting app_entry
[error] Error thrown while running command "fos:elastica:populate --verbose". Message: "Cannot unset string offsets"

[critical] Uncaught Error: Cannot unset string offsets


In MappingBuilder.php line 126:

  [Error]
  Cannot unset string offsets  


Exception trace:
  at /srv/api/vendor/friendsofsymfony/elastica-bundle/src/Index/MappingBuilder.php:126
 FOS\ElasticaBundle\Index\MappingBuilder->fixProperties() at /srv/api/vendor/friendsofsymfony/elastica-bundle/src/Index/MappingBuilder.php:98
 FOS\ElasticaBundle\Index\MappingBuilder->buildTypeMapping() at /srv/api/vendor/friendsofsymfony/elastica-bundle/src/Index/MappingBuilder.php:31
 FOS\ElasticaBundle\Index\MappingBuilder->buildIndexMapping() at /srv/api/vendor/friendsofsymfony/elastica-bundle/src/Index/Resetter.php:116
 FOS\ElasticaBundle\Index\Resetter->resetIndex() at /srv/api/vendor/friendsofsymfony/elastica-bundle/src/Command/PopulateCommand.php:193
 FOS\ElasticaBundle\Command\PopulateCommand->populateIndex() at /srv/api/vendor/friendsofsymfony/elastica-bundle/src/Command/PopulateCommand.php:171
 FOS\ElasticaBundle\Command\PopulateCommand->execute() at /srv/api/vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at /srv/api/vendor/symfony/console/Application.php:929
 Symfony\Component\Console\Application->doRunCommand() at /srv/api/vendor/symfony/framework-bundle/Console/Application.php:96
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /srv/api/vendor/symfony/console/Application.php:264
 Symfony\Component\Console\Application->doRun() at /srv/api/vendor/symfony/framework-bundle/Console/Application.php:82
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /srv/api/vendor/symfony/console/Application.php:140
 Symfony\Component\Console\Application->run() at /srv/api/bin/console:42
```
