### ISSUE TITLE
Command count requires authentication

### ISSUE THREAD

**Issue by pax1878** [FriendsOfSymfony/FOSElasticaBundle#1716]
I'm trying to connect to a mongodb in the configuration of elastica as a driver.

```yaml
persistence:
    driver: mongodb
    model: Some\Model
```

Mongodb is already successfully configured and used with the DoctrineMongoDBBundle.
I thought the ElasticaBunlde will use these configuration to establish a connection to mongodb. Isn't it?

All I get ist this excaption:

```
In Count.php line 176:
                                         
  command count requires authentication
```
