### ISSUE TITLE
Dynamic index name

### ISSUE THREAD

**Issue by darthf1** [FriendsOfSymfony/FOSElasticaBundle#1717]
I currently have one index defined, which is mapped to one of my ORM entities using the serializer.

In my app, its possibile to define an entity `Project`. All entities that get created later on, are related to this `Project`.
The entity which is related to this es-index, has millions of rows per project. When a new `Project` gets created, and new entities are inserted related to the es-index, I need to re-populate the es-index with `php bin/console fos:elastica:populate`. 

The downside of this approach (for me), is that the entire index gets repopulated while I only want it repopulated for a specific project. What I would like to achieve is defining an index per project, dynamically. I'm not sure how to get to this situation.

My assumptions:
- Current parameter supported is limited to SF parameters and can only be defined at compile time, not runtime.
- The `indexable_callback` cannot be changed on runtime. If it would be possibile, then I would check if the document is related to a certain project via the expression language. However, this does not cover the part where records in the index, related to that project, need to be reset first
- I could use `fos:elastica:create` to create a custom named index, however then theres no way to link this index to my config (persistence and serializer settings).

Is there a way to create an index with a dynamic name? Or create a custom index, and link it to one of my existing settings (and use the `indexable_callback`)?

`symfony.lock`
```yaml
"name": "symfony/framework-bundle",
"version": "v5.1.7",

"name": "symfony/messenger",
"version": "v5.1.7",

"name": "friendsofsymfony/elastica-bundle",
"version": "v6.0.0-beta3",
```

`fos_elastica.yaml`
```yaml
fos_elastica:
  messenger:
    message_bus: 'elasticsearch.bus'
  serializer: ~
  clients:
    default:
      url: '%env(ELASTICSEARCH_URL)%'
      compression: true
      logger: false
  indexes:
    myindexname:
      index_name: my_entity
      persistence:
        driver: orm
        model: App\Entity\MyEntity
      serializer:
        groups: ["myEntity:read"]
```

**Comment by deguif** [comment]
If you use a service as `indexable_callback` wouldn't that solve your problem, as you can do what you want by injecting the parameters / environment variable you want?

See https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/indexes.md#testing-if-an-object-should-be-indexed for the different approaches allowed for configuring `indexable_callback`.

**Comment by darthf1** [comment]
Well my issue starts earlier in the process:
- User creates a project
- I want create an index for that project

My index definition:
```yaml
fos_elastica:
  indexes:
    myindexname:
      index_name: my_entity
      persistence:
        driver: orm
        model: App\Entity\MyEntity
      serializer:
        groups: ["myEntity:read"]
```

The index name is `my_entity`. For a project with `ID=1` this could become `my_entity_1` etc. 
Running
```php
php bin/console fos:elastica:create --index my_entity_1
```
Will return
```
Index "my_entity_1" is not configured.
```

If this is resolved, then the next step would be to populate this index. I guess `indexable_callback` could resolve this issue, but at the moment its to theoretical for me so I would need to get there to test this.
