### ISSUE TITLE
Call to a member function getRepository() on null

### ISSUE THREAD

**Issue by vertisan** [FriendsOfSymfony/FOSElasticaBundle#1724]
Hi,  
I'm trying to get data from ElasticSearch by using a custom repository but when I'm trying to prepare repository, I'm getting error:  
```
Call to a member function getRepository() on null
```
**Stack:**  
* Symfony 5.1
* ElasticSearch 7.1
* FOSElasticaBundle v6.0.0-beta3 (for ES 7 support)  

**Code:**  
**fos_elastica.yaml**
```yaml
fos_elastica:
    clients:
        default: { url: '%env(ELASTICSEARCH_URL)%' }
    indexes:
        book:
            properties:
                card_name: ~
            persistence:
                driver: orm
                model: App\Document\Book
                provider: ~
                finder: ~
                repository: App\Repository\BookRepository
```
**BookRepository.php**
```php
class BookRepository extends Repository
{
    public function findPopularBooks()
    {
        $query = new MatchAll();

        return $this->find($query);
    }
}
```
**BookController.php**
```php
class CardPopularityController extends AbstractController
{
    /**
     * @Route("/popular_books", methods={"GET"})
     */
    public function getPopularBooks(BookRepository $bookRepository)
    {
        $books = $bookRepository->findPopularBooks();

        return new JsonResponse($books);
    }
}
```
**services.yaml**
```yaml
parameters:

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

        bind:
            $repositoryManager: '@fos_elastica.repository_manager'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    App\Repository\BookRepository:
        class: App\Repository\BookRepository
        arguments:
            $finder: '@fos_elastica.finder.book'
```

Any ideas where can be problem?
