### ISSUE TITLE
Unable to run bundle with es 7.10 and symfony 4.4

### ISSUE THREAD

**Issue by swnjfn** [FriendsOfSymfony/FOSElasticaBundle#1730]
Hi,

i have problems running the bundle with symfony 4.4 and elasticsearch 7.10

I got an error when using the config example from the setup.md and using initial the `bin/console fos:elastica:populate` command.

**From the setup.md:**
```yaml
fos_elastica:
    indexes:
        user:
            persistence:
                # the driver can be orm, mongodb or phpcr
                driver: orm
                model: Acme\ApplicationBundle\Entity\User
                provider: ~
                finder: ~
            properties:
                username: ~
                firstName: ~
                lastName: ~
                email: ~
```

**customized to my test environment:**
```yaml
# app/config/packages/fos_elastica.yaml
fos_elastica:
  clients:
    default:
      host: localhost
      port: 9200
  indexes:
    user:
      properties:
        username: ~
        id: ~
      persistence:
        driver: orm
        model: path/to/my/entity/user
        provider: ~
        finder: ~

```

i got the follwing error

```bash
  Unrecognized options "properties, persistence" under "fos_elastica.indexes.user". Available options are "client", "finder", "index_name", "settings", "type_prototype", "types", "use_alias".  
```
So after some googling i got this hint: https://stackoverflow.com/a/54179421

```
php bin/console config:dump-reference fos_elastica
```
And this shows me that the structure is not the same mentioned in the `setup.md`. Is it possible that the current docs are not up to date or not compatible with my elasticsearch version?

So i changed my config file to this to get rid of that error from above:

```yaml
# app/config/packages/fos_elastica.yaml
fos_elastica:
  [clients...]
  indexes:
    user:
      index_name: user
      types:
        default:
          persistence:
            # the driver can be orm, mongodb or phpcr
            driver: orm
            model: path/to/my/entity/user
            provider: ~
            finder: ~
```
But i run in this error:

```bash
 Root mapping definition has unsupported parameters:  [default : {dynamic_date_formats=[], _meta={model=path/to/my/entity/user}}] [reason: Failed to parse mapping [_doc]: Root mapping definition has unsupport  
  ed parameters:  [default : {dynamic_date_formats=[], _meta={model=path/to/my/entity/user}}]]                                                                                                                     
```
Interesting because i never used `_doc` in my config.

so i decided to check whats happens when i use `_doc` as `type name`
```yaml
# app/config/packages/fos_elastica.yaml
fos_elastica:
  [clients..]
  indexes:
    user:
      index_name: user
      types:
        _doc:
          persistence:
            # the driver can be orm, mongodb or phpcr
            driver: orm
            model: path/to/my/entity/user
            provider: ~
            finder: ~
```
**Error:**
```bash
The mapping definition cannot be nested under a type [_doc] unless include_type_name is set to true. 
```

Interesting, the same error sems to appear in #1585 

Does anybody has a clou what i am doing wrong?

**Edit**

Bundle Version: v5.2.0
