### ISSUE TITLE
Is it possible to define global analyzers?

### ISSUE THREAD

**Issue by ongkevdel** [FriendsOfSymfony/FOSElasticaBundle#1748]
Hello,

Elasticsearch version: 6.0
FosElasticaBundle version: 5.2
Symfony version: 3.4

I wanted to ask if there is a way to define global analyzers and use them from multiple indexes?

Very blunt example:
```
fos_elastica:
    clients:
        default: { url: '%fos.elastica.auth_url%' }
    analyzers:
        global_analyzer:
            tokenizer: standard
            filter: [ standard, lowercase, asciifolding ]
    indexes:
        index_one:
            index_name: entity_one
            settings:
                index:
                    analysis:
                        analyzer: global_analyzer
            types:
                type_one:
                    properties:
                        name: ~
                        description: { analyzer: global_analyzer }
                    persistence:
                        driver: orm
                        model: AppBundle\Entity\EntityOne
                        finder: ~
        index_two:
            index_name: entity_two
            settings:
                index:
                    analysis:
                        analyzer: global_analyzer
            types:
                type_two:
                    properties:
                        name: ~
                        description: { analyzer: global_analyzer }
                    persistence:
                        driver: orm
                        model: AppBundle\Entity\EntityTwo
                        finder: ~
```

Cheers and thanks for taking your time!

**Comment by slappyslap** [comment]
Up !

**Comment by XWB** [comment]
That is not possible right now. Someone would have to make a feature.

**Comment by Gu3** [comment]
Hey, 
something like this maybe ? 

```
fos_elastica:
    indexes:
      access:
        use_alias: true
        index_name: place
        client: default
        finder: ~
        settings: &settings
          index:
            analysis:
              filter:
                french_elision:
                  type: elision
                  articles_case: true
                  articles: [ "l", "m", "t", "qu", "n", "s", "j", "d", "c", "jusqu", "quoiqu", "lorsqu", "puisqu" ]
                french_stemmer:
                  type: stemmer
                  language: light_french
              analyzer:
                french_heavy:
                  tokenizer: icu_tokenizer
                  filter: [ french_elision, icu_folding, french_stemmer ]
      place:
        use_alias: true
        index_name: place
        client: default
        finder: ~
        settings: *settings
```
