### ISSUE TITLE
Attempted to call an undefined method named "getConnection" of class "Doctrine\ODM\MongoDB\DocumentManager"

### ISSUE THREAD

**Issue by Barbarians** [FriendsOfSymfony/FOSElasticaBundle#1751]
I see this error in production environnement on launch fos:elastica:populate

I use FOSElastica version
![image](https://user-images.githubusercontent.com/15941539/105861791-61f1ef80-5fef-11eb-88e0-4d8db4ef4c1f.png)

https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/9e8903aaa0644afc0dbb697e2156e28e5a88865c/src/Doctrine/RegisterListenersService.php#L77

Version doctrine mongo
![image](https://user-images.githubusercontent.com/15941539/105861643-3b33b900-5fef-11eb-9d4e-71a3f4f81ca0.png)

https://github.com/doctrine/mongodb-odm/commit/7158b08278ab753652f2fec2eacf9d7f236fcffa#diff-12a2324f373722122b496af69d59ee2b3a19ac4d50b37511973397ed707e50f1L25

**Comment by Gemineye** [comment]
+1

**Comment by domhaas** [comment]
+1

**Comment by quentint** [comment]
Current solution is to force `debug_logging` to `true`, eg:

```yaml
fos_elastica:
    clients:
        default: { host: '%es_host%', port: '%es_port%' }
    indexes:
        app_answer:
            index_name: "%elastic_index_prefix%_%elastic_env%_answer"
            use_alias: true
            types:
                answer:
                    properties:
                        # (...)
                    persistence:
                        driver: mongodb
                        model: App\Document\Answer
                        provider:
                            debug_logging: true
                        # (...)
```
