### ISSUE TITLE
Undefined index: hits in ruflin/Elastica/lib/Elastica/ResultSet.php line 36

### ISSUE THREAD

**Issue by mrcmorales** [FriendsOfSymfony/FOSElasticaBundle#177]
Hello, 

I have this configuration of bundle:
# app/config/config.yml

foq_elastica:
    clients:
        default: { host: localhost, port: 80 }

```
indexes:
    website:
        client: default
        types:
            pagines:
                mappings:
                    titol: { boost: 5 }
                    descripcio: { boost: 3 }
                persistence:
                    driver: orm # orm, mongodb, propel are available
                    model: LoPati\BlogBundle\Entity\Pagina
                    provider:
                    listener:
                    finder: 
```

the Action code:

```
public function searchAction() {


    $finder =$this->container->get('foq_elastica.finder.website.pagines');

    /** var array of Acme\UserBundle\Entity\User */
    $pagines = $finder->find('XYZ');

    /** var array of Acme\UserBundle\Entity\User limited to 10 results */
    //$pagines = $finder->find('bob', 10);


    return $this->render('BlogBundle:Default:search.html.twig',array('pagines'=>$pagines));


}
```

And I obtained this error:

Notice: Undefined index: hits in 
/work/LoPati/vendor/ruflin/Elastica/lib/Elastica/ResultSet.php line 36

protected function _init(Elastica_Response $response) {
        $this->_response = $response;
        $result = $response->getData();
        $this->_totalHits = $result['hits']['total'];
        if (isset($result['hits']['hits'])) {
            foreach ($result['hits']['hits'] as $hit) {

What Can I do?

Thanks 

Regards
