### ISSUE TITLE
Using serializer and boost and analyzer

### ISSUE THREAD

**Issue by fGuix** [FriendsOfSymfony/FOSElasticaBundle#1784]
Hello,

I'm using foselastica in some projects and wanted to switch from using manual mappings to the serializer.
Here is an simplified version of my fos_elastica.yaml config :

``` yaml
...
      types:
        my_entity:
          properties:
            field1:
              boost: 10
              analyzer: my_entity_index_analyzer
              search_analyzer: my_entity_search_analyzer
            field2:
            field3:
              type: boolean
            field4:
              type: nested
              properties:
                field_en:
                  analyzer: field4_index_analyzer_en
                  search_analyzer: field4_index_analyzer_en
                  boost: 8
                field_fr:
                  analyzer: field4_index_analyzer_fr
                  search_analyzer: field4_search_analyzer_fr
                  boost: 8
...
```

My question : how should I set up the boost and analyzers parameters when using the serializer ?
I could not find an answer so far, and as I'm probably not the first in that situation, am I misunderstanding something there ?

Thanks in advance.
