### ISSUE TITLE
Doctrine hints on result hydration are not working

### ISSUE THREAD

**Issue by xantos05** [FriendsOfSymfony/FOSElasticaBundle#1806]
I trying to output Elastica results to a (KNP) paginator using:
`$pagination  = $paginator->paginate($finder->createPaginatorAdapter($query), $page_nr);`

It seems like the query hints in the fos_elastica.yml are not being used as i keep getting results in my default language (EN). I would like to get results for another language for example NL.

My fos_elastica.yml looks like this:

```
persistence:
    driver: orm
    model: App\Entity\Product
    elastica_to_model_transformer:        
         hints:
            - { name: '\Doctrine\ORM\Query::HINT_CUSTOM_OUTPUT_WALKER', value: 'Gedmo\Translatable\Query\TreeWalker\TranslationWalker' }
            - { name: '\Gedmo\Translatable\TranslatableListener::HINT_TRANSLATABLE_LOCALE', value: 'nl' }
            - { name: '\Gedmo\Translatable\TranslatableListener::HINT_FALLBACK', value: '1' }
    listener: { enabled: false }
    identifier: id
```

Hints for result hydration are being mentioned here: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/cookbook/hints-on-result-hydration.md

Any thoughts on this?
