### ISSUE TITLE
class java.util.ArrayList cannot be cast to class java.util.Map (java.util.ArrayList and java.util.Map are in module java.base of loader 'bootstrap')

### ISSUE THREAD

**Issue by nayzo** [FriendsOfSymfony/FOSElasticaBundle#1811]
Hello,

I'm getting this error when I execute: `bin/console fos:elastica:populate`:

`[Elastica\Exception\ResponseException]                                                                                                                
  class java.util.ArrayList cannot be cast to class java.util.Map (java.util.ArrayList and java.util.Map are in module java.base of loader 'bootstrap') `

**TAG:**  v6.0.0-beta4

**My Index:**

```yaml
fos_elastica:
    clients:
        default: { url: '%env(ELASTICSEARCH_URL)%' }
    indexes:
        user:
            properties:
                id: ~
            persistence:
                driver: orm
                model: App\Entity\User
                repository: App\Repository\SearchRepository
                elastica_to_model_transformer:
                    ignore_missing: true
```

**Exception trace:**

```bash
  at /var/www/vendor/ruflin/elastica/src/Transport/Http.php:178
 Elastica\Transport\Http->exec() at /var/www/vendor/ruflin/elastica/src/Request.php:181
 Elastica\Request->send() at /var/www/vendor/ruflin/elastica/src/Client.php:512
 Elastica\Client->request() at /var/www/vendor/friendsofsymfony/elastica-bundle/src/Elastica/Client.php:60
 FOS\ElasticaBundle\Elastica\Client->request() at /var/www/vendor/ruflin/elastica/src/Client.php:547
 Elastica\Client->requestEndpoint() at /var/www/vendor/ruflin/elastica/src/Index.php:664
 Elastica\Index->requestEndpoint() at /var/www/vendor/ruflin/elastica/src/Index.php:431
 Elastica\Index->create() at /var/www/vendor/friendsofsymfony/elastica-bundle/src/Index/Resetter.php:91
 FOS\ElasticaBundle\Index\Resetter->resetIndex() at /var/www/vendor/friendsofsymfony/elastica-bundle/src/Command/PopulateCommand.php:163
 FOS\ElasticaBundle\Command\PopulateCommand->populateIndex() at /var/www/vendor/friendsofsymfony/elastica-bundle/src/Command/PopulateCommand.php:148
 FOS\ElasticaBundle\Command\PopulateCommand->execute() at /var/www/vendor/symfony/console/Command/Command.php:256
 Symfony\Component\Console\Command\Command->run() at /var/www/vendor/symfony/console/Application.php:989
 Symfony\Component\Console\Application->doRunCommand() at /var/www/vendor/symfony/framework-bundle/Console/Application.php:96
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /var/www/vendor/symfony/console/Application.php:290
 Symfony\Component\Console\Application->doRun() at /var/www/vendor/symfony/framework-bundle/Console/Application.php:82
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /var/www/vendor/symfony/console/Application.php:166
 Symfony\Component\Console\Application->run() at /var/www/bin/console:43
```

Any Idea plz ?
