### ISSUE TITLE
No commands defined in the "fos:elastica" namespace

### ISSUE THREAD

**Issue by tuliof** [FriendsOfSymfony/FOSElasticaBundle#1814]
I followed the [documentation](https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/setup.md), installed v6.0.0-beta4 to be able to use with my ElasticSearch v7.13.4.

Then run the recipe for the basic configuration.

![Captura de Tela 2021-07-22 às 12 08 11 PM](https://user-images.githubusercontent.com/839142/126672067-4ac22839-ecf9-4dd6-93c2-8c0974fea4ed.png)

This is my `fos_elastica.yaml` config.

```yml
fos_elastica:
    clients:
        default: { url: '%env(ELASTICSEARCH_URL)%' }
    indexes:
        participant:
            persistence:
                driver: orm
                model: AppBundle\Entity\Invitation\Participant
                listener: ~
            properties:
                occupation: ~
                company: ~
```

I get the following error when running `php bin/console fos:elastica:populate`

![Captura de Tela 2021-07-22 às 12 04 50 PM](https://user-images.githubusercontent.com/839142/126671575-d7295de3-11d6-4b89-a868-6d82c297a5ba.png)
