### ISSUE TITLE
Bug with keyword indexing with an array field

### ISSUE THREAD

**Issue by murilozilli** [FriendsOfSymfony/FOSElasticaBundle#1831]
FOS/Elastic version: 5.1.x-dev

Issue happens if we use `type: keyword` alongside a `array` Doctrine field type.

This is our setup:

```
 types:
                recruiters:
                    properties:
                        roleTypes:
                            type: keyword
```

Than on our annotations:
```

    /**
     * @ORM\Column(type="array", nullable=true)
     */
    private $roleTypes = [];
```

Error message we get:

<img width="818" alt="Screen Shot 2021-10-25 at 11 27 23 am" src="https://user-images.githubusercontent.com/10093456/138618922-5dc4eaf9-24d8-44f0-a23c-4653e0546963.png">

I went in to find out why that specific entity object had an issue as this happened when 92% of our documents were already indexed.

Found out my roleTypes were serialised without having the 0 index filled, like:

`a:2:{i:1;s:9:"Permanent";i:2;s:10:"Fixed-term";}`

As you can see, we have i:1 and i:2 but not i:0 which can happen as this field stores arrays of any sort. To fix it I had to manually change this to `a:2:{i:0;s:9:"Permanent";i:1;s:10:"Fixed-term";}`

I ran the populate command again and it worked but this definitely felt like a bug.
