### ISSUE TITLE
property_path is not read

### ISSUE THREAD

**Issue by Radiergummi** [FriendsOfSymfony/FOSElasticaBundle#1834]
My model has a relation property `$country: Country`. During indexing, I'd like to store the country code instead of the country entity, so I added a `getCountryName(): string` getter to the model, and the following to the index mapping:
```yaml
country:
  property_path: country_name
  type: keyword
```

The country is still indexed as an empty array, however. Then, I tried digging through the code to see where `property_path` is even used - and as far as I can see, the `ObjectSerializerPersister` invoked calls `$document = $this->transformer->transform($object, []);`, and as no fields are being passed, the mapping will never be read.  

How is this even supposed to work in the first place?

**Comment by Radiergummi** [comment]
Sadly, the documentation leaves lots of topics untouched - especially regarding entity transformation....

**Comment by deguif** [comment]
Would that work?

 ```yaml
 country:
  property_path: country.countryName
  type: keyword
 ```
