### ISSUE TITLE
Environmental indexes / parameterise index name?

### ISSUE THREAD

**Issue by stevelacey** [FriendsOfSymfony/FOSElasticaBundle#185]
At the moment index names are specified as a key in the YAML configuration e.g.

```
foq_elastica:
    clients:
        default:
            host: localhost
            port: 9200
    indexes:
        my_index:
            client: default
            types:
                 my_type:
                    mappings:
                        name:
...
```

This means that the name can't be set by a parameter, parameters can only be used in values (as far as I can see).

I need environmental indexes. i.e. my_index_demo and my_index_prod as both are hosted on the same server.

This poses another problem however, that the finder service is based on this name, so every injection would need changing.

I've considered extending the bundle or adding a compiler pass to environmentalise the index name whilst keeping the service name the same, but I'm thinking that this surely isn't that rare a use case, and should probably be catered for in the bundle?

Any thoughts on how this could be achieved? Or how I should approach this problem if not the way I have described?
