### ISSUE TITLE
  Unrecognized option "types" 

### ISSUE THREAD

**Issue by StudioAH** [FriendsOfSymfony/FOSElasticaBundle#1855]
Hello, 

I am new to elastica but I  followed many docs I found and tried a lot of diffrent things but I can't figure a way to make this work.
What am I doing wrong ? 
symfony : 5.4
elastica : 6.1

error : 
```
  Unrecognized option "types" under "fos_elastica.indexes.app". Available options are "_id", "_routing", "_source", "analyzer", "client", "date_detection", "dynamic", "dynamic_date_formats", "dynamic_templates", "finder", "index_   
  name", "index_prototype", "indexable_callback", "numeric_detection", "persistence", "properties", "serializer", "settings", "use_alias".     
```    
Thanks 

```
#app/config/config.yml
fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }

    indexes:
        app:
            settings:
                analysis:
                    analyzer:
                        fr:
                            tokenizer: standard
                            filter: [ lowercase, stop_fr, snowball_fr ]
                        autocomplete:
                            type: custom
                            tokenizer: whitespace
                            filter: [ lowercase, engram, elision ]
                        csv:
                            type: pattern
                            pattern: '\s*,\s*'
                            lowercase: false
                    filter:
                        snowball_fr:
                            type: "snowball"
                            language: "French"
                        stop_fr:
                            type: "stop"
                            stopwords: "_french_"
                        engram:
                            type: edge_ngram
                            min_gram: 2
                            max_gram: 15
            types:
                # ---------
                # USER
                # ---------
                user:
                    properties:
                        username: ~
                        email: ~
                        organization:
                            type: object
                            properties:
                                id: { index: true }
                                code: { index: true }
                                name:
                                    index: true
                                    type: text
                                    fields:
                                        source: { type: text, index: true }
                    persistence:
                        driver: orm # orm, mongodb, propel are available
                        model: App\Entity\User
                        provider: ~
                        listener: ~
                        finder: ~
```
