### ISSUE TITLE
Indexes suffixes

### ISSUE THREAD

**Issue by mpiot** [FriendsOfSymfony/FOSElasticaBundle#1858]
I would like to know if there is a way like Doctrine to have an `index_suffix` to use it with *Paratest* ?

```yaml
when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'
```
https://www.doctrine-project.org/projects/doctrine-bundle/en/2.4/configuration.html

**Comment by AndreyMashukov** [comment]
It is good idea, because now bundle designed like a piece of shit and no way to override or extend it

**Comment by mvhirsch** [comment]
I was thinking about a index_suffix for the same purpose, too.

> But this mean to duplicate all indexes.

Not necessarily. There is this concept of having index templates; where Elasticsearch is applying templates to it's indexes. One could add `index_templates` instead of indices and apply them automatically using "*" (wildcard). So something like this may work, but requires said `index_suffix` first:

```yaml
when@test:
    fos_elastica:
        index_suffix: '_%env(default::TEST_TOKEN)%' # <-- new
 
        indexes: 
            app_user:
                # ...

        index_templates:
            app_user:
                template: app_user_* # <-- requires manual work and must match index name + index_suffix (using wildcard) 
                types: 
                    # ...
```

I tried implementing this prior to my vacation, but failed to get it working to due (my) complex index templates. Downside on this approach is to get the actual index template running: I've note yet found a way to extract it easily which is done automatically in [`FOSElasticaExtension`](https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/src/DependencyInjection/FOSElasticaExtension.php). Any tips on how to proceed here @XWB @biozshock?
