### ISSUE TITLE
Service name aliases

### ISSUE THREAD

**Issue by stevelacey** [FriendsOfSymfony/FOSElasticaBundle#187]
Related to: https://github.com/Exercise/FOQElasticaBundle/issues/185

When using a parameter to set index names, the FOQ services are named differently based on that parameter, breaking any references to them that don't match.

I propose that the key in the config indexes array is used to create a service alias that can be referenced instead, that, or an addition property e.g. 'alias' or 'service_name'.

```
foq_elastica:
    clients:
        default:
            host: localhost
            port: 9200
    indexes:
        **my_index_service_alias_name**:
            name: %foq_elastica.index.name%
```
