### ISSUE TITLE
The clients url requires slash `/` at the end

### ISSUE THREAD

**Issue by Ferror** [FriendsOfSymfony/FOSElasticaBundle#1885]
## Scenario

The config below with the value `ELASTICSEARCH_URL=http://elasticsearch:9200` will result in the `Malformed URL` exception. But it will be valid for the `ELASTICSEARCH_URL=http://elasticsearch:9200/` value. It seems like a bad developer experience. Especially when other Symfony URLs do not require it.

```yaml
fos_elastica:
    clients:
            default:
                url: '%env(ELASTICSEARCH_URL)%'
```

## The expected behavior:

I can provide a URL with a slash or without at the end of the URL and both gonna be valid.
