### ISSUE TITLE
Support for Symfony/uid

### ISSUE THREAD

**Issue by BrentRobert** [FriendsOfSymfony/FOSElasticaBundle#1890]
I'm using uuid's as identifier for my model, however the ORM elastica to model transformer does not support this, as it can not resolve the objects with Doctrine.

**Comment by williarin** [comment]
Here's the solution. Part of it found [here](https://www.lukashron.cz/symfony-uuid-doctrine-a-elastic-search-bundle.html).

Step 1: create a new service `App\ElasticSearch\Transformer\ElasticaToModelTransformer`

```php
<?php

declare(strict_types=1);

namespace App\ElasticSearch\Transformer;

use FOS\ElasticaBundle\Doctrine\ORM\ElasticaToModelTransformer;
use Symfony\Component\Uid\Uuid;

final class ElasticaToUuidModelTransformer extends ElasticaToModelTransformer
{
    protected function findByIdentifiers(array $identifierValues, $hydrate): array
    {
        if (empty($identifierValues)) {
            return [];
        }

        $identifierValues = array_map(static fn($y) => Uuid::fromString($y)->toBinary(), $identifierValues);

        $qb = $this->getEntityQueryBuilder();
        $qb
            ->andWhere(
                $qb
                    ->expr()
                    ->in(BaseElasticaToModelTransformer::ENTITY_ALIAS . '.' . $this->options['identifier'], ':values')
            )
            ->setParameter('values', $identifierValues);

        $query = $qb->getQuery();

        foreach ($this->options['hints'] as $hint) {
            $query->setHint($hint['name'], $hint['value']);
        }

        return $query->execute();
    }
}
```

Step 2: add the service definition

```yaml
services:
	// ...
    elastica_to_model_transformer.my_entity:
        class: App\ElasticSearch\Transformer\ElasticaToUuidModelTransformer
        calls:
            - ['setPropertyAccessor', ["@fos_elastica.property_accessor"]]
        arguments:
            - '@doctrine'
            - 'App\Entity\MyEntity'
```

Step 3: override the `elastica_to_model_transformer` of your index

```yaml
fos_elastica:
    indexes:
        my_entity:
            persistence:
                elastica_to_model_transformer:
                    service: elastica_to_model_transformer.my_entity
```
