### ISSUE TITLE
IndexMissingException[[website] missing] 

### ISSUE THREAD

**Issue by jamhall** [FriendsOfSymfony/FOSElasticaBundle#19]
I have the error : IndexMissingException[[website] missing]

I have this in my config:

```
foq_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        website:
            client: default
            types:
                application:
                    mappings:
                        name: { boost: 5 }
                        description: { boost: 3 } 
                    doctrine:
                        driver: orm
                        model: HALL\TestBunde\Entity\Application
                        provider: 
                            query_builder_method: getAllQueryBuilder
                        finder:
```

I run the command:

`php app/console foq:elastica:populate`

The result I have is:

```
Reseting indexes
Setting mappings
Populating indexes
Indexing foq_elastica.provider.website.application, 100.0% (2/2), 9 objects/s
Done
```

In my controller I have:

```
        $finder   = $this->get('foq_elastica.finder.website.application');
        $messages = $finder->find('name:test', 10);
```

And the following error is thrown:et thrown the error:

```
IndexMissingException[[website] missing]
500 Internal Server Error - Elastica_Exception_Response 

```

Any ideas? Thanks! I've tried different versions of Elastica......same problem.
