### ISSUE TITLE
Searching the entire index

### ISSUE THREAD

**Issue by lypynskyi** [FriendsOfSymfony/FOSElasticaBundle#1916]
Hello!
I have an issue connected with searching the entire index from [docs](https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/usage.md#searching-the-entire-index)
I got the following error using DI in my service: `The service "fos_elastica.finder.app" has a dependency on a non-existent service "fos_elastica.elastica_to_model_transformer.app".`
PHP 8.2
Elastica 6.3.1
Elasticsearch 7.17.10

elastica.yaml:
```
fos_elastica:
    client:
        class: Elasticsearch\Client
    clients:
        default:
            host: '%elastica_host%'
            port: '%elastica_port%'
            transport: '%elastica_transport%'
    indexes:
        app:
            finder: ~
```

services.yaml:
```
App\Service\Search:
    public: true
    arguments:
      [ '@fos_elastica.finder.app']
```

and Search service:
```
class Search
{
      public function __construct(
              private PaginatedFinderInterface $finder,
          ) {}
}
```

What could be missing in my config or inside the service class?
