### ISSUE TITLE
Index even if i rollback transaction

### ISSUE THREAD

**Issue by Zarlokh** [FriendsOfSymfony/FOSElasticaBundle#1917]
Package Version : v6.2.0
PHP version : 8.2.5
doctrine/dbal version : 3.6.2
Symfony version : 5.4.22
Elastica conf :
```
fos_elastica:
    clients:
        default: { host: "%env(ELASTICSEARCH_HOST)%", port: '%env(ELASTICSEARCH_PORT)%' }
    indexes:
        bubbles:
            ...
        unavailabilities:
            ...
        orders:
            properties:
               ...
            persistence:
                driver: orm
                model: App\Entity\Order\Order
                listener:
                    defer: true
                provider:
                    query_builder_method: getQueryBuilderForElasticaPopulate
```
With this conf, if i run this code
```
        $entityManager->beginTransaction();
        $order = new Order();
        $order->setCode('test123456789');
        $entityManager->persist($order);
        $entityManager->flush();
        $entityManager->rollback();
```
My order is not create in my database but if i check my elasticsearch, i can find this order
![image](https://github.com/FriendsOfSymfony/FOSElasticaBundle/assets/16246455/5b5ecea0-664d-45ef-b229-895c2f7e344e)

Now, if i go to my order list page, i have an error because Elastica cannot find this order in my database
So, how can i index my entity only if a transaction is committed and not rollbacked ? (i see nothing about that in closed or opened issues and nothing about it in any site like stackoverflow. Did i miss something ?)

Thanks for helping
