### ISSUE TITLE
_parent mapping not being recognized

### ISSUE THREAD

**Issue by jmorgan74** [FriendsOfSymfony/FOSElasticaBundle#209]
Hi,

I seem to be having trouble getting the _parent mapping to configure from the config.yml.

I have the following config in the yml file:

```
foq_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        website:
            client: default
            types:
                fund:
                    mappings:
                         name:
                    persistence:
                        driver: orm
                        model: Morgz\Bundle\SiteBundle\Entity\Fund
                        provider:
                        listener:
                        finder:
                share:
                    mappings:
                        name:
                        price: { type: float }
                        fund: { _parent: { type: "fund", identifier: "id"  } }
                    persistence:
                        driver: orm
                        model: Morgz\Bundle\SiteBundle\Entity\Share
                        provider:
                        listener:
                        finder:
```

When I run the foq:elastica:populate command and check the resultant mapping using curl -XGET 'http://localhost:9200/website/_mapping?pretty=true' , I see the following:

```
{
  "website" : {
    "share" : {
      "properties" : {
        "fund" : {
          "type" : "string",
          "include_in_all" : true
        },
        "name" : {
          "type" : "string",
          "include_in_all" : true
        },
        "price" : {
          "type" : "float",
          "include_in_all" : true
        }
      }
    },
    "fund" : {
      "properties" : {
        "name" : {
          "type" : "string",
          "include_in_all" : true
        }
      }
    }
  }
```

It seems that fund has a type of string and there's no sign of the _parent mapping.

Cheers,

Jon.
