### ISSUE TITLE
Nesting of ManyToOne-association doesn't seem to work

### ISSUE THREAD

**Issue by daFish** [FriendsOfSymfony/FOSElasticaBundle#213]
I'm trying to add a nesting to a `ManyToOne`-association like this:

```
types:
    release:
        mappings:
            label:
                type: "nested"
                properties:
                    title:
```

The configuration of my entity:

```
/**
 * @var Label
 *
 * @ORM\ManyToOne(targetEntity="Fmdb\LabelBundle\Entity\Label")
 * @ORM\JoinColumn(name="label", referencedColumnName="id")
 */
private $label;
*/
```

I guess type `nested` is only supposed to work with `OneToOne` and `OneToMany` associations but I'm not sure how I should configure the definition to use it with a `ManyToOne` association. Did I miss something?
