### ISSUE TITLE
Enable field alias for nested objects

### ISSUE THREAD

**Issue by daFish** [FriendsOfSymfony/FOSElasticaBundle#217]
While testing the fix in #216 I thought of useful addition to the nesting support: Aliasing the fields from the nested object.

Proposing the following configuration to illustrate the problem:

```
alternates:
    type: "nested"
    properties:
        alternate: { analyzer: index_analyzer }
```

The nested field would be named `alternate`. In case the name doesn't make sense it would be great to be able to specify an alias like:

**Variant 1:**

```
alternates:
    type: "nested"
    properties:
        alternate: { analyzer: index_analyzer, alias: 'foo' }
```

The field would be indexed as `foo` instead of `alternate`.
**Variant 2:**

```
alternates:
    type: "nested"
    properties:
        alternate: { analyzer: index_analyzer, alias: '_parent' }
```

`_parent` would have a special meaning. The field would be indexed as `alternates` instead of `alternate` as it is the name of the association in the indexed type.

Any thoughts?
