### ISSUE TITLE
Wrong parameter given on finder constructor

### ISSUE THREAD

**Issue by herlambang** [FriendsOfSymfony/FOSElasticaBundle#221]
I followed all steps in README file
but when I tried to load the finder service

``` php
$this->get('foq_elastica.finder.website.product');
```

 got this instead

``` html
Catchable Fatal Error: Argument 1 passed to FOQ\ElasticaBundle\Finder\TransformedFinder::__construct() must be an instance of Elastica\Searchable, instance of Elastica\Type given, called in /myproject/app/cache/dev/appDevDebugProjectContainer.php on line 939 and defined in /myproject/vendor/bundles/FOQ/ElasticaBundle/Finder/TransformedFinder.php line 22
```

my configuration

``` yaml
foq_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        website:
            client: default
            types:
                product:
                    mappings:
                        title:
                        description:
                    persistence:
                        driver: orm
                        model: MyProject\MyBundle\Entity\Product
                        identifier: product_id
                        provider:
                            batch_size: 100
                        listener:
                            insert: false
                            update: false
                            delete: false
                        finder:
```

is there something wrong with my configuration?
