### ISSUE TITLE
Ability to set mapping field name separated from property path

### ISSUE THREAD

**Issue by vkartaviy** [FriendsOfSymfony/FOSElasticaBundle#228]
Now, to index referenced object I am using below mapping:

``` yml
mappings:
    name: { boost: 5 }
    reference.id: ~
    reference.name:
```

But that also create fields with the name "reference.id" and "reference.name" in ElasticSearch.

It would be great if will be possible to use mapping something like this:

``` yml
mappings:
    name: { boost: 5 }
    reference.id: { field_name: "reference_id" }
    reference.name: { field_name: "reference_name" }
```

or 

``` yml
mappings:
    name: { boost: 5 }
    reference_id: { property_path: "reference.id" }
    reference_name: { property_path: "reference.name" }
```
