### ISSUE TITLE
Parent mapping is not working

### ISSUE THREAD

**Issue by ruudk** [FriendsOfSymfony/FOSElasticaBundle#269]
I'm having troubles with storing parent id's. Everything is populated correctly on the ES server except the parent connection.

This is my config:

``` yaml
fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        website:
            client: default
            types:
                account:
                    mappings:
                        name: ~
                        alias: ~
                    persistence:
                        driver: orm
                        model: MyBundle\Entity\Account
                        provider: ~
                conversation:
                    mappings:
                        account: { _parent: { type: "account", identifier: "id" } }
                        name: ~
                        subject: ~
                    persistence:
                        driver: orm
                        model: MyBundle\Entity\Conversation
                        provider: ~
                        finder: ~
```

When I run `php app/console fos:elastica:populate -v` I get this:

```
Resetting website
Populating website/account, 100.0% (2/2), 21 objects/s
Populating website/conversation, 100.0% (2/2), 48 objects/s
Refreshing website
```

This is the mapping server on the server: `http://localhost:9200/_mapping?pretty=1`

``` json
{
  "website" : {
    "conversation" : {
      "properties" : {
        "account" : {
          "type" : "string",
          "include_in_all" : true
        },
        "name" : {
          "type" : "string",
          "include_in_all" : true
        },
        "subject" : {
          "type" : "string",
          "include_in_all" : true
        }
      }
    },
    "account" : {
      "properties" : {
        "alias" : {
          "type" : "string",
          "include_in_all" : true
        },
        "name" : {
          "type" : "string",
          "include_in_all" : true
        }
      }
    }
  }
}
```

As you can see, the `conversation` node doesn't have a parent declaration. It should be something like this:

``` json
....
"conversation" : {
  "_parent" : {
    "type" : "account"
  },
  "properties" : {
    "account" : {
      "type" : "string",
      "include_in_all" : true
    },
    "name" : {
      "type" : "string",
      "include_in_all" : true
    },
    "subject" : {
      "type" : "string",
      "include_in_all" : true
    }
  }
}
....
```

Any ideas?
