### ISSUE TITLE
Index-wide finder does not load transformers

### ISSUE THREAD

**Issue by Tatsh** [FriendsOfSymfony/FOSElasticaBundle#270]
I am getting an error when attempting to use the index-wide finder because the argument passed into the constructor for `ElasticaToModelTransformerCollection` is always an empty array.

I am using a service for each provider. Also I have a compiler pass that replaces each object persister with my own version (although I cannot see how this would conflict).

Am I missing in something in my configuration? Does the provider service need to do something special?

Configuration:

``` yaml
fos_elastica:
    clients:
        default:
            host: %elastica_host%
            port: 9200
    indexes:
        acme:
            client: default
            finder: ~
            types:
                article:
                    mappings:
                        native_id:
                            type: integer
                        image_url:
                            null_value: ''
                        image_thumbnail_url:
                            null_value: ''
                        title:
                            boost: 5
                            null_value: ''
                        deck:
                            null_value: ''
                        date_updated:
                            type: date
                        date_created:
                            type: date
                        date_published:
                            type: date
                        url: ~
                        cms_url: ~
                        publishable:
                            type: boolean
                            null_value: true
                    persistence:
                        driver: orm
                        model: Acme\ArticleBundle\Entity\Article
                        provider:
                            service: acme.search.article_provider
```

In `FOSElasticaExtension#loadIndexFinder()`, I see that the first argument to the collection transformer never changes:

``` php
        $abstractTransformerId = 'fos_elastica.elastica_to_model_transformer.collection.prototype';
        $transformerId = sprintf('fos_elastica.elastica_to_model_transformer.collection.%s', $name);
        $transformerDef = new DefinitionDecorator($abstractTransformerId);
        $container->setDefinition($transformerId, $transformerDef);
```
