### ISSUE TITLE
Repository does not exist.

### ISSUE THREAD

**Issue by beckyta** [FriendsOfSymfony/FOSElasticaBundle#278]
Hi everybody !

Thank for built this bundle.
I have an error when I execute my website : *_FrontEnd\AplicacionBundle\Repository\OaRepository repository for FrontEnd\AplicacionBundle\Entity\Oa does not exist . *_ 

I need to know where this error does it come from please ?

_app//config/config.yml_

```
fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        website:
            client: default
            types:
                 manager:
                     mappings:
                         id: { boost: 3 }
                         nombreoa:   { analyzer: snowball }
                         titulo: {boost: 3}
                         duracion: {boost: 3}
                         uniduracion: {boost: 3}
                         email: {boost: 3}
                         caracteristicas: { analyzer: snowball }
                         requisitos: ~
                         planestudio: ~
                         matricula: {boost: 3}
                         cuota: {boost: 3}
                         dirigidoa: {boost: 3}
                         url: {boost: 3}
                         idareaestudio:
                            type: "nested"
                            properties:
                                nombre: { boost: 5 }
                         idcategoria:
                            type: "nested"
                            properties:
                                nombre: { boost: 5 }
                         idinstitucion:
                            type: "nested"
                            properties:
                                nombreinstitucion: { boost: 5 }      
                                nombresede: { boost: 5 }
                         idmodalidadoa:
                            type: "nested"
                            properties:
                                nombre: { boost: 5 }  
                         idniveloa:
                            type: "nested"
                            properties:
                                nombre: { boost: 5 } 
                         idtipooa:
                            type: "nested"
                            properties:
                                nombre: { boost: 5 }                   
                     persistence:
                        driver: orm
                        model: FrontEnd\AplicacionBundle\Entity\Oa
                        repository:  FrontEnd\AplicacionBundle\Repository\OaRepository
                        provider: ~                     
                        listener:
                        finder: ~
```

_src\FrontEnd\AplicacionBundle\Entity\Oa.php_

```
<?php
namespace FrontEnd\AplicacionBundle\Entity;
use Doctrine\ORM\Mapping as ORM;
use FOS\ElasticaBundle\Configuration\Search;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
/**
 * FrontEnd\AplicacionBundle\Entity\Oa
 *
 * @ORM\Table(name="oa")
 * @ORM\Entity
 * @ORM\HasLifecycleCallbacks()
 * @Search(repositoryClass="FrontEnd\AplicacionBundle\Repository\OaRepository")
 */
class Oa
{
    /**
     * @var integer $idoa
     *
     * @ORM\Column(name="idOA", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @var string $nombreoa
     *
     * @ORM\Column(name="NombreOA", type="string", length=200, nullable=true)
     */
    private $nombreoa;
.......................................................................................................................  
    /**
     * @var Areaestudio
     *
     * @ORM\ManyToOne(targetEntity="Areaestudio")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="idAreaEstudio", referencedColumnName="idAreaEstudio")
     * })
     */
    private $idareaestudio;
...................................................................................................................    

/**
 * Get idoa
 *
 * @return integer 
 */
public function getIdoa()
{
    return $this->id;
}
public function getId()
{
    return $this->id;
}

/**
 * Set nombreoa
 *
 * @param string $nombreoa
 */
public function setNombreoa($nombreoa)
{
    $this->nombreoa = $nombreoa;
}

/**
 * Get nombreoa
 *
 * @return string 
 */
public function getNombreoa()
{
    return $this->nombreoa;
}
......................................................................................    
}
```

_\src\FrontEnd\AplicacionBundle\Repository\OaRepository_

```
<?php

namespace FrontEnd\AplicacionBundle\Repository;

use FOS\ElasticaBundle\Repository;

class OaRepository extends Repository
{

    public function findByTexto($searchTerm)
    {
        $nameQuery = new \Elastica_Query_Text();
        $nameQuery->setFieldQuery('nombreoa', $searchTerm);
        $nameQuery->setFieldParam('nombreoa', 'analyzer', 'snowball');

        $keywordsQuery = new \Elastica_Query_Text();
        $keywordsQuery->setFieldQuery('caracteristicas', $searchTerm);
        $keywordsQuery->setFieldParam('caracteristicas', 'analyzer', 'snowball');

        $boolQuery = new \Elastica_Query_Bool();
        $boolQuery->addShould($nameQuery);
        $boolQuery->addShould($keywordsQuery);

        return $this->find($boolQuery);
    } 
}
```

_src\FrontEnd\AplicacionBundle\Controller\BuscadorController.php_

```
<?php

namespace FrontEnd\AplicacionBundle\Controller;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use FrontEnd\AplicacionBundle\Entity\Oa;
use FrontEnd\AplicacionBundle\Form\BuscadorType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use FOS\ElasticaBundle\Finder\TransformedFinder;
use FOS\ElasticaBundle\Manager\RepositoryManager;
use FOS\ElasticaBundle\Repository;
use Doctrine\ORM\EntityManager;
use FOS\ElasticaBundle\Configuration\Search;

class BuscadorController extends Controller
{
    public function searchAction()
{
                        // TESTING
                            $repositoryManager = $this->get('fos_elastica.manager');
                            $repository = $repositoryManager->getRepository('FrontEndAplicacionBundle:Oa');
                        $oas = $repository->findByTexto('bob');
                            return array('oas' => $oas);                    
 }
}
```

Help me, please.            

Thank you for all !
