### ISSUE TITLE
Filtered Nested.

### ISSUE THREAD

**Issue by beckyta** [FriendsOfSymfony/FOSElasticaBundle#289]
Hi everybody !
I try to do this, i get error. What am i doing wrong?

```
        $nameQuery = new \Elastica_Query_Text();
        $nameQuery->setFieldQuery('nombreoa', $searchTerm);
        $nameQuery->setFieldParam('nombreoa', 'type', 'phrase_prefix');

        $tipoQuery = new \Elastica_Query_Text();
        $tipoQuery->setFieldQuery('titulo', $searchTerm);
        $tipoQuery->setFieldParam('titulo', 'type', 'phrase_prefix');

        $duraQuery = new \Elastica_Query_Text();
        $duraQuery->setFieldQuery('duracion', $searchTerm);
        $duraQuery->setFieldParam('duracion', 'type', 'phrase_prefix');

        $uniduraQuery = new \Elastica_Query_Text();
        $uniduraQuery->setFieldQuery('uniduracion', $searchTerm);
        $uniduraQuery->setFieldParam('uniduracion', 'type', 'phrase_prefix');

        $emailQuery = new \Elastica_Query_Text();
        $emailQuery->setFieldQuery('email', $searchTerm);
        $emailQuery->setFieldParam('email', 'type', 'phrase_prefix');

        $estadoQuery = new \Elastica_Query_Text();
        $estadoQuery->setFieldQuery('estado', 'V');
        $estadoQuery->setFieldParam('estado', 'type', 'phrase_prefix');

        $caractQuery = new \Elastica_Query_Text();
        $caractQuery->setFieldQuery('caracteristicas', $searchTerm);
        $caractQuery->setFieldParam('caracteristicas', 'type', 'phrase_prefix');

        $requiQuery = new \Elastica_Query_Text();
        $requiQuery->setFieldQuery('requisitos', $searchTerm);
        $requiQuery->setFieldParam('requisitos', 'type', 'phrase_prefix');

        $planQuery = new \Elastica_Query_Text();
        $planQuery->setFieldQuery('planestudio', $searchTerm);
        $planQuery->setFieldParam('planestudio', 'type', 'phrase_prefix');

        $matriQuery = new \Elastica_Query_Text();
        $matriQuery->setFieldQuery('matricula', $searchTerm);
        $matriQuery->setFieldParam('matricula', 'type', 'phrase_prefix');

        $cuoQuery = new \Elastica_Query_Text();
        $cuoQuery->setFieldQuery('cuota', $searchTerm);
        $cuoQuery->setFieldParam('cuota', 'type', 'phrase_prefix');

        $diriQuery = new \Elastica_Query_Text();
        $diriQuery->setFieldQuery('dirigidoa', $searchTerm);
        $diriQuery->setFieldParam('dirigidoa', 'type', 'phrase_prefix');

        $urlQuery = new \Elastica_Query_Text();
        $urlQuery->setFieldQuery('url', $searchTerm);
        $urlQuery->setFieldParam('url', 'type', 'phrase_prefix');

        $boolQuery = new \Elastica_Query_Bool();
        $boolQuery->addShould($nameQuery);
        $boolQuery->addShould($tipoQuery);
        $boolQuery->addShould($duraQuery);
        $boolQuery->addShould($uniduraQuery);
        $boolQuery->addShould($emailQuery);
        $boolQuery->addShould($estadoQuery);
        $boolQuery->addShould($caractQuery);
        $boolQuery->addShould($requiQuery);
        $boolQuery->addShould($planQuery);
        $boolQuery->addShould($matriQuery);
        $boolQuery->addShould($cuoQuery);
        $boolQuery->addShould($diriQuery);
        $boolQuery->addShould($urlQuery);


            $tipo_filter_nested = new  \Elastica_Filter_Nested();
            $tipo_filter_nested->setPath('idtipooa');
            $tipo_filter_nested->setParam('nombre', $tipo);
            $tipo_filter_nested->setQuery($nameQuery);


        $filtro_completo=new \Elastica_Query_Filtered($boolQuery, $tipo_filter_nested);
        $results= $this->find($filtro_completo);
```

_app//config/config.yml_

```
fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        website:
            client: default
            types:
                 ofertas:
                     mappings:
                         id: { boost: 3 }
                         nombreoa: { analyzer: standard }
                         titulo:  { analyzer: standard }
                         duracion: { analyzer: standard }
                         uniduracion: { analyzer: standard }
                         email: { analyzer: standard }
                         caracteristicas: { analyzer: standard }
                         requisitos: { analyzer: standard }
                         planestudio: { analyzer: standard }
                         matricula: { analyzer: standard }
                         cuota: { analyzer: standard }
                         dirigidoa: { analyzer: standard }
                         url: { analyzer: standard }
                         estado: { boost: 3 }
                         idareaestudio:
                            type: "nested"
                            properties:
                                nombre: { type: string, index: not_analyzed }
                         idcategoria:
                            type: "nested"
                            properties:
                                nombre: { type: string, index: not_analyzed }
                         idinstitucion:
                            type: "nested"
                            properties:
                                nombreinstitucion: { type: string, index: not_analyzed }  
                                nombresede: { type: string, index: not_analyzed }
                                idprovincia: 
                                    type: "nested"
                                    properties:
                                        nombre: { type: string, index: not_analyzed }
                                idlocalidad: 
                                    type: "nested"
                                    properties:
                                        nombre: { type: string, index: not_analyzed     }                                  
                         idmodalidadoa:
                            type: "nested"
                            properties:
                                nombre: { type: string, index: not_analyzed }
                         idniveloa:
                            type: "nested"
                            properties:
                                nombre: { type: string, index: not_analyzed }
                         idtipooa:
                            type: "nested"
                            properties:
                                nombre: { type: string, index: not_analyzed }               
                     persistence:
                        driver: orm
                        model: FrontEnd\AplicacionBundle\Entity\Oa
                        provider: ~
                        finder: ~
                        repository: FrontEnd\AplicacionBundle\Repository\OaRepository
```

I want to get this query:

```
'{
"query": {
    "filtered": {
        "query": {
            "match_all": {}
        },
        "filter": {
            "nested": {
                "path": "idtipooa",
                    "query": {
                        "bool": {
                            "must": [{
                                "match": {
                                "idtipooa.nombre": "Carrera Universitaria"
                                }
                            }]
                        }
                    },
                "_cache": true
             }
          }
       }
   }
}'
```
