### ISSUE TITLE
add support for inheriting parent index definitions

### ISSUE THREAD

**Issue by lsmith77** [FriendsOfSymfony/FOSElasticaBundle#291]
we frequently need to define duplicate index definitions for the test environment that only get a different name. it would be great to have native support for this. maybe it should be possible to define a "parent_index" and then it would copy everything from there and only overwrite any duplicate settings (like f.e. the index_name).

```
# config.yml
fos_elastica:
    indexes:
        de:
            index_name: de
            types: ..
```

```
# config_test.yml
fos_elastica:
    indexes:
        de:
            index_name: de_test
            parent_index: de
```
