### ISSUE TITLE
 getRepository() on a non-object

### ISSUE THREAD

**Issue by fertandil87** [FriendsOfSymfony/FOSElasticaBundle#294]
php app/console fos:elastica:populate --env=prod

Resetting golocal
PHP Fatal error:  Call to a member function getRepository() on a non-object in /home/fer/www/elastic/vendor/friendsofsymfony/elastica-bundle/FOS/ElasticaBundle/Doctrine/ORM/Provider.php on line 57

If I remove "-env=prod" works fine. I want to try in env=prod because I have a table in Mongodb of 14 millons and I am getting an error of memory when arround 1 millon were indexed. 
I used clear cache and removed it too but nothing works

My config:

```
fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        myindex:
            client: default
            types:
                business:
                    mappings:
                        busTitle: { boost: 4 }
                    persistence:
                        driver: orm
                        model: Acme\DemoBundle\Entity\GlmBussiness
                        identifier: bus_id
                        provider: ~
```
