### ISSUE TITLE
ignore_missing option in type_prototype section dosn't applied to corresponding types

### ISSUE THREAD

**Issue by vkartaviy** [FriendsOfSymfony/FOSElasticaBundle#299]
Type prototype configuration:

``` yml
type_prototype:
    persistence:
        elastica_to_model_transformer:
            ignore_missing: true
```

Corresponding type configuration:

``` yml
types:
    item:
        mappings:
            name:           { boost: 5 }
            description:    { boost: 3 }
        persistence:
            model: ItemDocument
```
