### ISSUE TITLE
Error with Argument passed to ElasticaToModelTransformer...

### ISSUE THREAD

**Issue by rayrigam** [FriendsOfSymfony/FOSElasticaBundle#337]
I just integrated FOSElasticaBundle into my app and I'm getting this error:

> Catchable Fatal Error: Argument 1 passed to FOS\ElasticaBundle\Propel\ElasticaToModelTransformer::FOS\ElasticaBundle\Propel{closure}() must be an instance of Elastica\Document, instance of Elastica\Result given in ...path_to_my_app/vendor/friendsofsymfony/elastica-bundle/FOS/ElasticaBundle/Propel/ElasticaToModelTransformer.php line 74

with these php lines (using the Finder Service):

``` php
$finder = $this->container->get('fos_elastica.finder.website.user');
$users = $finder->find('bob');
```

On the other hand, if I use the search method on the Index Service, as follows, I correctly get the search results:

``` php
$userType = $this->container->get('fos_elastica.index.website.user');
$resultSet = $userType->search('bob');
```

I'm using the config shown bellow with a propel driver and would like to use the Finder to get the Propel objects along with the results. **Am I doing something wrong with the setup or is this a bug?**

``` yaml
fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        website:
            client: default
            types:
                user:
                    mappings:
                        username: { boost: 5 }
                        name: { boost: 2 }
                    persistence:
                        driver: propel
                        model: Acme\UserBundle\Model\User
                        provider: ~
                        finder: ~
```
