### ISSUE TITLE
Time To Live option is not supported?

### ISSUE THREAD

**Issue by Sydney-o9** [FriendsOfSymfony/FOSElasticaBundle#340]
Is there a way to set up the time to live option `_ttl` in FOSElasticaBundle?

Time To Live is supported by ElasticSearch  [as stated in the doc](http://www.elasticsearch.org/guide/reference/mapping/ttl-field/) :

I am trying to do this:

``` bash
curl -XPUT 'http://localhost:9200/website/' -d '{
    "mappings" : {
        "article" : {
           "_ttl" : { "enabled" : true},
           "properties": {
              "title": {
                  "include_in_all": true,
                  "analyzer": "snowball",
                  "boost": 5,
                  "type": "string"
                }
            }
        }
    }
}
'
```

Out of curiosity, I have tried the following:

``` yml
foq_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        website:
            client: default
            types:
                article:
                    _ttl: { enabled: true}
                    mappings:
                        title: { type: string, analyzer: snowball, boost: 5}

```

So I get the following error:

```
Unrecognized options "_ttl" under "foq_elastica.indexes.website.types.article"
```

I think it would be a good idea to add a `mapping_options` key for each type to allow something like this:

``` yml
foq_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        website:
            client: default
            types:
                article:
                    mapping_options:
                        _ttl: { enabled: true}
                    mappings:
                        title: { type: string, analyzer: snowball, boost: 5}

```

This would also allow us to support `_timestamp`, `_size`, etc..

``` yml
types:
    article:
        mapping_options:
            _ttl: { enabled: true, default: 10s}
            _timestamp: { enabled: true } 
            _size: { enabled: true }                 
```

Any ideas?
