### ISSUE TITLE
FOSElasticaBundle : impossible to find results

### ISSUE THREAD

**Issue by GBCVisible** [FriendsOfSymfony/FOSElasticaBundle#346]
Hi,

My problem is the implementation of a search engine job with ElasticaSearch.

I use FOSElasticaBundle 3.0.\* with Symfony 2.3.2
My Config : 

```
#\app\config\config.yml

#Config Elasticsearch
fos_elastica:
    clients:
        default: { host: localhost, port: 8080 }
    indexes:
        website:
            client: default
            types:
                Job:
                    mappings:
                        Title: { boost: 5 }
                        Location: { type: geo_point, boost: 3, lat_lon: true }
                    persistence:
                        driver: orm # Le mode de stockage des données à indexer  (orm, mongodb, propel)
                        model: Xxxx\YyyyBundle\Entity\Job # L'entité sur laquelle porte le mapping défini ci-dessus
                        provider: ~
                        finder: ~ # Indique que l'on va utiliser un finder (voir la doc officielle pour plus d'infos)
                        listener:  # Indique que l'on va utiliser un listener sur l'entité pour la MàJ de l'index
```

My Controller : 

```
public function SearchAction()
{

//Récupération du formulaire/*
$SearchJob_entity = new SearchJob();
    $SearchJob_form = $this->createForm(new SearchJobType(), $SearchJob_entity);
    $request = $this->getRequest();
    $SearchJob_form->handleRequest($request);

    $Job = $SearchJob_form['JobSearch']->getData();
    $Where = $SearchJob_form['WhereSearch']->getData();

    $StringSearch = $Job . " / " . $Where;


//Job
    $finder = $this->container->get('fos_elastica.finder.website.job');

    $Data = $finder->find($Job);

    $StringSearch = $Job . " / " . $Where . " / " . var_dump($Data);


    return $this->render('CViJobBundle::JobResult.html.twig', array(
                'StringSearch'      => $StringSearch,
                ));
}
```

The command  "php app/console fos:elastica:populate" it's OK.

But, don't find results, even one that matches exactly one title in this BDD.

One  idea ?

Thanhs
