### ISSUE TITLE
json_encode() : Invalid UTF-8 sequence

### ISSUE THREAD

**Issue by hugoruggieri** [FriendsOfSymfony/FOSElasticaBundle#354]
Hey!

I'm going to have a nervous breakdown with this...

So I got elasticsearch, Elastica and FOSElasticaBundle up and running, configured as follows:

```
fos_elastica:
clients:
    default: { host: localhost, port: 9200 }
serializer: ~
indexes:
    website:
        client: default
        finder: ~
        settings:
            index:
                analysis:
                    analyzer:
                        default:
                            language: French
                            type: snowball
                            tokenizer: lowercase
                            filter: [my_ngram, my_filter]
                    filter:
                        my_ngram:
                            type: "nGram"
                            min_gram: 3
                            max_gram: 5
                        my_filter:
                            type: "length"
                            min: 0
                            max: 2000
        types:
            user:
                mappings:
                    username: { boost: 5 }
                    prenom: { boost: 3 }
                    nom: { boost: 3 }
                persistence:
                    driver: orm
                    model: Me\UserBundle\Entity\User
                    provider: ~
                    listener: # by default, listens to "insert", "update" and "delete"
                    finder: ~
```

and I'm desperately trying to get my research to work for accents, as I'm French and French language extensively uses accents.
So I want my research to give the same results for "été" and "ete", and also for "TRIP" and "TRIPs". I can't seem to be able to make it work however. With this configuration, searching on my site only gives results for the exact match (TRIPs has a result but not TRIP) and no matches for accents. When I try searching with command line, this is what I get:

```
C:\wamp\www\pearexchange.fr>php app/console fos:elastica:search website-user éva




   [Symfony\Component\Debug\Exception\ContextErrorException]
  Warning: json_encode(): Invalid UTF-8 sequence in argument in C:\wamp\www\pearexchange.fr\vendor\monolog\monolog\src\Monolog\Formatter\NormalizerFormatter.php line 132



 fos:elastica:search [--index="..."] [--limit="..."] [--show-field="..."] [--show
 -source] [--show-id] [--explain] type query
```

I have a user called Eva, and I'm trying to search for "éva" to find that User, but this is the error.

Oh and also, weird thing, doing this:

```
php app/console fos:elastica:search website eva
Found 0 results
```

Whilst searching on the website brings back my user, as planned.
I also tried with type: french in my config, instead of this custom type.

This is my controller code:

```
        $utilisateurs = $this->container->get('fos_elastica.finder.website.user');
        $recherche = $_GET['recherche'];
        $hybridUtilisateurs = $utilisateurs->find($recherche);
```
