### ISSUE TITLE
Mapping Attachments

### ISSUE THREAD

**Issue by RobertPlant** [FriendsOfSymfony/FOSElasticaBundle#356]
Hello,

I am having issues with indexing attachments, I've installed the plugin from elasticsearch, the mapper-attachment-plugin. When trying to index the files I get this error;

```
[Elastica\Exception\ResponseException]                                                                                           
  MapperParsingException[mapping [attachment]]; nested: ClassCastException[java.util.ArrayList cannot be cast to java.util.Map];   
```

The configuration that i've used for mapping the files are;

``` yml
# Elastic Search Configuration
fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        documents :
            types:
                attachment:
                    mappings:
                        _contentType: ~
                        _name: ~
                        content:
                            type: attachment
                    persistence:
                        driver: orm
                        model: Entity\Document
                        provider: ~
                        finder: ~
                        listener: ~
```

The Entity code to return the information

``` php
    public function get_contentType()
    {
        $pathInfo = pathinfo($this->getFileName());
        $symfonyFile = new File($this->getPath() . '/' . $pathInfo['filename'] . $this->getRevision() . '.' . $pathInfo['extension']);
        return $symfonyFile->getMimeType();
    }

    public function get_name()
    {
        return $this->fileName;
    }

    public function getContent()
    {
        return base64_encode(file_get_contents($this->path . '/' . $this->fileName, 'r'));
    }
```

I've looked at this issue https://github.com/FriendsOfSymfony/FOSElasticaBundle/issues/96 and the associated issues that link off from it. 

I can't see where i'm going wrong any help would be greatly appreciated.
