### ISSUE TITLE
Can't find by nested document

### ISSUE THREAD

**Issue by spolischook** [FriendsOfSymfony/FOSElasticaBundle#362]
I config index like:

``` yml
recipe:
    mappings:
        title: { boost: 50 }
        categories:
            type : "nested"
            properties:
                name: { boost: 7 }
```

I create query like that:

``` php
$boolQuery = new Bool();

$nested = new Nested();
$nested->setQuery(new Field('name', $category));
$nested->setPath('categories');
$boolQuery->addMust($nested);
```

But when query has been executed I have received zero in result.
Maybe I forgot something?
