### ISSUE TITLE
Getting exception while fos:elastica:populate

### ISSUE THREAD

**Issue by kiserbd** [FriendsOfSymfony/FOSElasticaBundle#369]
Hi,

Here is my config for fos_elastica

```
fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    serializer:
        callback_class: FOS\ElasticaBundle\Serializer\Callback
        serializer: serializer
    indexes:
        geos:
            client: default
            index_name: geos
        listings:
            client: default
            index_name: listings_v_0_1_1
            types:
                listing:
```

So after run the populate command(php app/console fos:elastica:populate) i'm getting the following exception:

```
[Elastica\Exception\ResponseException]                                   
  ClassCastException[java.util.ArrayList cannot be cast to java.util.Map]
```

Please help if anybody know  what's wrong i'm doing here.

Thanks
Abdullah
