### ISSUE TITLE
Completion suggester mapping fails due to include_in_all

### ISSUE THREAD

**Issue by wlzch** [FriendsOfSymfony/FOSElasticaBundle#380]
I am trying [completion suggester](http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/search-suggesters-completion.html) on my application using this mapping

``` yaml
user:
     mappings:
         username: { boost: 5 }
         realname: { boost: 4 }
         suggestions: { type: completion}
```

but elasticsearch throws MapperParsingException[Unknown field [include_in_all]] when I ran `fos:elastica:reset` or `fos:elastica:populate`.

As you can see in the doc, completion type does not accept include_in_all option. I think that is what causes the commands to fail. Is there any reason why include_in_all is defined as `->booleanNode('include_in_all')->defaultValue(true)->end()`?

**Comment by DjangoFR** [comment]
Defining mapping like suggested above by @wlzch causes for me the following error:

```php
    [Symfony\Component\PropertyAccess\Exception\NoSuchPropertyException]                                                                                                                                            
    Neither the property "suggestions" nor one of the methods "getSuggestions()", "suggestions()", "isSuggestions()", "hasSuggestions()", "__get()" exist and have public access in class "AcmeBundle\Entity\MyEntity".
```
composer show -i:
friendsofsymfony/elastica-bundle         dev-master 88e9f5a

**Comment by lucasgranberg** [comment]
I have defined this method in my entity. I can get int to index correctly and I can do _suggest queries directly to elasticsearch. Still have to figure out how it works with elastica.

Entity:
```php
    public function getSuggest(){
        return array(
            'input' => $this->getName(),
            'output' => $this->getName(),
            'payload' => array(
                'id' => $this->getId(),
                'type'=>'category'
            )
        );
    }
```
Mapping:
```yaml
suggest:
    type: completion
    index_analyzer: simple
    search_analyzer: simple
    payloads: true
```
