### ISSUE TITLE
How to manually update a index?

### ISSUE THREAD

**Issue by devgogo** [FriendsOfSymfony/FOSElasticaBundle#385]
i have a Post entity, when a user view a post, i  will call $post->incrementViews(1),
but will trigger  elasticsearch update $post object
I think this is unnecessary.

so setting:

```
 listener:
     insert: true
     update: false
     delete: true
```

but, when user change after post, i need update elasticsearch index.

what can i do?

thx.
