### ISSUE TITLE
Issues using the finder (Doctrine persistence)

### ISSUE THREAD

**Issue by bobvandevijver** [FriendsOfSymfony/FOSElasticaBundle#387]
Hi, 

I've got a issue with the finder component of this bundle. Whenever I try to find a person object from my database using the standard finder: 

``` yaml
fos_elastica:
  clients:
    default: { host: localhost, port: 9200 }
  serializer:
    callback_class: FOS\ElasticaBundle\Serializer\Callback
    serializer: serializer
  indexes:
    idb:
      client: default
      types:
        person:
          mappings:
            fullname: ~
            studentnumber: ~
          persistence:
            driver: orm
            model: Idb\PersonBundle\Entity\Person
            provider: ~
            listener: ~
            finder: ~
```

Doctrine uses to much memory `PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 87 bytes) in /var/www/dev/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php on line 2557`This does not happen when populating the index (for now only 22k objects). 

As I've read this could be caused by circular referencing (which probably happens, as I've got a Person -> OrganisationPerson -> Organisation structure, and others), I've disabled the hydrate option:

``` yaml
fos_elastica:
  indexes:
    idb:
      types:
        person:
          persistence:
            elastica_to_model_transformer:
              hydrate: false
```

However, then the following error is generated: 
`Cannot read property "id" from an array. Maybe you should write the property path as "[id]" instead?[{/var/www/dev/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php at line 198]`
as wel as 
`PHP Warning:  usort(): Array was modified by the user comparison function in /var/www/dev/vendor/friendsofsymfony/elastica-bundle/FOS/ElasticaBundle/Doctrine/AbstractElasticaToModelTransformer.php on line 115` 
in the server log. 

When I comment out the sort rules (lines 112-115) in AbstractElasticaToModelTransformer in the Doctrine dir, I do get the results, but the result part en the transformer part are not aligned with each other. 

My controller: 

``` php
public function searchAction()
  {
    $request = $this->getRequest();
    $searchKey = $request->request->get('key');
    $limit = (int)$request->request->get('limit', 25);
    if($limit > 100){
      $limit = 100;
    }

    $finder = $this->get('fos_elastica.finder.idb.person');

    $objects = $finder->findHybrid($searchKey, $limit);
    $serializer = $this->get('serializer');
    $results = $serializer->serialize($objects, 'json');

    $response = new Response($results);
    $response->headers->set('Content-Type', 'application/json');
    return $response;
  }
```

I would really like to use the Doctrine Hydrate function (other finder actions in the future will use those objects), and as the not hydrate option also fails, it is not really an option...

Has anyone an idea on what to do, or better, any solution?
