### ISSUE TITLE
Notice: Undefined index: product

### ISSUE THREAD

**Issue by justinhilles** [FriendsOfSymfony/FOSElasticaBundle#393]
I am trying to search over all indexes and i had it working a couple days ago but now its coming up with this error.  I have tried repopulating the index and still the same

```
fos_elastica:
    clients:
        default: { host: 10.0.0.200, port: 9200 }
    serializer: ~
    indexes:
        website:
            client: default
            finder: ~
            types:
                product:
                    mappings:
                        name: ~
                        description: ~
                    persistence:
                        driver: orm
                        model: Sylius\Bundle\CoreBundle\Model\Product
                        provider: ~
                        listener: ~
                taxon:
                    mappings:
                        name: ~
                        description: ~
                    persistence:
                        driver: orm
                        model: Sylius\Bundle\CoreBundle\Model\Taxon
                        provider: ~
                        listener: ~
```

Did something change that is not reflected yet in documentation?

Thanks for any help or guidance
