### ISSUE TITLE
Use same mapping configuration as ES itself

### ISSUE THREAD

**Issue by Tobion** [FriendsOfSymfony/FOSElasticaBundle#407]
Why does the bundle have a different mapping structure than ES uses itself? This is quite unexpected and not useful.

So the config `fos_elastica.index.<index>.types` should be renamed `fos_elastica.index.<index>.mappings` and `fos_elastica.index.<indexes>.types.<type>.mappings` should be `fos_elastica.index.<indexes>.mappings.<type>.properties`. This makes the config much more consistent with ES API.
Also it was quite strange that the properties are placed under "mappings" in the top level, but sub-object mappings must still use "properties again".

For example the old way

``` yaml
fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        de:
            client: default
            settings:
                index:
                    number_of_replicas: 0
            types:
                category:
                    _id : { path: code }
                    mappings:
                        code:        { type: string }
                        children:
                            type: object
                            properties:
                                code: { type: string }
```

should be new

``` yaml
fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        de:
            client: default
            settings:
                index:
                    number_of_replicas: 0
            mappings:
                category:
                    _id : { path: code }
                    properties:
                        code:        { type: string }
                        children:
                            type: object
                            properties:
                                code: { type: string }
```
