### ISSUE TITLE
Parent-Child relationship with mapping serialization

### ISSUE THREAD

**Issue by malberts** [FriendsOfSymfony/FOSElasticaBundle#428]
I'm having trouble getting a parent-child relationship working when both entities are serialized with JMSSerializer. I'm not 100% sure, but I think issue might be related to https://github.com/FriendsOfSymfony/FOSElasticaBundle/pull/413

Before that I defined all my mappings in the config file. For example:

```
fos_elastica:
    indexes:
        website:
            types:
                rfq:
                    mappings:
                        # all the fields here
                    persistence:
                        # ...
                quote:
                    _parent: { type: rfq, property: rfq }
                    mappings:
                        # all the fields here
                    persistence:
                        # ...
```

Now I moved the mappings out to the serializer config files. In both the RFQ and Quote serializer files I indicated that all properties should be excluded by default. I didn't specify that the RFQ property on the Quote should be included.

When I run the populate command I get:

```
[Elastica\Exception\ResponseException]                                  
  RoutingMissingException[routing is required for [website]/[quote]/[1]]
```

The only way I could get past that was to create separate serialization groups for both entities:

```
            types:
                rfq:
                    serializer:
                        groups: [ rfq_index ]

                quote:
                    serializer:
                        groups: [ quote_index ]
                    _routing:
                        path: rfq.id
                    _parent: { type: rfq, property: rfq, identifier: id }
```

Then in the RFQ serialization config I made it serialize the id only as part of the 'quote_index' group. In the Quote serialization config I added the RFQ property. 

Now it indexes, but I am not sure if this is a proper way to achieve a parent-child relationship while serializing.
Does anyone perhaps have a working example?
