### ISSUE TITLE
Set analyzer to "_all" field

### ISSUE THREAD

**Issue by kayue** [FriendsOfSymfony/FOSElasticaBundle#438]
Hi all

I want to change `_all` field's analyzer to snowball but looks like it is not being added to mapping:

```
        types:
            product:
                mappings:
                    _all:
                        analyzer: snowball
```

May I know is this something doable via this bundle? 

Thanks
