### ISSUE TITLE
Exclude DB fields from indexes

### ISSUE THREAD

**Issue by ghost** [FriendsOfSymfony/FOSElasticaBundle#442]
Hi, 

Probably a dumb question, but I'm trying to exclude certain fields from my index(es) and I don't know how to do it. 

I tried : 

```
<table_name>
    mappings:
        firstname: { boost: 5 }
        lastname: ~
        email: { index: not_analyzed }
```

The name and the logic behind those statements aren't relevant, I just want Elastica not to look into the 'email' field of my SQL DB when creating its indexes.

Can you help me? Am I missing something?

Thanks!
