### ISSUE TITLE
Populate command getting wrong entity for index type (only at the end of the index population - 95% complete)

### ISSUE THREAD

**Issue by tec4** [FriendsOfSymfony/FOSElasticaBundle#443]
I have two index types, Consumer and Lead. Both of these in my symfony2 application use class table inheritance to a "Person" entity. However, in elastic search I would like to keep an index for each, independently. 

While populating the Consumer index it gets about 95% done and it gets an exception saying that the Lead (should be a Consumer) does not have a property on it. This is because it is trying to index a Lead in the Consumer index. I am not sure how the Lead is getting in the resultset from the query. I have not had this happen previously and has only started happening the past couple days, for me, and I cannot seem to figure it out.

My configuration, repository methods and command output are all below:

composer.json version:

``` json
"friendsofsymfony/elastica-bundle": "3.0.*@dev",
```

app/config/config.yml

``` yaml
fos_elastica:                                                     
    clients:                                                      
        default: { host: %elastica_host%, port: %elastica_port% } 
    indexes:                                                      
        website:                                                  
            client: default                                       
            index_name: website                                   
            settings:                                             
                index:                                            
                    analysis:                                     
                        analyzer:                                 
                            analyzer_startswith:                  
                                tokenizer: keyword                
                                filter: lowercase                 
                            my_ngram_analyzer:                    
                                tokenizer: my_ngram_tokenizer     
                        tokenizer:                                
                            my_ngram_tokenizer:                   
                                type: nGram                       
                                min_gram: 2                       
                                max_gram: 20  
            types:
                Consumer:                                                                        
                    mappings:                                                                     
                        first_name: { boost: 3, analyzer: snowball }                              
                        last_name: { boost: 3, analyzer: snowball }                               
                        email_address: { analyzer: analyzer_startswith }                                                                                 
                        organization.name: ~                                                      
                        tracking_number: ~                                                                                                                      
                    persistence:                                                                  
                        driver: orm                                                               
                        model: Foo\AppBundle\Entity\User\Consumer                           
                        finder: ~                                                                 
                        provider:                                                                 
                            query_builder_method: getQueryBuilderForElasticIndex                  
                        repository: Foo\AppBundle\SearchRepository\User\ConsumerRepository  
                        listener:                                                                 
                            is_indexable_callback: "isIndexableByElasticSearch"                   
                            insert: true                                                          
                            update: true                                                          
                            delete: true      
                Lead:                                                                      
                    mappings:                                                                 
                        first_name: { boost: 3, analyzer: snowball }                          
                        last_name: { boost: 3, analyzer: snowball }                           
                        email_address: { analyzer: analyzer_startswith }                                                                        
                        organization.name: ~                                                  
                        date_of_birth: ~                                                      
                    persistence:                                                              
                        driver: orm                                                           
                        model: Foo\AppBundle\Entity\User\Lead                         
                        finder: ~                                                             
                        provider:                                                             
                            query_builder_method: getQueryBuilderForElasticIndex              
                        repository: Foo\AppBundle\SearchRepository\User\LeadRepository
                        listener:                                                             
                            insert: true                                                      
                            update: true                                                      
                            delete: true                                                                                

```

Repository method for Consumer:

``` php
 /** src/Foo/AppBundle/Entity/Repository/User/ConsumerRepository.php **/
 public function getQueryBuilderForElasticIndex()                 
 {                                                                                   
     $qb = $this->createQueryBuilder('a')                         
         ->join('a.organization', 'g')                            
     ;                                                            

     return $qb;                                                  
 }                                                                
```

Repository method for Lead:

``` php
 /** src/Foo/AppBundle/Entity/Repository/User/LeadRepository.php **/
 public function getQueryBuilderForElasticIndex()                 
 {                                                                                   
     $qb = $this->createQueryBuilder('a')                         
         ->join('a.organization', 'g')                            
     ;                                                            

     return $qb;                                                  
 }                                                                
```

Command being run: 
`app/console fos:elastica:populate --no-debug -vvv`

Outputs:

```
Populating website/Consumer, 94.5% (30700/32470), 33 objects/s
Populating website/Consumer, 94.9% (30800/32470), 28 objects/s
Populating website/Consumer, 95.2% (30900/32470), 31 objects/s
Populating website/Consumer, 95.5% (31000/32470), 29 objects/s
Populating website/Consumer, 95.8% (31100/32470), 23 objects/s

[Symfony\Component\PropertyAccess\Exception\NoSuchPropertyException]
Neither the property "tracking_number" nor one of the methods "getTrackingNumber()", "isTrackingNumber()", "hasTrackingNumber()", "__get()" exist and have public access in class "Foo\AppBundle\Entity\User\Lead".

Exception trace:
 () at /var/www/app/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php:236
 Symfony\Component\PropertyAccess\PropertyAccessor->readProperty() at /var/www/app/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php:130
 Symfony\Component\PropertyAccess\PropertyAccessor->readPropertiesUntil() at /var/www/app/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php:49
 Symfony\Component\PropertyAccess\PropertyAccessor->getValue() at /var/www/app/vendor/friendsofsymfony/elastica-bundle/FOS/ElasticaBundle/Transformer/ModelToElasticaAutoTransformer.php:72
 FOS\ElasticaBundle\Transformer\ModelToElasticaAutoTransformer->transform() at /var/www/app/vendor/friendsofsymfony/elastica-bundle/FOS/ElasticaBundle/Persister/ObjectPersister.php:109
 FOS\ElasticaBundle\Persister\ObjectPersister->transformToElasticaDocument() at /var/www/app/vendor/friendsofsymfony/elastica-bundle/FOS/ElasticaBundle/Persister/ObjectPersister.php:96
 FOS\ElasticaBundle\Persister\ObjectPersister->insertMany() at /var/www/app/vendor/friendsofsymfony/elastica-bundle/FOS/ElasticaBundle/Doctrine/AbstractProvider.php:48
 FOS\ElasticaBundle\Doctrine\AbstractProvider->populate() at /var/www/app/vendor/friendsofsymfony/elastica-bundle/FOS/ElasticaBundle/Command/PopulateCommand.php:123
 FOS\ElasticaBundle\Command\PopulateCommand->populateIndex() at /var/www/app/vendor/friendsofsymfony/elastica-bundle/FOS/ElasticaBundle/Command/PopulateCommand.php:95
 FOS\ElasticaBundle\Command\PopulateCommand->execute() at /var/www/app/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:244
 Symfony\Component\Console\Command\Command->run() at /var/www/app/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:904
 Symfony\Component\Console\Application->doRunCommand() at /var/www/app/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:191
 Symfony\Component\Console\Application->doRun() at /var/www/app/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:96
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /var/www/app/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:121
 Symfony\Component\Console\Application->run() at /var/www/app/app/console:22
```

As you can see, I am trying to populate the Consumer type index, but it is somehow getting a Lead object instead of a Consumer and failing because it does not have the property/method that is located on the Consumer entity.

I've tried clearing the cache and installing the newest version of this bundle (with 3.0.*@dev) but no luck.  It keeps getting this far and failing. 

Has anyone experienced this or happen to know why this would be occuring?
