### ISSUE TITLE
Implement suggestion

### ISSUE THREAD

**Issue by Lughino** [FriendsOfSymfony/FOSElasticaBundle#469]
Can you implement the feature suggestion? 

I think it is one of the most important features for elasticsearch, and is already available on the library elastic a long time ago!

**Comment by misteio** [comment]
It works ! @ilithium is right.

First you must create a special field 'suggestion' or whatever you want in your config.yml.
suggest:
                                type: completion
                                index_analyzer: simple
                                search_analyzer: simple
                                payloads: true

And next a little exemple for your query:

$query = new \Elastica\Query(new \Elastica\Query\MatchAll());
$suggest = new \Elastica\Suggest();
$suggest->setParam('completion', ['text' => 'reserarch', 'completion' => ['field' => 'suggest']]);
$query->setSuggest($suggest);

**Comment by Hoannv** [comment]
+1

**Comment by ilithium** [comment]
Sweet! Thanks @misteio - nice to hear someone's found use for this.

FWIW, for users of Elastica, FOSElasticaBundle or ElasticSearch please do read the [ElasticSearch Book](https://www.elastic.co/guide/en/elasticsearch/guide/master/index.html) as the Elastica suite (and hence FEB) implement most things as class methods/properly structured PHP stuff, but also allow you to execute arbitrary JSON queries so even if you're trying to do something which Elastica doesn't, you can just create the JSON and execute it that way.

**Comment by XWB** [comment]
https://github.com/FriendsOfSymfony/FOSElasticaBundle/pull/1214

**Comment by rbrannath** [comment]
@misteio I have tried to follow your code but I can't figure it out. Could you help me on this?

**Comment by misteio** [comment]
@rbrannath Lot of things have change on this repo. I use my own bundle now. The best to do I think it's like said ilithium, to use arbitrary json. For my old code, I can't remember how to use it sorry.

**Comment by rbrannath** [comment]
@misteio thanks for your reply!
Figured it out by myself, not sure if its recommendable, at least it works:

Here is what I did:

added field "suggest" in my Entity and in config:
 
 ```
    # Entity Articles

     private $suggest;

    /**
     * Set suggest
     *
     * @param string suggest
     * @return Articles
     */
    public function setSuggest($suggest)
    {
        $this->suggest = $suggest;

        return $this;
    }

    /**
     * Get suggest
     *
     * @return string
     */
    public function getSuggest()
    {
        return $this->shortName;
    }
```

```
     # config.yml   
     shortName:   
          type: string   
                        analyzer: custom_analyzer   
                    suggest:   
                        type: completion   
                        analyzer: simple   
                        preserve_separators: true   
                        preserve_position_increments: true   
                        payloads: true    
                        max_input_length: 50
```


And finally in my controller:

```
       # controller
      $query = 'bund';
      $mngr = $this->get('fos_elastica.index_manager');
      $search = $mngr->getIndex('search')->createSearch();
      $suggest = new \Elastica\Suggest();
      
      $suggest->setParam('comp', ['text' => 'polo-shirt', 'completion' => ['field' => 'suggest']]);
      $search->setSuggest($suggest);
      $result = $search->search();
      if ($result->countSuggests()) {
          $suggestions = [];
          foreach ($result->getSuggests()['comp'][0]['options'] as $suggestion) {
              $suggestions[] = $suggestion['text'];
          }
      }
```
