### ISSUE TITLE
Auto update for child object(s) with attachments

### ISSUE THREAD

**Issue by rahimijavad** [FriendsOfSymfony/FOSElasticaBundle#470]
Hi,

I created a mapping which contains a type object; for the persistence section I set a model and listener. The problem is that when an object is inserted to the main entity and child, it just auto update index for the main object and not the child.
Does anybody know how to fix this issue?

Below is a sample of my mapping:

```
fos_elastica:
   clients:
      default: { host: localhost, port: 9200 }
   indexes:
      website:
          client: default
          types:
              docs:
                  mappings:
                      Title: ~
                      Description: ~
                      attachments:
                         type: "object"
                         properties:
                            FileName:
                            content:
                               type: attachment 
                  persistence:
                      driver: orm
                      model: MyBundle\Entity\Docs
                      provider: ~
                      listener: ~
                      finder: ~
```
