### ISSUE TITLE
[Bug?/Missing docs?] Unable to filter query with nested properties

### ISSUE THREAD

**Issue by stloyd** [FriendsOfSymfony/FOSElasticaBundle#488]
Hello there, first I want to say sorry if I misconfigured something, but documentation is not best yet =) So, let's describe the problem!

I have config like (simplified):

``` yaml
fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        frontend:
            client: default
            types:
                country:
                    mappings:
                        name: { boost: 5 }
                        provinces:
                            type: "nested"
                            properties:
                                id: ~
                                name: { boost: 2 }
                    persistence:
                        driver: orm
                        model: Acme\DemoBundle\Entity\Country
                        repository: Acme\DemoBundle\SearchRepository\CountryRepository
                        provider: ~
                        listener: ~
                        finder: ~
```

Simplified repository looks like:

``` php
namespace Acme\DemoBundle\SearchRepository;

use FOS\ElasticaBundle\Repository;
use Acme\DemoBundle\Form\Model\SearchData;

class CountryRepository extends Repository
{
    public function search(SearchData $search, $page = 1)
    {
        // $search - it's simple class that holds data between form and this repository
        $query = new \Elastica\Query\MatchAll();
        $boolQuery = new \Elastica\Query\Bool();
        $boolQuery->addMust($query);

        if (null !== $search->getProvinces()) {
            $boolFilter->addMust(
                new \Elastica\Filter\Terms('provinces.id', [$search->getProvinces()])
            );
        }

        $filtered = new \Elastica\Query\Filtered($boolQuery, $boolFilter);

        $query = \Elastica\Query::create($filtered);
        $query->addSort([
            $search->getSortField() => $search->getSortMethod()
        ]);

        $results = $this->findPaginated($query);
        $results->setMaxPerPage(12);
        $results->setCurrentPage($page);

        return $results;
    }
}
```

And that code when filtering provinces will always return `0` results (`provinces` in `Country` model are `Doctrine\ArrayCollection` object). Yet after long playing, debugging random changes (from different queries to config changes), I have found that simple change:

``` yaml
provinces:
    type: "object" # old was "nested"
    properties:
        id: ~
        name: { boost: 2 }
```

Fixes whole problem =)

Dunno it's just me that missed some docs, but I read it like 10 times =) I guess it could be noted somewhere in docs if it's not bug, to prevent others reaching this problem and fighting with it on their own =)
