### ISSUE TITLE
How to set multi_field in config.yml?

### ISSUE THREAD

**Issue by ushios** [FriendsOfSymfony/FOSElasticaBundle#495]
```
fos_elastica:
    clients:
        default: { host: "xxx.xxx.com", port: 9200 }
    indexes:
        reporters:
            client: default
            index_name: reporters
            settings:
                index:
                    analysis:
                        analyzer:
                            my_kuromoji:
                                type: kuromoji
                                mode: search
                                tokenizer: kuromoji_tokenizer
            types:
                models:
                    mappings:
                        self_pr:
                            type: string
                            analyzer: my_kuromoji
                        nickname_ja:
                            type: string
                            index: analyzed
                            analyzer: my_kuromoji
                            fields:
                                full:
                                    type: string
                                    index: not_analyzed
                        brithday:
                            type: date
                        height:
                            type: integer
                        bast:
                            type: integer
                        hip:
                            type: integer
                        waist:
                            type: integer
```

Command `app/console fos:elastica:reset` has error.

```
[Elastica\Exception\ResponseException]
RemoteTransportException[[Machine Man][inet[/xx.xx.xx.xx:9300]][indices/create]]; nested: MapperParsingException[mapping [models]]; nested: ClassCastException[java.util.ArrayList cannot be cast to java.util.Map]; 
```

I was tested on elastica-bundle 3.0.*@dev, elasticsearch 1.0.0RC1 and 1.0.1 but faild both version.
