### ISSUE TITLE
transformToElasticaDocument not working when using some provider

### ISSUE THREAD

**Issue by omenrpg** [FriendsOfSymfony/FOSElasticaBundle#500]
When I have configuration like this

```
fos_elastica:
    clients:
        default: { host: %elastic_search_host%, port: %elastic_search_port% }
    serializer:
        callback_class: FOS\ElasticaBundle\Serializer\Callback
        serializer: serializer
    indexes:
        avazanga:
            client: default
            types:
                something:
                    mappings: ~
                    serializer:
                        groups: [elastica]
                    persistence:
                        driver: mongodb
                        model: Some\Entity\User
                        model_to_elastica_transformer:
                            service: some.elastic.service.transformer
                        provider: ~
                        finder: ~
                        listener: ~
```

and will defined model_to_elastica_transformer, changes which I'm doing are overwritten by serializer. There is problem in FOS\ElasticaBundle\Persister\ObjectSerializerPersister:

```
public function transformToElasticaDocument($object)
    {
        $document = $this->transformer->transform($object, array());

        $data = call_user_func($this->serializer, $object);
        $document->setData($data);

        return $document;
    }
```

$document->setData($data) is overwriting all modification which has been done in transformer.
