### ISSUE TITLE
FatalErrorException: Error: Cannot redeclare class Doctrine\ORM\Mapping\Annotation 

### ISSUE THREAD

**Issue by dewos** [FriendsOfSymfony/FOSElasticaBundle#506]
I really don't understand how to make things works. 

The Mapping:

```
            node:
                mappings:
                    name: { type: string }
                persistence:
                    driver: orm
                    model: Agenda\CoreBundle\Entity\Node\StructureNode
                    provider: ~
                    listener: ~

            document:
                mappings:
                    name: { type: string }
                    node:
                        type: "object"
                persistence:
                    driver: orm
                    model: Agenda\DocumentBundle\Entity\DocumentEntity
                    provider: ~
                    listener: ~
```

But it keeps getting (on Document CRD) a FatalErrorException: Error: Cannot redeclare class Doctrine\ORM\Mapping\Annotation in [.....] vendor\doctrine\orm\lib\Doctrine\ORM\Mapping\Annotation.php line 22

Any tips? It seems related to https://github.com/schmittjoh/JMSSerializerBundle/issues/123
