### ISSUE TITLE
Empty fields / properties array added to all mappings

### ISSUE THREAD

**Issue by nurikabe** [FriendsOfSymfony/FOSElasticaBundle#511]
Some kind of bug in `Configuration.php` it looks like.  For example, if a mapping has a fields node, such as:

``` yaml
mappings:
    name: ~
    data:
        type: attachment
        fields:
            author: ~
            date: ~
            title: ~
            keywords: ~
```

Then _all_ mappings will receive an empty fields array.  For example, the above produces the following JSON for the `name` mapping:

``` json
{"name":{"type":"string","include_in_all":true,"enabled":true,"fields":[],"properties":[]}
```

Ideally this would just be:

``` json
{"name":{"type":"string","include_in_all":true,"enabled":true}
```

This behavior hasn't been a problem with ElasticSearch up to 0.9.10, but testing now on 1.0.1, the presence of the empty array occasionally causes ElasticSearch to throw ClassCastExceptions when resetting an index or type (via populate for example):

``` java
java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.util.Map
```

This may be what folks are seeing in #369.
