### ISSUE TITLE
Delete listener not working

### ISSUE THREAD

**Issue by createproblem** [FriendsOfSymfony/FOSElasticaBundle#517]
Hello.

I've the following configuration.

``` yml
fos_elastica:
    clients:
        default: { host: "%search_host%", port: "%search_port%" }

    indexes:
        test:
            client: default
            types:
                advert:
                    mappings:
                        title: { boost: 5 }
                    persistence:
                        driver: orm
                        model: Acme\Demo\Entity\Demo
                        provider: ~
                        finder: ~
                        listener:
                            insert: true
                            update: true
                            delete: true
                            immediate: false
```

Now if I delete an entity I get an exception.

```
ActionRequestValidationException[Validation Failed: 1: id is missing;] 
```

If I set `immediate` to `true` everything works as expected. I triple checked everything but cannot find any mistakes in my configuration. Can someone tell me what the problem is? Maybe this is a bug? Its important that `immediate` is set to `false`. Another workaround is to deactivate the delete listener and write a delete routine by hand.

PS: Update and Insert works fine, only delete is broken.

Cheers.
