### ISSUE TITLE
Nested field messes with the rest of fields mappings

### ISSUE THREAD

**Issue by habashysr** [FriendsOfSymfony/FOSElasticaBundle#550]
Adding `properties` to one field adds `properties` to all other mapped fields caused document transformation failure

```
mappings:
    foo: { type: "string" }
    bar: { type: "object" }
    foobar:
          type: "object"
          properties: 
                foobarfoo: { type: "string" }
```

```
 'foo' => 
        array (size=5)
          'type' => string 'string' (length=6)
          'include_in_all' => boolean true
          'enabled' => boolean true
          'properties' => 
            array (size=0)
              empty
      'bar' => 
        array (size=4)
          'type' => string 'object' (length=6)
          'include_in_all' => boolean true
          'enabled' => boolean true
          'properties' => 
            array (size=0)
              empty
      'foobar' => 
        array (size=4)
          'type' => string 'object' (length=6)
          'include_in_all' => boolean true
          'enabled' => boolean true
          'properties' => 
            array (size=1)
                    'foobarfoo' =>
                             array (size=1)
                                  'type'=>'string'
```

Quick solution at REF #549
