### ISSUE TITLE
Empty arrays added to type mappings by Configuration

### ISSUE THREAD

**Issue by evillemez** [FriendsOfSymfony/FOSElasticaBundle#561]
When I have mappings that contain nested "properties", I cannot reset/populate ES due to Java errors.  I think I've tracked it down to how the bundle config is validated, with default empty arrays being added in places where they should not be.

This probably relates to #550, #511, #369, and maybe others.

Given this type mapping:

``` yaml
types:
    resource:
        mappings:
            title:
                boost: 5
                analyzer: default
            client:
                type: object
                properties:
                    id:
                        index: not_analyzed
```

The following error comes back from ES:

```
[Elastica\Exception\ResponseException]                                                                                         
  MapperParsingException[mapping [resource]]; nested: ClassCastException[java.util.ArrayList cannot be cast to java.util.Map];
```

PR coming soon.

**Update:** For reference, this seems to be the underlying ES issue: https://github.com/elasticsearch/elasticsearch/issues/5887
