### ISSUE TITLE
Right way to configure and handle OneToMany and ManyToMany relationships

### ISSUE THREAD

**Issue by reypm** [FriendsOfSymfony/FOSElasticaBundle#573]
I have this on one of my entities (`Lugar.php`):

```
/**
 * @ORM\OneToMany(targetEntity="Mapyet\StartBundle\Entity\LugarUsuario", mappedBy="lugar", cascade={"remove"})
 */
private $lugarUsuario;

/**
 * @ORM\ManyToMany(targetEntity="Mapyet\AfiliadoBundle\Entity\Negocio", inversedBy="lugares")
 * @ORM\JoinTable(name="negocio_lugar",
 *     joinColumns={@ORM\JoinColumn(name="lugar_id", referencedColumnName="id")},
 *     inverseJoinColumns ={@ORM\JoinColumn(name="negocio_id", referencedColumnName="id")}
 * )
 */
private $negocios;
```

And this is my configuration at `config.yml`:

```
fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        search: 
            types:
                categoria:
                    mappings:
                        nombre: ~
                        descripcion: ~
                        subCategorias: ~
                    persistence:
                        driver: orm
                        model: Mapyet\BackendBundle\Entity\Categoria
                        provider: ~
                        listener: ~
                        finder: ~
                        immediate: ~
                lugar:
                    mappings:
                        nombre: ~
                        latitud: ~
                        longitud: ~
                        direccion: ~
                        referencia: ~
                        contacto: ~
                        precio_adulto: ~
                        precio_infante: ~
                        comuna: ~
                        subcategoria: ~
                        imagenes: ~
                        evaluacion: ~
                        lugarItinerario: ~
                        lugarUsuario: ~
                        negocios: ~
                        indexacion: ~
                    persistence:
                        driver: orm
                        model: Mapyet\BackendBundle\Entity\Lugar
                        provider: ~
                        listener: ~
                        finder: ~
                        immediate: ~
```

Is this config right? How the Bundle handle this kind of attributes and relations between entities?
