### ISSUE TITLE
Some way to pass extra parameters for Using a custom query builder method for transforming results

### ISSUE THREAD

**Issue by rkmax** [FriendsOfSymfony/FOSElasticaBundle#586]
Following the example in 

``` yaml
            user:
                persistence:
                    elastica_to_model_transformer:
                        query_builder_method: createSearchQueryBuilder
```

i need pass a extra parameter when call the method createSearchQueryBuilder

``` php
class UserRepository extends EntityRepository
{
    /**
     * Used by Elastica to transform results to model
     * 
     * @param string $entityAlias
     * @return  Doctrine\ORM\QueryBuilder
     */
    public function createSearchQueryBuilder($entityAlias, $user)
    {
        $qb = $this->createQueryBuilder($entityAlias);

        $qb->select($entityAlias, 'g')
            ->innerJoin($entityAlias.'.groups', 'g')
            ->addWhere('g.user = :user_id')
            ->setParameter('user_id', $user);

        return $qb;
    }
}

/*... */
$data = $finder->find($query, $user);

```

it's possible accomplish this with the current API
