### ISSUE TITLE
ElasticsearchIllegalArgumentException[Can't specify parent if no parent field has been configured]

### ISSUE THREAD

**Issue by korotovsky** [FriendsOfSymfony/FOSElasticaBundle#592]
Commit fa65784b4730aa7a13eed15d03e12e6477dc3f28 breaks the tests in the application on parent/child configuration. But in the previous commit c52c32fb56972e59a1071cb9229d4cc79c65ba45 all the tests go well.

Some example of our mapping:

```
        types:
            user:
                mapping:
                    field1: ~
                persistence: ~

            user_profile:
                _parent: { type: user, property: owner }
                mapping:
                    field1: ~
                    field2:
                        type: nested
                        properties:
                            nested_field1: { type: integer }
                            nested_field2:
                                type: object
                                properties: { id: { type: integer } }
```

P.S: when we change “mapping” to “properties”, we get:

```
Symfony\Component\Config\Definition\Exception\InvalidConfigurationException: Unrecognized options "properties" under "fos_elastica.indexes.users.types.user_profile.properties.nested_field2"
```
