### ISSUE TITLE
mapping on populate

### ISSUE THREAD

**Issue by datenarbeit** [FriendsOfSymfony/FOSElasticaBundle#599]
Hi,
i think there is a problem in creating the mapping information in 3.0.x-dev with elastica 1.1.1.1.  
my configuration:

```
           types:
                category:
                    mappings:
                        url: { type: string, index: not_analyzed }
```

now, instead of 

```
PUT /myindex
{
  "mappings": {
    "category": {
      "_source": {
        "enabled": true
      },
      "properties": {
        "url": {
          "type": "string",
          "index": "not_analyzed",
          "include_in_all": true,
          "enabled": true
        }
    }
  }
}
```

the following data is send ot elastic:

```
PUT /myindex
{
  "properties": {
    "category": {
      "_source": {
        "enabled": true
      },
      "properties": {
        "url": {
          "type": "string",
          "index": "not_analyzed",
          "include_in_all": true,
          "enabled": true
        }
    }
  }
}
```

this effects, that the not_analyzed option is not applied. this used to work in previous versions, but now the not_analysed option in not applied in any of my definitions.
