### ISSUE TITLE
Ideas around ModelToElasticaTransformer

### ISSUE THREAD

**Issue by ASKozienko** [FriendsOfSymfony/FOSElasticaBundle#606]
Hi I have several problems with ModelToElasticaAutoTransformer which are very common as for me, but I can't solve them without very custom and a quite big transformer. And would be better to implement it natively into this bundle. 
I will try to explain all of them with examples.
1)
```yaml
fos_elastica:
    types:
        product:
            price:
                type: integer
                __transformer: productPrice
```
So this example shows us product and it has property price. But its just a base price and in real live we use some kind of price calculator to add tax, discount etc. And I want to introduce extra option  `__transformer` which is field transformer name.
Behind the scene every type and even internal types (string, nested, _parent) have `field transformer/strategy`. When `__transformer` is missed internal type guesser tries to define type (almost the same like current ModelToElasticaAutoTransformer does)
2)
```yaml
fos_elastica:
    types:
        product:
            dynamic_templates:
                attributes:
                    match: attribute_*
                    mapping: ~
            attributes:
                __virtual: true
                __transformer: productAttributes
```
This part is not so clear for me, its just  food for thought. So our product has or even has no, doesnt matter, property `attributes` but we want transform our attributes to the next form
```json
{
    "attribute_color": ["red", "blue"], 
    "attribute_weight": [124]
}
```
Yep again `__transformer` does all work but extra field `__virtual` means this field is not a part of es mapping. This example is helpful for `dynamic_templates ` and denormalization of translatable fields into something like `title_en`, `title_fr` etc.

Please tell me what you think about this.
