### ISSUE TITLE
Index wide finder is not registered

### ISSUE THREAD

**Issue by daFish** [FriendsOfSymfony/FOSElasticaBundle#61]
I'm trying to use the index wide finder and have registered it as mentioned in the README:

```
foq_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        fmdb:
            client: default
            finder:
            // rest of my configuration
```

Trying to get the service from the container just gives me an 500 and dumping the container reveals no registered service. Did I miss something? The finders for my types are all registered.
