### ISSUE TITLE
multi_field in config.yml still doesn't work ...

### ISSUE THREAD

**Issue by fernandodbc** [FriendsOfSymfony/FOSElasticaBundle#615]
Hello,

My code works on v3.0.0-alpha5 but not in dev-master.

Here you have my config.yml :

```
            client: default
            types:
                Article:
                    mappings:
                        title:
                            type: string
                            fields:
                                raw:
                                    type: string
                                    index: not_analyzed
```

In dev-master version, after a populate elasticsearch only map :

```
"title" : {
            "type" : "string"
          },
```

But in v3.0.0-alpha5 it's work perfectly
