### ISSUE TITLE
How to update a index manually

### ISSUE THREAD

**Issue by rkmax** [FriendsOfSymfony/FOSElasticaBundle#616]
I have a many to many relationship and i have a two types in the same index

```
entityA:
  properties:
    entityB:
      type: nested

entityB:
  properties:
    entityA:
      type: nested
```

but when i change some in the table entityAHasEntityB the index is not updated. i need some way to update the two index manually but only for the updated object not the whole index.

there is nothing in the documentation to that
