### ISSUE TITLE
Nested mapping (same column name)

### ISSUE THREAD

**Issue by trsteel88** [FriendsOfSymfony/FOSElasticaBundle#617]
I have the following config:

``` yaml
fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        search:
            client: default
            types:
                user:
                    mappings:
                        firstName: { boost: 3 }
                        lastName: { boost: 3 }
                        dob: { type: date }
                        children:
                            type: "nested"
                            properties:
                                dob: { type: date }
```

I have found that when the column name "dob" has the same name as the nested child it doesn't save it correctly. However, I am not sure if this is an issue with how elasticsearch stores the data, or if this is an issue with the bundle.

With the config above, when doing a range search on the child it wouldn't find any matches. I managed to get around the issue by naming the children dob to "childDob". I am then able to query for both the child and parent dob ranges.
