### ISSUE TITLE
how to query documents contain nested field's element length > 0

### ISSUE THREAD

**Issue by hoannv** [FriendsOfSymfony/FOSElasticaBundle#620]
Hi,

Here is school entity mapping

```
school:
    mappings:            
        name: ~
        rankings:
            type: "nested"
                properties:
                    id: ~
```

 I get a problem with query for finding all school contains rankings element length > 0. I try use filter script but it throws error. I don't know how to fix it. Pls help me resolve this issue. Thanks.
