### ISSUE TITLE
Initialization mapping

### ISSUE THREAD

**Issue by baptistedonaux** [FriendsOfSymfony/FOSElasticaBundle#628]
I use the current version (3.0~) and I have declared my ElasticSearch mappings in my configuration but when I reset my base, the mapping isn't set.

When I push in ElasticSearch that it added all dynamically fields.

This is my Symfony2 configuration :

```
fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }

    indexes:
        my_index:
            client: default
            finder: ~
            types:
                my_type:
                    mappings:
                        my_first_field:   { index: true, store: false, type: integer }
                        my_second_field: { index: true, store: false, type: string }
                        my_third_field:        { index: true, store: false, type: attachment }

                    persistence:
                        driver: orm
                        finder: ~
                        model: Namespace\MyBundle\Entity\MyEntity
                        provider: ~
                        elastica_to_model_transformer:
                            service: my.transformer
```

When I execute **php app/console fos:elastica:reset**, and I check the mapping, I have a empty mapping.

If I disable the dynamic mapping in ElasticSearch, FOS throw this exception.

```
[Elastica\Exception\Bulk\ResponseException]                                                                                          
    Error in one or more bulk request actions:                                                                                           
    index: /my_index/my_type/198 caused TypeMissingException[[my_index] type[[my_type, trying to auto create mapping, but dynamic mapping is disabled  
    ]] missing]
```

An idea ?
