### ISSUE TITLE
store mapping doesn't works

### ISSUE THREAD

**Issue by baptistedonaux** [FriendsOfSymfony/FOSElasticaBundle#636]
When I declare my mapping type, boost option works but the option **store** doesn't works.

This is my mapping :

```
fos_elastica:
    indexes:
        myIndex:
            client: default
            finder: ~
            types:
                myType:
                    mappings:
                        fiertField:   { type: integer,  boost: 2,  store: false }
```
