### ISSUE TITLE
Simple Config: [Elastica\Exception\ResponseException]

### ISSUE THREAD

**Issue by fdrechsler** [FriendsOfSymfony/FOSElasticaBundle#641]
i installed FOSElastica 3.0 with Composer to my Symfony Project. This is my Config:

```
fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        search:
          types:
            keyword:
                mappings:
                    value:
                      type: string
                persistence:
                    driver: orm
                    model: Anklick\UserPagesBundle\Entity\Keyword
                    provider: ~
                    listener:
                        immediate: ~
                    finder: ~
```

Pretty simple huh?

Now when i do  `php app/console fos:elastica:populate`

It says me:

```
Resetting search

[Elastica\Exception\ResponseException]
ClassCastException[java.util.ArrayList cannot be cast to java.util.Map]
```

Whats the Problem?

EDIT: With 2.1.x everything works fine.
