### ISSUE TITLE
Cannot get any results in a search

### ISSUE THREAD

**Issue by gfrooo1989** [FriendsOfSymfony/FOSElasticaBundle#642]
I have a problem that I cannot sort it out, I have tried everyhing I have found on the web for this.

I have installed the bundle using composer, no problems. Please note that I am using symphony2. For the very most basic of search, my config looks like this :

```
fos_elastica:
 clients:
    default: { host: localhost, port: 80 }
 indexes:
    search:
        client: default
        types:
            story:
                mappings:
                    name: ~
                persistence:
                    driver: orm
                    model: Website\WebBundle\Entity\Story
                    provider: ~
                    listener: ~
                    finder: ~
```

I do not have any problems generating the data with php app/console fos:elastica:populate. The result are corectly inserted ( matching number or entries with the database entries ).

So, my problem is cannot display ANY results. I always have empty array as result for :

```
$finder = $this->container->get('fos_elastica.finder.search.story');
$results = $finder->find('name');
```

Also empty result for :

```
$repositoryManager = $this->container->get('fos_elastica.manager');
$repository = $repositoryManager->getRepository('WebsiteWebBundle:Story');
$results = $repository->find('name');
```

And I have a record in the database with the name 'name' so I should get results. Searching for a letter doesn't work also.

So, can anybody tell me what I am doing wrong ? Or is there any way of displaying all the results so I can see that the results are there and only the searching fails ?

Thanks
