### ISSUE TITLE
Field mapping with underscore (e.g. _ttl) and Symfony coding guidelines compliance

### ISSUE THREAD

**Issue by choonge** [FriendsOfSymfony/FOSElasticaBundle#650]
I have an Article entity which can optionally have a TTL. I have this configuration:

``` yml
fos_elastica:
    indexes:
        website:
            client: default
            types:
                article:
                    _ttl:
                        enabled: true
                    mappings:
                        body: ~
                        _ttl: ~
                    persistence:
                        driver: orm
                        model: Acme\DemoBundle\Entity\Article
                        provider: ~
```

The Article entity looks like this:

``` php
class Article
{
    /**
     * @return null
     */
    public function getTtl()
    {
        return $this->getTtl();
    }
```

ModelToElasticaAutoTransformer::transform() will try to access the _ttl property of Article at:

``` php
$value = $this->propertyAccessor->getValue($object, $key);
```

Which results in this error:

```
  [Symfony\Component\PropertyAccess\Exception\NoSuchPropertyException]                                                                                                                     
  Neither the property "_ttl" nor one of the methods "get_ttl()", "_ttl()", "is_ttl()", "has_ttl()", "__get()" exist and have public access in class "Genj\ArticleBundle\Entity\Article".  
```

Changing the method name from `getTtl()` to `get_ttl()` circumvents the issue, but breaks with Symfony2 coding standards: http://symfony.com/doc/current/contributing/code/standards.html

```
Use camelCase, not underscores, for variable, function and method names, arguments;
```

This would be a possible solution:

``` php
// Transformer/ModelToElasticaAutoTransformer.php
    public function transform($object, array $fields)
    {
        ...
        $objectProperty = $this->getCleanObjectProperty($key);
        $value = $this->propertyAccessor->getValue($object, $objectProperty);
        ...
    }

    protected function getCleanObjectProperty($key)
    {
        if (substr($key, 0, 1) === '_') {
            $key = substr($key, 1);
        }

        return $key;
    }
```

But I don't know enough about this bundle to say if that could have any adverse consequences. How do you guys feel about this?
