### ISSUE TITLE
Per-document TTL should be optional

### ISSUE THREAD

**Issue by choonge** [FriendsOfSymfony/FOSElasticaBundle#652]
My Article entity can have an optional expiry date. The _ttl in seconds is calculated with 'expiresAt - current timestamp'. If no expiry date is set, I don't want to set the _ttl value. So I don't want a default _ttl. The config:

``` yml
fos_elastica:
    indexes:
        website:
            types:
                article:
                    _ttl:
                        enabled: true
                    mappings:
                        body: ~
                        _ttl: ~
                    persistence:
                        driver: orm
                        model: Acme\DemoBundle\Entity\Article
                        provider: ~
```

I've tried the following default return values for Article::get_ttl():
- returning 0 gives an error that _ttl should > 0
- retuning null or void gives an error `JsonParseException[Current token (VALUE_NULL) not numeric, can not use numeric value accessors`
- returning false gives an error `JsonParseException[Current token (VALUE_FALSE) not numeric, can not use numeric value accessors`

Edit: I get these errors when running the populate Command.

So there seems to be no way to say "no _ttl". I could set it to 9999w of course, but that's just a hack.

Am I missing something, or should I send a PR?
