### ISSUE TITLE
Immediate population does not work as expected

### ISSUE THREAD

**Issue by xsmall** [FriendsOfSymfony/FOSElasticaBundle#654]
Dear @merk 

Underneath here I have my configuration file: 

```
fos_elastica:
    clients:
        default:
            servers:
                - { host: 192.168.10.10, port: 9200, logger: true }
    indexes:
        search:
            types:
                products:
                    mappings:
                        pageTitle: ~
                        searchwords: ~
                    persistence:
                        driver: orm
                        model: Fire\BossBundle\Entity\Page
                        provider: ~
                        listener:
                            immediate: ~
                        finder: ~
```

After updating an Entity it's value in the database, there seems to be a problem updating the mapped values in the ES index.

Any ideas why this might happen?

Best regards,

Xander
