### ISSUE TITLE
How do we use autocompletion with the bundle ?

### ISSUE THREAD

**Issue by Sshuichi** [FriendsOfSymfony/FOSElasticaBundle#673]
Hi again! 
I want to know how do I use term suggestions with symfony2
What I've done so far  : 

```
$suggest=new \Elastica\Suggest();
$termQuery = new \Elastica\Suggest\Term('tokens',$city);
$suggest->addSuggestion($termQuery->setText($city));
// $nameQuery->setFieldQuery('tokens', $city);
$data = $c->find($suggest);
```

it returns always same results no matter what $city is.
my mapping: 

```
mappings:

                    name: {type:"string", boost: 5,analyzer: my_analyzer }                                                                                              
                    tokens: { "type": "completion","index_analyzer": "simple","search_analyzer": "simple","payloads": false}                                            
                    state: {type:"string", boost: 4}
                    location:  { type: "geo_point", "lat_lon": true }
```
