### ISSUE TITLE
ElasticaToModelTransformer with doctrine mongodb

### ISSUE THREAD

**Issue by plozmun** [FriendsOfSymfony/FOSElasticaBundle#674]
With doctrine mongodb and configuration:

```
persistence:
    driver: mongodb
    model: Vivados\Bundle\MainBundle\Document\Property
    elastica_to_model_transformer:
       ignore_missing: true
       query_builder_method: createSearchQueryBuilder
```

the following error occurs:
Call to undefined method Doctrine\ODM\MongoDB\DocumentManager::createSearchQueryBuilder()

If i add the method ->getRepository($this->objectClass) this issue disappears.

```
<?php

namespace FOS\ElasticaBundle\Doctrine\MongoDB;

use FOS\ElasticaBundle\Doctrine\AbstractElasticaToModelTransformer;

/**
 * Maps Elastica documents with Doctrine objects
 * This mapper assumes an exact match between
 * elastica documents ids and doctrine object ids
 */
class ElasticaToModelTransformer extends AbstractElasticaToModelTransformer
{
    /**
     * Fetch objects for theses identifier values
     *
     * @param array $identifierValues ids values
     * @param Boolean $hydrate whether or not to hydrate the objects, false returns arrays
     * @return array of objects or arrays
     */
    protected function findByIdentifiers(array $identifierValues, $hydrate)
    {
        return $this->registry
            ->getManagerForClass($this->objectClass)->getRepository($this->objectClass)
            ->{$this->options['query_builder_method']}($this->objectClass)
            ->field($this->options['identifier'])->in($identifierValues)
            ->hydrate($hydrate)
            ->getQuery()
            ->execute()
            ->toArray();
    }
}
```

Something wrong in my config can not find the repository?

Thanks
