### ISSUE TITLE
multi_field type

### ISSUE THREAD

**Issue by cassianotartari** [FriendsOfSymfony/FOSElasticaBundle#677]
Hello!

I'm trying to use the multi_field type in my mapping without success. I didn't find anything inside FOSElasticaBundle about this.

http://www.elasticsearch.org/guide/en/elasticsearch/reference/0.90/mapping-multi-field-type.html

When I try:

``` yml
                        name:
                            type: multi_field
                            fields:
                                name_metaphone: 
                                type: string
                                analyzer: mf_analyzer
                            name_exact:
                                type: string
                                index: not_analyzed
```

I get in populate:

```
Resetting my_elastica



  [Elastica\Exception\ResponseException]                                       
  MapperParsingException[mapping [media]]; nested: ClassCastException[java.la  
  ng.String cannot be cast to java.util.Map];                                  



fos:elastica:populate [--index[="..."]] [--type[="..."]] [--no-reset] [--offset="..."] [--sleep="..."] [--batch-size="..."] [--ignore-errors]
```

Any ideas?
