### ISSUE TITLE
Hydrate Nested object

### ISSUE THREAD

**Issue by baptistedonaux** [FriendsOfSymfony/FOSElasticaBundle#691]
I would want create an object with a property which is a nested object.

This is my declaration :

``` yaml
fos_elastica:
    indexes:
        myIndex:
            types:
                notice:
                    mappings:
                        created_at:
                            format: basic_date
                            store: false
                            type: date
                        name:
                            boost: 2
                            store: false
                            type: string
                        medias:
                            type: "nested"
                            properties:
                                content:
                                    store: false
                                    type: attachment
                                created_at:
                                    format: basic_date
                                    store: false
                                    type: date
                                name:
                                    type: string
                                    store: false
```

I think that my declaration is good. When I try to hydrate objects, it works. But it's when I want display all my records that I have shards fails.

I push informations into medias like this.

``` php
$document->set("medias", array("created_at"  => "01/01/1970", "name" => "myName"));
```

My method is good ?
