### ISSUE TITLE
Unrecognized options "listener"

### ISSUE THREAD

**Issue by kaiwa** [FriendsOfSymfony/FOSElasticaBundle#7]
According to the docs, automatical index updating will be enabled by defining the "listener" option. Tried with the latest git version, seems this option is unknown?

```
doctrine:
    driver: mongodb
    model: Application\UserBundle\Document\User
    provider:
    finder:
    listener:
```

=>

```
Fatal error: Uncaught exception 'Symfony\Component\Config\Definition\Exception\InvalidConfigurationException' with message 'Unrecognized options "listener" under "foq_elastica.indexes.website.types.item.doctrine"`
```

thanks
