### ISSUE TITLE
multi_field not working

### ISSUE THREAD

**Issue by igorladela** [FriendsOfSymfony/FOSElasticaBundle#712]
version: 3.0.4
elasticsearch 1.3.2

config:

```
fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        search:
          types:
            staff:
                mappings:
                    code:
                        type: multi_field
                        fields:
                            raw:
                                type: string
                                index: not_analyzed
                persistence:
                    driver: orm
                    model: Demo\CoreBundle\Entity\Staff
                    provider: ~
                    listener:
                        immediate: ~
                    finder: ~
```

In result I have the only "code" field without raw
I try instead of "multi_field" use "string" - same result
