### ISSUE TITLE
In order to filterby and order, fields must also be searchable

### ISSUE THREAD

**Issue by cellulosa** [FriendsOfSymfony/FOSElasticaBundle#713]
We have a form that takes a keyword to search for each individual entities:

```
if ($form->get('search')->isClicked()) {

    $data = $form->getData();

    $query = new \Elastica\Query();
    $query->addSort(array('id' => array('order' => 'desc')));

    $q = new \Elastica\Query\QueryString('*' . $data['query'] . '*');
    $term = new \Elastica\Filter\Term(array('archived' => false));
    $filteredQuery = new \Elastica\Query\Filtered($q, $term);

    $query->setQuery($filteredQuery);

    $entities = $this->get('fos_elastica.finder.search.user')->find($query);
}
```

The issue we are having is that the filtered fields "archived" and "id" also become searchable, which is a problem for certain fields. Can this be turned off in the config? Or are we doing the filtering wrong?

This is our `config.yml`:

```
fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        search:
            types:
                user:
                    mappings:
                        id: ~
                        name: ~
                        surname: ~
                    persistence:
                        driver: orm
                        model: Acme\AcmeBundle\Entity\User
                        provider: ~
                        listener:
                            immediate: ~
                        finder: ~
```
