### ISSUE TITLE
PartialShardFailureException when trying to filter by coordinates 

### ISSUE THREAD

**Issue by anthonytison** [FriendsOfSymfony/FOSElasticaBundle#714]
Hi,

Since few days my elastica query doesn't work anymore. I don't have problem to populate and if i remove the GeoDistance part the request is been executed and i get results. Currently, in the trace, I got the following message : 

```
    "message": "1",
    "class": "Elastica\\Exception\\PartialShardFailureException",
    "trace": [
        {
            "namespace": "",
            "short_class": "",
            "class": "",
            "type": "",
            "function": "",
            "file": "/Applications/MAMP/htdocs/GTAB/what2days/api/vendor/ruflin/elastica/lib/Elastica/Transport/Http.php",
            "line": 150,
            "args": []
        }
```

It means nothing to me so i just made a var_export of $shardsStatistics variable and i get that : 

```
    array (
        'total' => 6,
        'successful' => 5,
        'failed' => 1,
        'failures' =>
            array (
                0 =>
                    array (
                        'index' => '.marvel-2014.09.16',
                        'shard' => 0,
                        'status' => 400,
                        'reason' => 'SearchParseException[[.marvel-2014.09.16][0]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query":{"filtered":{"query":{"bool":{"must":[{"term":{"online":{"value":1}}}]}},"filter":{"bool":{"must":[{"geo_distance":{"distance":"100mi","location.latlon":{"lat":48.891773,"lon":2.3379156}}}]}}}}}},"size":"100"}]]]; nested: QueryParsingException[[.marvel-2014.09.16] failed to find geo_point field [location.latlon]]; ',
            ),
        ),
    )
```

The error finish by " failed to find geo_point field [location.latlon]] ". I don't know why it doesn't work because when i check the _mapping the geo_point exists and i didn't make a mistake with the name of the property.

```
    location: {
        properties: {
            latitude: {
                type: "float",
                store: true
            },
            latlon: {
                type: "geo_point",
                store: true,
                lat_lon: true
            },
            longitude: {
                type: "float",
                store: true
            }
        }
    },
```

And this is the way i set fos_elastica

```
fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        search:
            finder: ~
            types:
                mytype:
                    mappings:
                        title:
                          type: string
                        online:
                          type: integer
                        information: ~
                        location:
                            type: object
                            properties:
                              longitude:
                                type: float
                              latlon:
                                type: geo_point
                                lat_lon: true
                                boost: 10
                    persistence:
                        driver: orm
                        model:  API\Rest\v1\MyBundle\Entity\MyEntity
                        provider: ~
                    listener: ~
                    finder: ~
                    repository: API\Rest\v1\MyBundle\Repository\MyRepository
```

When i make a kopf request with the query value (see following query) retrieved by $query->getQuery() i get a correct result. 

```
{
    "query": {
        "filtered": {
            "query": {
                "bool": {
                    "must": [
                        {
                            "term": {
                                "online": {
                                    "value": 1
                                }
                            }
                        }
                    ]
                }
            },
            "filter": {
                "bool": {
                    "must": [
                        {
                            "geo_distance": {
                                "distance": "1mi",
                                "location.latlon": {
                                    "lat": 48.891773,
                                    "lon": 2.3379156
                                }
                            }
                        }
                    ]
                }
            }
        }
    }
}
```

I don't know what to do. I was on 3.0.*@alpha version and now i'm trying the dev-master. I hope someone will help me find what goes wrong.

UPDATE : When i make a var_export in the method getData from Elastica/Response.php i have the failure i explained earlier and i also have 1 hit (the one i want to get).
