### ISSUE TITLE
Persisting Object w/Nested Results In It Being 1 "Persist" Behind

### ISSUE THREAD

**Issue by emirii** [FriendsOfSymfony/FOSElasticaBundle#730]
I'm having a rather terrible issue with FOSElasticaBundle that I have been working on for three days. Usually I don't ask for help but at this point I'm begging for mercy.

I have events that have occurrences, only events can have multiple occurrences but occurrences only have one event.

I create an event and give it 3 occurrences to start out with. Both are persisted fine in the DB, but in elasticsearch the occurrences nest is empty. I go and edit the event and give it 2 more occurrences, all of them show up fine in the DB again, except in elasticsearch now only the first original 3 show up, not my two additions. This can continue on and on, but the latest ones will just simply never show up.

I TRIED a few approaches all over stackoverflow and here but it simply does the same thing. http://stackoverflow.com/questions/21909763/symfony2-foselasticabundle-update-index-for-all-entities-related-to-the-entity-u

I will post everything I currently have here:

My config.yml

``` yaml
    indexes:
        search:
            finder: ~
            types:
                event:               
                    mappings:
                        id: ~
                        event: ~
                        category: { type: string, index: not_analyzed }
                        city: { type: string, index: not_analyzed }
                        description: ~
                        dateAdded: { type: date, format: "yyyy-MM-dd HH:mm:ss" }
                        isActive: ~
                        venueId: ~
                        venue: ~
                        venueIsActive: ~
                        venueDescription: ~
                        occurrences:
                            type: "nested"
                            properties:
                                occurrenceId: ~
                                startDateTime: { type: date, format: "yyyy-MM-dd HH:mm:ss" }
                                endDateTime: { type: date, format: "yyyy-MM-dd HH:mm:ss" }
                                occurrenceIsActive: ~
                    persistence:
                        model_to_elastica_transformer:
                            service: events.transformers.model.event
                        driver: orm
                        model: Events\EventsBundle\Entity\Event
                        provider: ~
                        listener:
                            insert: true
                            update: true
                            delete: true
                        finder: ~  
```

My Services:

``` yaml
services:
    events.transformers.model.event:
        class:   Events\EventsBundle\Transformer\EventsToElasticaTransformer 
    timezonecookie.kernel_response_listener:
        class: Events\EventsBundle\EventListener\SetTimezoneCookie
        arguments: [ @service_container, @doctrine.orm.entity_manager ]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
    fos_elastica.listener.search.occurrences:
        class: Events\EventsBundle\EventListener\EventsPersist
        arguments:
            - @fos_elastica.object_persister.search.event
            - ['postPersist', 'postUpdate', 'preRemove']
            - @fos_elastica.indexable
        calls:
             - [ setContainer, ['@service_container', @fos_elastica.object_persister.search.event ] ]
        tags:
             - { name: 'doctrine.event_subscriber' }
```

My Model 2 Elastica:

``` php
<?php

namespace Events\EventsBundle\Transformer;

use Elastica\Document;
use FOS\ElasticaBundle\Transformer\ModelToElasticaTransformerInterface;
use Symfony\Component\PropertyAccess\PropertyAccessorInterface;

class EventsToElasticaTransformer implements ModelToElasticaTransformerInterface
{
    public function transform($event, array $fields)
    {

        $identifier = $event->getId();

        $occurrences = array();

        foreach($event->getOccurrences()->toArray() as $occurrence) {      
            $occurrences[] = array(
                'id' => $occurrence->getId(),
                'startDateTime' => $occurrence->getStartDateTime()->format('Y-m-d H:i:s'),
                'endDateTime' => $occurrence->getEndDateTime()->format('Y-m-d H:i:s'),
                'occurrenceIsActive' => $occurrence->getIsActive()
            );
        }

        if ($event->getIsActive() && $event->getVenue()->getIsActive()) {
            $active = TRUE;
        } else {
            $active = FALSE;
        }

        $values = array(
            'id' => $event->getId(),
            'event' => $event->getEvent(),
            'category' => $event->getCategory()->getCategory(),
            'city' => $event->getVenue()->getCity()->getCity(),
            'description' => $event->getDescription(),
            'dateAdded' => $event->getDateAdded()->format('Y-m-d H:i:s'),
            'isActive' => $active,
            'venueId' => $event->getVenue()->getId(),
            'venue' => $event->getVenue()->getVenue(),
            'venueDescription' => $event->getVenue()->getDescription(),
            'occurrences' => $occurrences
        );

        //Create a document to index
        $document = new Document($identifier, $values);

        return $document;
    }
}
```

My Listener:

``` php
<?php
namespace  Events\EventsBundle\EventListener;

use FOS\ElasticaBundle\Doctrine\Listener as BaseListener;
use Doctrine\Common\EventArgs;
use FOS\ElasticaBundle\Persister\ObjectPersister;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Events\EventsBundle\Entity\Occurrence;

class EventsPersist extends BaseListener
{
    private $container;
    private $objectPersisterProducts;

    public function setContainer(ContainerInterface $container, ObjectPersister $objectPersisterProduct) {
        $this->container = $container;
        $this->objectPersisterProducts = $objectPersisterProduct;
    }

    public function postUpdate(EventArgs $eventArgs)
    {
        $occurrence = $eventArgs->getEntity();

        if ($occurrence instanceof Occurrence) {
            $event = $occurrence->getEvent();
            $this->objectPersisterProducts->replaceOne($event);
        }
    }
}
```

Any help is GREATLY appreciated... If I get this working I'll be so happy :>
