### ISSUE TITLE
Possible to disable fos_elastica in config_test.yml?

### ISSUE THREAD

**Issue by liuwenchao** [FriendsOfSymfony/FOSElasticaBundle#734]
in test envt, fos_elastica is not mocked up in my case, but it break functional tests with this error:

{"code":500,"message":"Couldn't connect to host, Elasticsearch down?"}

**Comment by OskarStark** [comment]
any news on the `noop` stuff? i would like to deactivate the listeners while i am importing a large dataset to increase speed. after the import is done i can populate the data

**Comment by BentCoder** [comment]
Like @OskarStark  mentioned above, will they ever be an addition to options below to prevent [listener](https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/DependencyInjection/Configuration.php#L530) to update es index? Such as `->booleanNode('noop')->defaultTrue()->end()`


```
fos_elastica:
    indexes:
        index:
            types:
                whatever:
                    persistence:
                        listener:
                            noop: ~
```
