### ISSUE TITLE
Index auto-update not working 

### ISSUE THREAD

**Issue by sujayjaju** [FriendsOfSymfony/FOSElasticaBundle#741]
Here is my config 
  
```
indexes:
        allstock:
            types:
                clip:
                    mappings:
                        title : { boost: 10 }
                        description : { boost: 2 }
                        tags: ~
                    persistence:
                        driver: orm
                        model: Application\AllStock\AssetBundle\Entity\Clip
                        model_to_elastica_transformer:
                            service: allstock.transformers.model.clip
                        provider: ~
                        listener:
                            insert: true
                            update: true
                            delete: true
                            immediate: true
                        finder: ~
```

index is not updating when i update title, description or tags property of an clip entity object
please suggest me some solution or workaround for this issue
