### ISSUE TITLE
facets in a service

### ISSUE THREAD

**Issue by vittore** [FriendsOfSymfony/FOSElasticaBundle#757]
I'm trying to get facets in a service.

```
    manager.search:
        class:  MyBundle\Manager\SearchManager
        arguments:
            - @fos_elastica.finder.bazar.object ( --> map to $this->es property)
            - @knp_paginator
```

And relevant code:

```
        $facet = new \Elastica\Facet\Terms('tags');
        $facet->setField('tags');
        $query->addFacet($facet);
        $resultSet = $this->es->findHybrid($query);
        $elasticaFacets = $resultSet->getFacets();
```

But I get this error:

Attempted to call method "getFacets" on class "FOS\ElasticaBundle\HybridResult"

May you help me?

Thanks in advance.
v.
