### ISSUE TITLE
Notice: Undefined index: indexName in vendor/friendsofsymfony/elastica-bundle/Doctrine/Listener.php at line 218 

### ISSUE THREAD

**Issue by yearofthegus** [FriendsOfSymfony/FOSElasticaBundle#758]
When extending the FOS\ElasticaBundle\Doctrine\Listener, Undefined index: indexName is shown. This only seems to happen when inserting an indexed Entity, and only when passing this to the custom listener service:
 - ['postPersist', 'postUpdate', 'postRemove', 'preRemove']

Using only postUpdate doesn't result in an error.

Services.yml:
```yaml
    company.doctrine.elastica.listener:
        class: 'Company\AppBundle\EventListener\ElasticaUserListener'
        arguments:
            - '@fos_elastica.object_persister.search.user'
            - ['postPersist', 'postUpdate', 'postRemove', 'preRemove']
            - '@fos_elastica.indexable'
        calls:
            - [setContainer, ['@service_container', @fos_elastica.object_persister.search.user]]
        tags:
            - {name: 'doctrine.event_subscriber'}
```

Company\AppBundle\EventListener\ElasticaUserListener:
```php
<?php


namespace Company\AppBundle\EventListener;

use Doctrine\Common\EventArgs;
use FOS\ElasticaBundle\Doctrine\Listener as BaseListener;
use FOS\ElasticaBundle\Persister\ObjectPersister;
use Company\AppBundle\Entity\Location;
use Symfony\Component\DependencyInjection\ContainerInterface;

class ElasticaUserListener extends BaseListener
{
    /** @var ContainerInterface */
    private $container;

    public function setContainer(ContainerInterface $container, ObjectPersister $objectPersister)
    {
        $this->container = $container;
        $this->objectPersister = $objectPersister;
    }

    /**
     * @param EventArgs|\Doctrine\ORM\Event\LifecycleEventArgs $eventArgs
     */
    public function postUpdate(EventArgs $eventArgs)
    {
        /** @var $entity Location */
        $entity = $eventArgs->getEntity();

        if ($entity instanceof Location) {
            $user = $entity->getUser();

            if (!$user) {
                return;
            }

            $this->objectPersister->replaceOne($user);
        }
    }
}
```
