### ISSUE TITLE
Boolean field not indexed

### ISSUE THREAD

**Issue by pierre-b** [FriendsOfSymfony/FOSElasticaBundle#76]
Hi guys,

Could you please confirm this issue ?

I have a boolean field in this config wich is not indexed by the bundle, but it works with the raw Elastica Client:

``` yaml
foq_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        comparator:
            client: default
            settings:
            types:
                product:
                    mappings:
                        ...
                        isDiscount: { type: boolean, store: yes, index: not_analyzed }
                        ....
                    persistence:
                        driver: orm
                        model: Ac\CoreBundle\Entity\Product
                        provider:
                        listener:
```
