### ISSUE TITLE
"multi_field" type fields are not normalized

### ISSUE THREAD

**Issue by vkartaviy** [FriendsOfSymfony/FOSElasticaBundle#764]
```"multi_field"``` type fields are not normalized by ```FOS\ElasticaBundle\Index\MappingBuilder::fixProperties```

For example:
```yml
tag:
    type: multi_field
    fields:
        tag: { boost: 4, index_analyzer: default_index_analyzer, search_analyzer: default_search_analyzer }
        origin: { boost: 5, index: not_analyzed }
```
will raise below exception
```
[Elastica\Exception\ResponseException]
  MapperParsingException[mapping [xxx]]; nested: MapperParsingException[No type specified for property [tag]];
```
