### ISSUE TITLE
fos:elastica:populate --no-reset fails when use_alias: true

### ISSUE THREAD

**Issue by aheinz-sg** [FriendsOfSymfony/FOSElasticaBundle#797]
Using ElasticaBundle v3.0.8, with configuration along the lines of:
```YAML
fos_elastica:
    indexes:
        search:
            use_alias: true
            index_name: my_index
            types:
                product:
                    mappings:
                        name: { analyzer: standard }
```
Executing the following command throws an exception
```sh
$ app/console fos:elastica:populate --no-reset
Populating search/product, 32.9% (100/304), 113 objects/s (RAM : current=15Mo peak=17Mo)
Populating search/product, 65.8% (200/304), 368 objects/s (RAM : current=15Mo peak=18Mo)
Populating search/product, 98.7% (300/304), 421 objects/s (RAM : current=18Mo peak=20Mo)
Populating search/product, 100.0% (304/304), 394 objects/s (RAM : current=17Mo peak=20Mo)
Refreshing search
  [Elastica\Exception\ResponseException]        
  IndexMissingException[[my_index] missing]
```

I've chased it down a little and I believe the issue is that [PopulateCommand.php:129](https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/3.0.x/Command/PopulateCommand.php#L129) is not being skipped when --no-reset is used, unlike [PopulateCommand.php:114](https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/3.0.x/Command/PopulateCommand.php#L114).
