### ISSUE TITLE
Issue with custom property

### ISSUE THREAD

**Issue by yellow1912** [FriendsOfSymfony/FOSElasticaBundle#804]
Since I have to manually calculate the product price before setting it to the index, I have no way to use the normal mapping but have to rely on customProperty via listener to set price.

The problem is that my price is in string type (since we deal with very large number which PHP may not be able to handle correctly in integer form). 

``` php
$document->set('price', $somePrice);
```

Since there is no way to specify the type of price here, ElasticSearch then interprets it as string and store as string. 

What should I do in this case to specify the type?

**Comment by merk** [comment]
I have sent a PR that lets you set property_path: false on a defined mapping property so it will not be automatically calculated..

https://github.com/FriendsOfSymfony/FOSElasticaBundle/pull/794

If you could test it and let me know if it needs any improvements, I'd appreciate it

**Comment by yellow1912** [comment]
Hi Merk,

If the value is already a string, with or without transformation it's still a string isn't it? I think what I need here is to have elastica respect the type mapping for that custom property field which I already defined?

**Comment by merk** [comment]
If you define the mapping in fos_elastica in your config.yml file as the proper type ElasticSearch will coerce the type correctly regardless of if its a string or a number.

**Comment by yellow1912** [comment]
Weird, I already have something like this:

```yaml
types:
                product:
                    mappings:
                        id:
                            type: long
                        name:
                            type: multi_field
                            fields:
                                ngram:
                                    type: string
                                    analyzer: ngram_analyzer
                        description:
                            type: string
                            search_analyzer: startswith
                            index_analyzer: startswith
                        price:
                            type: long
                        updated:
                            type: date
                            format: basic_date_time
                        enabled:
                            type: boolean
```
