### ISSUE TITLE
Error in Mapping Builder

### ISSUE THREAD

**Issue by huitiemesens** [FriendsOfSymfony/FOSElasticaBundle#830]
since last update ( 3.1 ) i can t populate my data without erros . here is the error message : 

$ php app/console fos:elastica:populate --verbose
Resetting recetas

Fatal error: Cannot unset string offsets in C:\xampp\htdocs\rn\vendor\friendsofsymfony\elastica-bundle\Index\MappingBuilder.php on line 115

  [Symfony\Component\Debug\Exception\FatalErrorException]
  Error: Cannot unset string offsets

Exception trace:
 () at C:\xampp\htdocs\rn\vendor\friendsofsymfony\elastica-bundle\Index\MappingBuilder.php:115

fos:elastica:populate [--index[="..."]] [--type[="..."]] [--no-reset] [--offset="..."] [--sleep="..."] [--batch-size="..."] [--ignore-errors] [--no-overwrite-fo
rmat]

i use a manual provider , according to your documentation for one of my three type, everything was working fine on 3.0.5 but not anymore :( 

here is my config.yml

```
     #ELASTIC SEARCH
fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    serializer:
        callback_class: FOS\ElasticaBundle\Serializer\Callback
        serializer: serializer
    indexes:
        recetas:
            client: default
            settings:
                index:
                    analysis:
                        analyzer:
                            custom_search_analyzer:
                                type: custom
                                tokenizer: standard
                                filter   : [standard, lowercase, asciifolding]
                            custom_index_analyzer:
                                type: custom
                                tokenizer: standard
                                filter   : [standard, lowercase, asciifolding]
                        filter:
                            custom_filter:
                                type: "edgeNGram"
                                side: front
                                min_gram: 3
                                max_gram: 20
            types:
                Recipe:
                    mappings: 
                        name: { search_analyzer: custom_search_analyzer, index_analyzer: custom_index_analyzer, type: string }
                        slug: { search_analyzer: custom_search_analyzer, index_analyzer: custom_index_analyzer, type: string }
                    persistence:
                        driver: orm # orm, mongodb, propel are available
                        model:  recetas\AppBundle\Entity\Recipe\Recipe
                        provider: ~
                        listener: ~
                        finder: ~
                Ingredient:
                    mappings:
                        name: { search_analyzer: custom_search_analyzer, index_analyzer: custom_index_analyzer, type: string }
                        slug: { search_analyzer: custom_search_analyzer, index_analyzer: custom_index_analyzer, type: string }
                    persistence:
                        driver: orm # orm, mongodb, propel are available
                        model:  recetas\AppBundle\Entity\Recipe\Ingredient
                        provider: ~
                        listener: ~
                        finder: ~
                Search:
                    mappings:
                        value: { search_analyzer: custom_search_analyzer, index_analyzer: custom_index_analyzer, type: string}
                        date:  { type: date }
                        provider: recetas\AppBundle\Service\SearchProvider
```
here is my manual provider

     <?php

namespace recetas\AppBundle\Service;

use FOS\ElasticaBundle\Provider\ProviderInterface;
use Elastica\Type;
use Elastica\Document;

class SearchProvider implements ProviderInterface
{
    protected   $searchType;
    private     $search;

    public function __construct(Type $searchType)
    {
        $this->searchType = $searchType;
    }

    public function add( $search )
    {
        $this->search = $search;
        $this->populate();
    }

    /**
     * Insert the repository objects in the type index
     *
     * @param \Closure $loggerClosure
     * @param array    $options
     */
    public function populate(\Closure $loggerClosure = null, array $options = array())
    {
        if ($loggerClosure) {
            $loggerClosure('Indexing searches');
        }

        $date  = time();

        $document = new Document();
        $document->setData(array('value' => $this->search, 'date' => $date ) );
        $this->searchType->addDocuments(array($document));
        $this->searchType->getIndex()->refresh();
    }
}

and finally my service.yml

    services:

    recetas.search:
        class: recetas\AppBundle\Service\Search
        arguments:  [@fos_elastica.manager.orm]

    recetas.search_provider:
        class: recetas\AppBundle\Service\SearchProvider
        arguments:
            - @fos_elastica.index.recetas.search
        tags:
            - { name: fos_elastica.provider, index: recetas, type: Search }

i use elastic search for both indexing my entities ( ingredients et recipe ) and indexing my search result ( which is not related to an entity ), each time a user make a search , i add it to elastic search through the manual provider.

hope this will help you finding out the issue.

PS : i tried to reverse to a minor version ( 3.0.6 ) there is still an error but the exception is a bit different : 

$ php app/console fos:elastica:populate --verbose
Resetting recetas

  [Symfony\Component\Debug\Exception\ContextErrorException]
  Warning: Illegal string offset 'type'

Exception trace:
 () at C:\xampp\htdocs\rn\vendor\friendsofsymfony\elastica-bundle\Index\MappingBuilder.php:108
 Symfony\Component\Debug\ErrorHandler->handleError() at C:\xampp\htdocs\rn\vendor\friendsofsymfony\elastica-bundle\Index\MappingBuilder.php:108
 FOS\ElasticaBundle\Index\MappingBuilder->fixProperties() at C:\xampp\htdocs\rn\vendor\friendsofsymfony\elastica-bundle\Index\MappingBuilder.php:81

 FOS\ElasticaBundle\Index\MappingBuilder->buildTypeMapping() at C:\xampp\htdocs\rn\vendor\friendsofsymfony\elastica-bundle\Index\MappingBuilder.php
:36
 FOS\ElasticaBundle\Index\MappingBuilder->buildIndexMapping() at C:\xampp\htdocs\rn\vendor\friendsofsymfony\elastica-bundle\Index\Resetter.php:71
 FOS\ElasticaBundle\Index\Resetter->resetIndex() at C:\xampp\htdocs\rn\vendor\friendsofsymfony\elastica-bundle\Command\PopulateCommand.php:114
 FOS\ElasticaBundle\Command\PopulateCommand->populateIndex() at C:\xampp\htdocs\rn\vendor\friendsofsymfony\elastica-bundle\Command\PopulateCommand.
php:97
 FOS\ElasticaBundle\Command\PopulateCommand->execute() at C:\xampp\htdocs\rn\vendor\symfony\symfony\src\Symfony\Component\Console\Command\Command.p
hp:257
 Symfony\Component\Console\Command\Command->run() at C:\xampp\htdocs\rn\vendor\symfony\symfony\src\Symfony\Component\Console\Application.php:882
 Symfony\Component\Console\Application->doRunCommand() at C:\xampp\htdocs\rn\vendor\symfony\symfony\src\Symfony\Component\Console\Application.php:1
95
 Symfony\Component\Console\Application->doRun() at C:\xampp\htdocs\rn\vendor\symfony\symfony\src\Symfony\Bundle\FrameworkBundle\Console\Application
.php:96
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at C:\xampp\htdocs\rn\vendor\symfony\symfony\src\Symfony\Component\Console\Application
.php:126
 Symfony\Component\Console\Application->run() at C:\xampp\htdocs\rn\app\console:27

fos:elastica:populate [--index[="..."]] [--type[="..."]] [--no-reset] [--offset="..."] [--sleep="..."] [--batch-size="..."] [--ignore-errors]
