### ISSUE TITLE
Circular reference when injecting the repository to model_to_elastica transformer

### ISSUE THREAD

**Issue by dwaligora** [FriendsOfSymfony/FOSElasticaBundle#832]
Hi Guys, like I mentioned in the topic I'm getting the following error:

```
Circular reference detected for service "doctrine.orm.default_entity_manager", path: "doctrine.orm.default_entity_manager -> doctrine.dbal.default_connection -> fos_elastica.object_persister.myindex.providers -> myservice".
```

when try injecting the repository, which is a service created by the `factory_method`, into the `model_to_transformer` service. Any idea what may cause that and how to solve that to avoid injecting the whole container? Thanks in advance for any help!

Code:
```yml
# Elastica config
providers:
          persistence:
              driver: orm
              model: Account\Provider\CommonBundle\Entity\Provider
              elastica_to_model_transformer:
                  service: application.transformer.elastic_response
              model_to_elastica_transformer:
                  service: account.provider.common.transformer.provider_to_elastic
              listener: ~
              finder: ~
          mappings:

# Service definition
verification.common.repository.provider_verification:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - Verification\CommonBundle\Entity\ProviderVerification

account.provider.common.transformer.provider_to_elastic:
        parent: fos_elastica.model_to_elastica_transformer
        class: Account\Provider\CommonBundle\Transformer\ProviderToElasticTransformer
        calls:
            - [setRepository, [@verification.common.repository.provider_verification]]
```
