### ISSUE TITLE
service custom ElasticaToModelTransformer not in ElasticaToModelTransformerCollections'index

### ISSUE THREAD

**Issue by kokmok** [FriendsOfSymfony/FOSElasticaBundle#856]
Hi,
when I use a custom ElasticaToModelTransformer as a service. My finder's ElasticaToModelTransformerCollection doesn't receive it.

Exemple : 
config.yml
```
fos_elastica:
    indexes:
        myIndex:
            finder: ~
           #....
            types:
                user:
                    #...
                post:
                      #....
                    persistence:
                        driver: orm 
                        model: P4M\CoreBundle\Entity\Post
                        provider: ~
                        finder: ~
                        listener:
                            is_indexable_callback: "isSearchable"
                        repository: P4M\CoreBundle\SearchRepository\PostRepository
                        elastica_to_model_transformer:
                            service: p4m.transformers.elastica.post
                wall:          
                      #.... 
```

SomeController.php
```
$this->container->get('fos_elastica.finder.myIndex');
$results = $finder->find($keyword);
```

I get this error : 

ContextErrorException: Notice: Undefined index: post in [path]\vendor\friendsofsymfony\elastica-bundle\Transformer\ElasticaToModelTransformerCollection.php line 56 

if i dump my finder, I see that my ElasticaToModelTransformer is not in the collection.
```
TransformedFinder {#586 ▼
  #searchable: Index {#315 ▶}
  #transformer: ElasticaToModelTransformerCollection {#587 ▼
    #transformers: array:2 [▼
      "user" => ElasticaToModelTransformer {#593 ▶}
      "wall" => ElasticaToModelTransformer {#591 ▶}
    ]
  }
}

```

I'm using symfony 2.3.x and fosElastica 3.0.x
