### ISSUE TITLE
parent definition

### ISSUE THREAD

**Issue by webspin** [FriendsOfSymfony/FOSElasticaBundle#859]
I try to implement a parent-child relationship, but this does not get indexed:

```
indexes:
        app:
            finder: ~
            types:
                auction:
                    mappings:
                        id: ~
                        status: ~
                        translations:
                            type: nested
                            properties:
                                name: ~
                                description: ~
                    persistence:
                        driver: orm
                        model: Vavato\ApiBundle\Entity\Auction
                        provider: ~
                        listener:
                            immediate: ~
                        finder: ~
                lot:
                    _parent:
                        type: "auction"
                        identifier: "id"
                        property: "auction"
                    mappings:
                        number: ~
                        enddate: { type: date }
                        translations:
                            type: nested
                            properties:
                                name: ~
                                shortDescription: ~
                                longDescription: ~
                        subcategories:
                            type: nested
                            properties:
                                translations:
                                    type: nested
                                    properties:
                                        name: ~
                    persistence:
                        driver: orm
                        model: Vavato\ApiBundle\Entity\Lot
                        provider: ~
                        listener:
                            immediate: ~
                        finder: ~
                        repository: Vavato\ApiBundle\SearchRepository\LotRepository
```

What is wrong?
