### ISSUE TITLE
Undefined index

### ISSUE THREAD

**Issue by cmedinamoenne** [FriendsOfSymfony/FOSElasticaBundle#866]
Hello my friends!
I try to search in the entire index, but I obtain a Server error:

> Notice: Undefined index: bluecoat-syslog
> 500 Internal Server Error - ContextErrorException

in vendor/friendsofsymfony/elastica-bundle/Transformer/ElasticaToModelTransformerCollection.php at line 56   -

```
$transformed = array();
foreach ($sorted as $type => $objects) {
    $transformedObjects = $this->transformers[$type]->transform($objects);
    $identifierGetter = 'get'.ucfirst($this->transformers[$type]->getIdentifierField());
    $transformed[$type] = array_combine(
    array_map(
```

 Anyone know what happens? I think, maybe, this is an bug

my config.yml

```
fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        log:
            client: default
            index_name: log-2015.04.20
            finder: ~
            types:
                bluecoat-syslog:
                    mappings:
                        message: ~
```

and my controller

```
public function reportAction(Request $request)
{
    $finder = $this->container->get('fos_elastica.finder.log');

    $results = $finder->find('ERROR');

    $parameters = array("results" => $results);

    return $this->render('MyCoreBundle:Core:report.html.twig', $parameters);
}
```

Regards and thanks!
