### ISSUE TITLE
How to set Timeout in configuration?

### ISSUE THREAD

**Issue by Giuffre** [FriendsOfSymfony/FOSElasticaBundle#869]
Like Elastica\Client, i want to set timeout for the client provided by FOSElasticaBundle. It is possibile to put it through the configuration of the bundle?

**Comment by oleg-andreyev** [comment]
Possible.

```
fos_elastica:
    clients:
        default:
            connections:
                - { host: localhost, port: 9200, timeout: 15 }
```
