### ISSUE TITLE
Possible to use a different finder within an entity repository?

### ISSUE THREAD

**Issue by robcaw** [FriendsOfSymfony/FOSElasticaBundle#880]
I've been slaving away at a bug where my repository isn't returning any results, but the same query on elastic itself does return the correct results.

Anyway, it turns out my repository isn't using the right index, hence the lack of results.

Is it possible to choose the index name of the repository you want? E.g:

```php
$repo1 = $manager->getRepository('Acme\AcmeBundle\Entity\Article', 'article_index');
$repo2 = $manager->getRepository('Acme\AcmeBundle\Entity\Article', 'article_temp_index');
```

**Comment by robcaw** [comment]
I should mention that this is only an issue if you use the manager. It's possible to create service for the repository and just inject the correct finder yourself.

**Comment by brice** [comment]
> I should mention that this is only an issue if you use the manager to get the repository. It's possible to create service for the repository and just inject the correct finder yourself.

How you does that?

I try this but i'm not sure that the right  things to do : 
```
services:
    app.search_repository:
        class: MyApp\Repository\ElasticaRepository
        arguments:
            - @fos_elastica.finder.app
    app.search_repository_member:
        class: MyApp\Repository\ElasticaRepository
        arguments:
            - @fos_elastica.finder.app.role
```

Is there something more clever to do in the repository?

Thanks.
