### ISSUE TITLE
listener not working

### ISSUE THREAD

**Issue by niepi** [FriendsOfSymfony/FOSElasticaBundle#897]
Hi,

I'm using v3.1.4 with a normal Symfony entity->persists->flush setup, but the listeners are not triggered. 

The console command ```fos:elastica:populate``` is working fine.

Any idea what could be the problem?

My config is
```
fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        search:
            types:
                article:
                    mappings:
                        title: ~
                        body: ~
                    persistence:
                        driver: orm
                        model: AppBundle\Entity\Article
                        provider: ~
                        listener: ~
                            immediate: ~
                        finder: ~
```
