### ISSUE TITLE
Propagate changes from ORM to ES

### ISSUE THREAD

**Issue by tgalery** [FriendsOfSymfony/FOSElasticaBundle#901]
Hi and sorry to pose this question here. I'm using this bundle (`v 3.1`) in a symfony2 application that uses doctrine `2.2` to talk to elastic search. I was assuming that changes made in the DB via doctrine would be automatically picked up and propagated to ES. However, this doesn't seem to be the case, e.g. changes in the name of a user wouldn't be reflected on the ES index. Is this the intended behaviour of the library ? if not, could you point out what is wrong in my config ?

```yml
user:
                    _all:
                        index_analyzer: nGram_analyser
                        search_analyzer: whitespace_analyzer
                    mappings:
                        id:
                            type: integer
                            index: not_analyzed
                        name:
                            type: string
                        picture_hash:
                            type: string
                            index: not_analyzed
                        is_professor:
                            type: boolean
                            index: not_analyzed
                    persistence:
                        driver: orm
                        model: Ulife\UserBundle\Entity\User
                        provider: ~
                        listener:
                            immediate: ~
                        finder: ~
```

On the other hand, if changes in the DB are not meant to be propagated automatically to ES, could you point me to a way in which this could be achieved ?
