### ISSUE TITLE
Config for indexable_callback not being recognized.

### ISSUE THREAD

**Issue by haburka** [FriendsOfSymfony/FOSElasticaBundle#906]
Hello, I can not figure out how to use this indexable_callback option. I've read two other issues :
https://github.com/FriendsOfSymfony/FOSElasticaBundle/issues/287
https://github.com/FriendsOfSymfony/FOSElasticaBundle/pull/755
but I can't figure it out. Please help. 
I get this error

Unrecognized options "indexable_callback" under "fos_elastica.indexes.app.types.talent" 

And my config is like this: 
```yaml
fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        app:
            client: default
            types:
                talent:
                    indexable_callback: 'isIndexable'
                    mappings:
                        firstName: ~
                        lastName: ~
                        emailAddresses: ~
                    persistence:
                        # the driver can be orm, mongodb or propel
                        # listener and finder are not supported by
                        # propel and should be removed
                        driver: orm
                        model: JsrBundle:Talent
                        provider: ~
                        listener: ~
                        finder: ~

            finder: ~
```
