### ISSUE TITLE
Property Accessor for nullable associations

### ISSUE THREAD

**Issue by AliHichem** [FriendsOfSymfony/FOSElasticaBundle#915]
Hi ,

Thank you guys for this awesome bundle ! while I'm using the property accessor feature from SF2 introduced to this bundle since v3.1 I'm getting a little problem: if for instance I have a mapping attribute "image" that is behind the scene a doctrine association to Image Entity I can use this mapping :

```
mappings:
   image: 
     property_path: image[id]
```

but if that association can be nullable I get this error 

```
PropertyAccessor requires a graph of objects or arrays to operate on, but it found type "NULL" while trying to traverse path "image[id]" at property "id".
```

which make sense since the property accessor is not configured to ignore accessing the path if the input is NULL. 

How can I solve this ?

**Comment by zanardigit** [comment]
As a workaround you can create an additional getter that always returns a valid value, e.g.

    public function getImageId() 
    {
        if (empty($this->getImage()) {
            return 0;
        }

        return $this->getImage()->getId();
    }

And then in your mappings:

    mappings:
        imageid: ~

**Comment by AliHichem** [comment]
Thank you for your answer but this is not resolving the issue : the purpose of the property accessor is to make this kind of nested access automatic, what's the good of having property accessor integration in this bundle if I'm not gonna use it at all and implement everything by my self ? 

Anyway as a better workaround I did this : 
```
image:
   type: "nested"
   properties:
        web_path: 
             index: not_analyzed
```
(in this example I access "web_path" property as it is the real property I'm trying to access.)
This way even if "image" is null I won't have any error after doctrine persistence as I will get an object with a web_path property that has null as value.

The thing is that property accessor is supposed to avoid you having nested object for association if you only require one single property to persist in ES. The only problem that won't work if you're association itself is nullable ..

**Comment by jxmallett** [comment]
This seemed like a silly limitation of the `PropertyAccessor` so I got around it by making a new `PropertyAccessor` which happily returns `null` when an association is `null`. Here's my setup:

```php
namespace AppBundle\Transformer;

use Symfony\Component\PropertyAccess\PropertyAccessor;

class QuietPropertyAccessor extends PropertyAccessor
{
    public function getValue($objectOrArray, $propertyPath)
    {
        try {
            return parent::getValue($objectOrArray, $propertyPath);
        } catch (\Exception $e) {
            return null;
        }
    }
}
```

```yaml
#services.yml
quiet_property_accessor:
    class: AppBundle\Transformer\QuietPropertyAccessor

my_model_to_elastica_transformer:
    class: FOS\ElasticaBundle\Transformer\ModelToElasticaAutoTransformer
    arguments: [[], "@event_dispatcher"]
        calls:
            - [setPropertyAccessor, ["@quiet_property_accessor"]]
```

```yaml
#Elastica config
fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        app:
            finder: ~
            types:
                my_entity:
                    mappings:
                        field1: ~
                        nullable_field:
                            property_path: a_method_that_may_return_null.a_property

                    persistence:
                        driver: orm
                        model: AppBundle\Entity\MyEntity
                        provider: ~
                        listener:
                            immediate: ~
                        finder: ~
                        model_to_elastica_transformer:
                            service: my_model_to_elastica_transformer
```

It's annoying to always have to specify `model_to_elastica_transformer` and I'm not sure what it does to indexing speed (nothing good, I'm assuming, because of all the exception catching) but it means you can write `PropertyAccessor` expressions without having to worry about whether you'll get a 'valid' return value.

**Comment by XWB** [comment]
👍

**Comment by pbowyer** [comment]
Thanks @jxmallett I got the exact same error today and your workaround sorted it.

For others needing this 6.5 years(!) after the solution above was shared, the YAML changes remain the same (except there is one incorrect indentation, it needs to be
```yaml
    }
}
#services.yml
quiet_property_accessor:
    class: AppBundle\Transformer\QuietPropertyAccessor

my_model_to_elastica_transformer:
    class: FOS\ElasticaBundle\Transformer\ModelToElasticaAutoTransformer
    arguments: [[], "@event_dispatcher"]
    calls:
        - [setPropertyAccessor, ["@quiet_property_accessor"]]
```
but the PHP class is now
```php
<?php

namespace App\Lib\Elastica\Transformer;

use Symfony\Component\PropertyAccess\PropertyAccessor;
use Symfony\Component\PropertyAccess\PropertyPathInterface;

class QuietPropertyAccessor extends PropertyAccessor
{
    public function getValue(object|array $objectOrArray, string|PropertyPathInterface $propertyPath): mixed
    {
        try {
            return parent::getValue($objectOrArray, $propertyPath);
        } catch (\Exception $e) {
            return null;
        }
    }
}
```
