### ISSUE TITLE
Force Object persisting with nested object 

### ISSUE THREAD

**Issue by gouaille** [FriendsOfSymfony/FOSElasticaBundle#923]
Hi,

I'm having an issue with object persisting of a nested object.
Let's say i have the following mapping : 

 - product:
  - id
  - reference
  - quantity

 - device: 
  - id
  -  name
  -  device_type
   - product_id

My elastica.yml's index is like 
```
device:
  mappings:
    id:
        type: integer
    name: ~
    product:
      type: object
      properties:
        id:
          type: integer
        reference: ~
        quantity: 
          type: integer
```

In my application, i'm updating the quantity field on the product without doing any change to the device entity. ElasticSearch doesn't reindex the product data and i'm looking for a way to "force it". Is it possible ?

Thank's
