### ISSUE TITLE
Index / remove from index on property

### ISSUE THREAD

**Issue by dariuszp** [FriendsOfSymfony/FOSElasticaBundle#937]
Hi,
I'm trying to figure out this. How can I configure elastica so when bool property like "is_archived" is true/false, elastica will add/remove object?
Can I configure this or should I use event subscribers to do so?

// EDIT: sorry, you can close this one. I didn't notice at fist "is_indexable_callback". Work like a charm:

````
                category:
                    mappings:
                        title: ~
                    persistence:
                        driver: orm
                        model: MadmanLabs\ArticleBundle\Entity\Category
                        listener:
                            is_indexable_callback: isIndexable
                        provider:
                            query_builder_method: createIsActiveQueryBuilder
                            batch_size: 100
````
