### ISSUE TITLE
ActionRequestValidationException[Validation Failed: 1: id is missing;]

### ISSUE THREAD

**Issue by RuslanZavacky** [FriendsOfSymfony/FOSElasticaBundle#960]
Trying to understand how saving works, and have this code as proof of concept

``` php
$em = $this->get('doctrine.orm.default_entity_manager');

$rename = new RenameMe();
$rename->setName('Rename ' . microtime(true));
$rename->setKeywords('Keywords ' . microtime(true));
$em->persist($rename);
$em->flush($rename);

$rename->setName('Rename Updated ' . microtime(true));
$em->persist($rename);
$em->flush($rename);

$em->remove($rename);
$em->flush($rename);
```

It fails, when it tries to Update document, so it can't get to remove. This happens with such configuration

``` yaml
fos_elastica:
  clients:
    default: { host: localhost, port: 9200 }
  serializer:
    callback_class: FOS\ElasticaBundle\Serializer\Callback
    serializer: serializer
  indexes:
    app:
      index_name: app_%kernel.environment%
      types:
        rename:
          persistence:
            driver: orm
            model:  AppBundle\Entity\RenameMe
            repository: AppBundle\Repository\RenameMeRepository
            model_to_elastica_transformer:
              service: app.es.entity_transformer
            elastica_to_model_transformer:
              ignore_missing: true
            provider: ~
            listener:
              insert: true
              update: true
              delete: true
              immediate: false
```

When I change immediate: true, it succeed on Update, but then fails with the same error on Delete.
I've seen #508 #515 #517 and was under impression, that it now is working. I have 3.1.6 version, am I doing something wrong?
