### ISSUE TITLE
Elastica 3.0.0-beta1 BC breaks and Elasticsearch 2.0 compatibility

### ISSUE THREAD

**Issue by ruflin** [FriendsOfSymfony/FOSElasticaBundle#969]
Finally Elastica 3.0.0-beta1 is out. It is compatible with elasticsearch 2.0 but brings quite a few compatibility breaks. The full list can be found here: http://elastica.io/2015/11/26/release-3-dot-0-0-beta1/

I post this here as I assume this will also have quite an affect on the next versions of FOSElasticaBundle and its users. I would like to use this issue to discuss potential problems which will occur and how we can solve them. 

This is the first time Elastica does a beta release, but I think with this many changes it is worth to first get the early users on board for testing. So lets use this time to iron out the last bugs so we can ship a GA as soon as possible.

**Comment by merk** [comment]
Looking through the list of deprecations and breaks I don't think there is going to be much trouble with FOSElasticaBundle.

Feedback from people willing to try the latest releases together would be appreciated.

**Comment by yellow1912** [comment]
I would be glad to try on the new version and report any issue I may find. Is FOS ready to release a beta version to support new elastica?

**Comment by merk** [comment]
Depends on what changes are required - minor things that can support both Elastica 2 and 3 will just be released as a point release, otherwise we will have to consider what to do.

**Comment by ruflin** [comment]
@yellow1912 That would be nice if you could try it out. I plan to release 3.0.0 in the next days. The good news is, there are no bad issues reported yet. That could be for 2 reasons: There aren't any or nobody is using it yet :-)

**Comment by oscarjg** [comment]
Hello, with ElasticSearch 1.4.1 I can get matches by partial words, but with ElasticSearch 2.x only I get matches if I write the exact word. For example: I can get the word test tipping tes in 1.4.1. Otherwise I must to write test to get the result on 2.x.  I have the version  v3.1.6 of the bundle. 

Thanks for advance

**Comment by ruflin** [comment]
@oscarjg I think I need some more details here. Are you using FOSElasticaBundle? Which version of Elastica before and after? If it is only related to Elastica, I suggest to open a separate issue in Elastica. This issue here is mainly target on "incompatibilty between Elastica and FOSElasticaBundle".

**Comment by oscarjg** [comment]
@ruflin Yes, I'm using FOSElasticaBundle (v.3.1.6) with the elastica (2.2.1). The only significant difference is the version of ElasticSearch. 1.4.1 (before) 2.1.0 (after).

This is my config
````
# Elastic search
fos_elastica:
    clients:
        default: %elastic_server%
    indexes:
        cs:
            index_name: %elastic_index%
            settings:
                index:
                    analysis:
                        analyzer:
                            custom_index_analyzer :
                                type:    custom
                                tokenizer: nGram
                                filter : [stopwords, asciifolding ,lowercase, snowball, elision, worddelimiter]
                            custom_search_analyzer :
                                type: custom
                                tokenizer: standard
                                filter: [stopwords, asciifolding ,lowercase, snowball, elision, worddelimiter]
                        tokenizer:
                            nGram:
                                type: nGram
                                min_gram: 2
                                max_gram: 20
                        filter:
                            snowball:
                                type: snowball
                                language: Spanish
                            elision:
                                type: elision
                                articles: [l, m, t, qu, n, s, j, d]
                            stopwords:
                                type: stop
                                stopwords: [_spanish_]
                                ignore_case: true
                            worddelimiter :
                                type: word_delimiter
            types:
                search:
                    mappings:
                        id: ~
                        site: ~
                        subSite: ~
                        locale: ~
                        entityId: ~
                        entityType: ~
                        entityClass: ~
                        url: ~
                        introTitle:
                            boost: 5
                            index_analyzer: custom_index_analyzer
                            search_analyzer: custom_search_analyzer
                        name:
                            boost: 5
                            index_analyzer: custom_index_analyzer
                            search_analyzer: custom_search_analyzer
                        title:
                            boost: 10
                            index_analyzer: custom_index_analyzer
                            search_analyzer: custom_search_analyzer
                        subTitle:
                            boost: 5
                            index_analyzer: custom_index_analyzer
                            search_analyzer: custom_search_analyzer
                        body:
                            boost: 4
                            index_analyzer: custom_index_analyzer
                            search_analyzer: custom_search_analyzer
                        featured:
                            boost: 10
                        reference:
                            boost: 10
                        images:
                            type: object
                        categories:
                            type: object
                        weight: ~
                        enabled: ~
                        creationDate: ~
                        updatedDate: ~
                        publishedDate: ~
                        unpublishedDate: ~
                    persistence:
                        driver: orm
                        model: ComitiumSuite\Components\Search\Entity\Search
                        provider: ~
                        listener: ~
                        finder: ~
                        elastica_to_model_transformer:
                            hydrate: false
```
