### ISSUE TITLE
Unrecognized option "Entity" under fos_elastica.indexes.types

### ISSUE THREAD

**Issue by fanchGit520** [FriendsOfSymfony/FOSElasticaBundle#975]
Hello,
My problem is that my entity is not recognized as an option under " fos_elastica.indexes.populate "
when cmd "php app/console fos:elastica:populate"
1 tab = 4 spaces
I test with upper, lower ucfirst, ...
Here is my fos_elastica.yml

fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        achats:
            client: default
        types:
            devis:
                mappings:
                    id: { type: integer }
                    document: { type: AchatsBundle\Entity\Document }
                    date_add: { type: date, format: "dd-mm-YYYY" }
                    date_upd: { type: date, format: "dd-mm-YYYY" }
                persistence:
                    driver: orm
                    model: AchatsBundle\Entity\Devis
                    finder: ~
                    provider: ~
                    listener: ~

Thanks

**Comment by behramcelen** [comment]
Probably there is an indentation problem on your yaml configuration. Can you paste there with indentation for clear seen. Like;
```
fos_elastica:
    indexes:
        app:
            types:
                user:
                    mappings:
                        username: ~
                        firstName: ~
                        lastName: ~
                        email: ~
```
