### ISSUE TITLE
GeoDistance - result is Empty 

### ISSUE THREAD

**Issue by nirgendswo** [FriendsOfSymfony/FOSElasticaBundle#976]
Hallo,

i'm not sure if this is a bug, but there is no Error Message and if i add a GeoDistance-Filter to the type company the result is empty. Other Filters i used are Working.

The Longitude and Latitude Values are saved as seperated Columns, and i use a Trait extend the Entities.  Each Company has a Location and this Location is extend by the Trait. To get the Location for Elastica i use this Function in the Trait,

```
    /**
     *  @VirtualProperty
     *
     */
    public function getPin()
    {
        $result = null;

        if ($this->getLatitude() && $this->getLongitude())
        {
            $result = array(
                "lat" => $this->getLatitude(),
                "lon" => $this->getLongitude()
            );
        }

        return $result;
    }
```

The config for Company looks like this,

```
company:
    mappings:
        name: ~
        location:
            type: object
            properties:
                pin:
                    type: geo_point
```

And this is the part where i add the filter,

```
$boolFilter = new Bool();
$boolFilter->addMust(new GeoDistance('location.pin',
    array(
        'lat' => $location['latitude'],
        'lon' => $location['longitude']
    ),
   $location['radius']
));

$query->setFilter($boolFilter);
```

BUT, the search is empty...
