### ISSUE TITLE
Elasticsearch doesn't update indexes

### ISSUE THREAD

**Issue by mcbuckets** [FriendsOfSymfony/FOSElasticaBundle#980]
I'm using this configuration for elasticsearch powered search feature. Now when i populate indexes the search function works fine and i get desired results. But, after some time(couple of hours) the search stops working and results are plain wrong. The application uses cron jobs to update entities every 15 minutes noted in the config(and other data). How do i get indexes updated?

I'm using 3.0 version.

```
 fos_elastica:
    clients:
         default: { host: localhost, port: 9200 }
    indexes:
          kladise:
    finder: ~
    types:
        blogs:
            mappings:
                title: ~
                shortContent: ~
            persistence:
                driver: orm
                model: Acme\BlogBundle\Entity\Post
                provider: ~
                listener: ~
                finder: ~
        tips:
            mappings:
                title: ~
                shortContent: ~

            persistence:
                driver: orm
                model: Acme\TipsterBundle\Entity\Tip
                provider: ~
                listener: ~
                finder: ~

        soccer_players:
            mappings:
                firstName: ~
                lastName: ~
                name: ~

            persistence:
                driver: orm
                model: Acme\SoccerBundle\Entity\People
                provider: ~
                listener: ~
                finder: ~

        soccer_teams:
            mappings:
                clubName: ~
                shortName: ~
                officialName: ~

            persistence:
                driver: orm
                model: Acme\SoccerBundle\Entity\Team
                provider: ~
                listener: ~
                finder: ~

        hockey_players:
            mappings:
                firstName: ~
                lastName: ~
                name: ~

            persistence:
                driver: orm
                model: Acme\HockeyBundle\Entity\People
                provider: ~
                listener: ~
                finder: ~

        hockey_teams:
            mappings:
                clubName: ~
                shortName: ~
                officialName: ~

            persistence:
                driver: orm
                model: Acme\HockeyBundle\Entity\Team
                provider: ~
                listener: ~
                finder: ~

        handball_players:
            mappings:
                firstName: ~
                lastName: ~
                name: ~

            persistence:
                driver: orm
                model: Acme\HandballBundle\Entity\People
                provider: ~
                listener: ~
                finder: ~

        handball_teams:
            mappings:
                clubName: ~
                shortName: ~
                officialName: ~

            persistence:
                driver: orm
                model: Acme\HandballBundle\Entity\Team
                provider: ~
                listener: ~
                finder: ~

        basketball_players:
            mappings:
                firstName: ~
                lastName: ~
                name: ~

            persistence:
                driver: orm
                model: Acme\BasketballBundle\Entity\People
                provider: ~
                listener: ~
                finder: ~

        basketball_teams:
            mappings:
                clubName: ~
                shortName: ~
                officialName: ~

            persistence:
                driver: orm
                model: Acme\BasketballBundle\Entity\Team
                provider: ~
                listener: ~
                finder: ~
```
