### ISSUE TITLE
Http Headers configuration seems not working as expected.

### ISSUE THREAD

**Issue by Raffaello** [FriendsOfSymfony/FOSElasticaBundle#994]
I configured the bundle using these parameters:
```
fos_elastica:
    clients:
        default:
            headers:
              Authorization: "Basic blablablah"
            servers:
              - { host: "%elasticsearch.node1.host%", port: "%elasticsearch.node1.port%" }
              - { host: "%elasticsearch.node2.host%", port: "%elasticsearch.node2.port%" }
            connection_strategy: RoundRobin
```

And I have got an exception in the configuration:

```
Whoops, looks like something went wrong.

1/1
InvalidTypeException in ScalarNode.php line 36:
Invalid type for path "fos_elastica.clients.default.headers". Expected scalar, but got array.
```

Any helps would be appreciated.
